begin;
do $test$
declare c uuid:='4b070000-0000-4000-8000-000000000001';requester uuid:='4b070000-0000-4000-8000-000000000002';approver uuid:='4b070000-0000-4000-8000-000000000003';a1 uuid;a2 uuid;cfg uuid;adj uuid;r jsonb;controls jsonb;blocked boolean:=false;d numeric;h numeric;
begin
 insert into public.companies(id,legal_name,display_name) values(c,'M4B manual','M4B manual');insert into auth.users(id,aud,role,email,encrypted_password) values(requester,'authenticated','authenticated','m4b-requester@example.com',''),(approver,'authenticated','authenticated','m4b-approver@example.com','');insert into public.user_roles(user_id,role_id,company_id) select u,id,c from public.roles cross join(values(requester),(approver))x(u) where code='direccion_admin';perform set_config('request.jwt.claim.role','authenticated',true);perform set_config('request.jwt.claim.sub',requester::text,true);
 insert into public.accounting_accounts(company_id,code,name,account_type,normal_balance,level) values(c,'1000','Caja','asset','debit',1),(c,'2000','Puente','liability','credit',1);a1:=(select id from public.accounting_accounts where company_id=c and code='1000');a2:=(select id from public.accounting_accounts where company_id=c and code='2000');
 insert into public.accounting_accounts(company_id,code,name,account_type,normal_balance,level) select c,'C'||n,'Control '||n,'asset','debit',1 from generate_series(1,9)n;select jsonb_object_agg(k,a.id) into controls from (values('accounts_receivable','C1'),('accounts_payable','C2'),('inventory','C3'),('cash','C4'),('banks','C5'),('vat_pending','C6'),('vat_collected','C7'),('vat_paid','C8'),('withholdings','C9'))x(k,code) join public.accounting_accounts a on a.company_id=c and a.code=x.code;
 r:=public.save_accounting_config(c,'MXN',current_date,'{"format":"4"}','{"vat_pending":"x","vat_collected":"x","vat_paid":"x","withholdings":"x"}',jsonb_build_object('adjustments',requester,'close',approver,'reopen',approver),'Manual',controls);cfg:=(r->>'id')::uuid;perform public.approve_accounting_config(cfg);perform public.create_accounting_period(c,to_char(current_date,'YYYY-MM'),date_trunc('month',current_date)::date,(date_trunc('month',current_date)+interval '1 month'-interval '1 day')::date);
 r:=public.submit_accounting_adjustment(c,'reclassification',current_date,'Reclasificación controlada','Corrección documentada',jsonb_build_array(jsonb_build_object('line_number',1,'account_id',a1,'debit',50,'credit',0),jsonb_build_object('line_number',2,'account_id',a2,'debit',0,'credit',50)),'4b070000-0000-4000-8000-000000000010');adj:=(r->>'id')::uuid;if r->>'status'<>'submitted' or (select count(*) from public.accounting_journal_entries where company_id=c)<>0 then raise exception 'La solicitud contabilizó antes de aprobación.';end if;
 begin perform public.decide_accounting_adjustment(adj,'approve','Autoaprobación','4b070000-0000-4000-8000-000000000011');exception when others then blocked:=position('solicitante no puede' in lower(sqlerrm))>0;end;if not blocked then raise exception 'No se bloqueó la autoaprobación.';end if;
 perform set_config('request.jwt.claim.sub',approver::text,true);r:=public.decide_accounting_adjustment(adj,'approve','Validación independiente','4b070000-0000-4000-8000-000000000012');if r->>'status'<>'approved' then raise exception 'Aprobación separada falló.';end if;r:=public.reverse_accounting_adjustment(adj,current_date,'Corrección posterior','4b070000-0000-4000-8000-000000000013');if r->>'status'<>'reversed' then raise exception 'Reversa falló.';end if;
 select sum(debit),sum(credit) into d,h from public.accounting_journal_lines where company_id=c;if d<>100 or h<>100 or (select count(*) from public.accounting_journal_entries where company_id=c)<>2 then raise exception 'Aprobación/reversa no conservaron doble entrada.';end if;raise notice 'M4B manual: solicitud, segregación, aprobación y reversa validadas.';
end;$test$;
rollback;
