begin;
do $$
declare c uuid:=gen_random_uuid();u uuid:=gen_random_uuid();loc uuid:=gen_random_uuid();tax uuid:=gen_random_uuid();reg uuid:=gen_random_uuid();session uuid:=gen_random_uuid();cart uuid:=gen_random_uuid();payment uuid:=gen_random_uuid();ing uuid;dish uuid;soup uuid;water uuid;extra uuid;bundle uuid:=gen_random_uuid();g1 uuid:=gen_random_uuid();g2 uuid:=gen_random_uuid();o1 uuid:=gen_random_uuid();o2 uuid:=gen_random_uuid();i1 uuid;i2 uuid;req uuid:=gen_random_uuid();q jsonb;choice jsonb;payload jsonb;result jsonb;selections jsonb;balance numeric;before_revision integer;sale jsonb;sale_req uuid:=gen_random_uuid();
begin
 if has_function_privilege('authenticated','public.restaurant_pos_solo_price(uuid,uuid,uuid,uuid,timestamptz)','EXECUTE') or has_function_privilege('anon','public.save_restaurant_pos_selection(uuid,uuid,text,jsonb,uuid[],integer,uuid,integer,uuid)','EXECUTE') then raise exception 'Permisos públicos demasiado amplios';end if;
 insert into public.companies(id,legal_name,display_name,product_experience_code)values(c,'QA comidas','QA comidas','restaurant');
 insert into auth.users(id,aud,role,email,encrypted_password)values(u,'authenticated','authenticated',u||'@example.invalid','');
 insert into public.user_roles(user_id,role_id,company_id)select u,id,c from public.roles where code='direccion_admin';
 perform set_config('request.jwt.claim.role','authenticated',true);perform set_config('request.jwt.claim.sub',u::text,true);
 insert into public.locations(id,company_id,external_code,name,location_type)values(loc,c,'QA','Cocina QA','sucursal');
 insert into public.tax_categories(id,company_id,code,name)values(tax,c,'IVA16','IVA 16%');
 insert into public.tax_rates(tax_category_id,jurisdiction_code,rate,valid_from)values(tax,'MX',.16,now()-interval '1 day');
 ing:=(public.save_restaurant_ingredient_studio(c,'{"name":"Ingrediente QA","unit":"g","purchase_unit":"KG","purchase_factor":1000}',gen_random_uuid())->>'id')::uuid;
 insert into public.inventory_balances(company_id,location_id,product_id,quantity_on_hand)values(c,loc,ing,10000);
 payload:=jsonb_build_object('kind','dish','portions',1,'waste_percent',0,'components',jsonb_build_array(jsonb_build_object('product_id',ing,'quantity',100,'unit_code','g','base_unit_code','g')),'category','Pruebas','finish',true,'available',true,'final_price',116,'tax_category_id',tax,'assortment_ids','[]'::jsonb,'location_ids',jsonb_build_array(loc));
 dish:=(public.save_restaurant_studio(c,payload||'{"name":"Platillo QA"}',gen_random_uuid())->>'product_id')::uuid;
 soup:=(public.save_restaurant_studio(c,payload||'{"name":"Sopa QA","final_price":30}',gen_random_uuid())->>'product_id')::uuid;
 water:=(public.save_restaurant_studio(c,payload||'{"name":"Agua QA","final_price":20}',gen_random_uuid())->>'product_id')::uuid;
 extra:=(public.save_restaurant_studio(c,payload||'{"name":"Extra QA","final_price":11.6}',gen_random_uuid())->>'product_id')::uuid;
 insert into public.restaurant_menu_bundles(id,company_id,product_id,combo_price_amount)values(bundle,c,dish,174);
 insert into public.restaurant_menu_bundle_groups(id,company_id,bundle_id,name)values(g1,c,bundle,'Sopa'),(g2,c,bundle,'Agua');
 insert into public.restaurant_menu_bundle_options(id,company_id,group_id,product_id)values(o1,c,g1,soup),(o2,c,g2,water);
 insert into public.restaurant_menu_bundle_extras(company_id,bundle_id,product_id)values(c,bundle,extra);
 insert into public.cash_registers(id,company_id,location_id,code,display_name)values(reg,c,loc,'QA','Caja QA');
 insert into public.cash_sessions(id,company_id,cash_register_id,location_id,opened_by)values(session,c,reg,loc,u);
 insert into public.sale_carts(id,company_id,location_id,cash_register_id,cash_session_id,cashier_id)values(cart,c,loc,reg,session,u);
 insert into public.payment_methods(id,company_id,code,display_name,settlement_kind)values(payment,c,'CASH','Efectivo','cash_drawer');
 update public.product_prices set valid_from=now()-interval '1 second' where product_id in(dish,soup,water,extra);
 choice:=public.get_pos_restaurant_bundle_choice(cart,dish);
 if (choice->>'solo_price')::numeric is distinct from 116 or (choice#>>'{extras,0,final_price}')::numeric is distinct from 11.6 then raise exception 'Precios finales incorrectos: %',choice;end if;
 update public.product_prices set amount=68.965517 where product_id=extra;
 if (public.get_pos_restaurant_bundle_choice(cart,dish)#>>'{extras,0,final_price}')::numeric is distinct from 80 then raise exception 'Redondeó el impuesto antes de tiempo';end if;
 update public.product_prices set amount=10 where product_id=extra;
 update public.restaurant_menu_bundles set combo_price_amount=null where id=bundle;
 if public.get_pos_restaurant_bundle_choice(cart,dish)->>'combo_price' is not null then raise exception 'Inventó precio de paquete';end if;
 update public.restaurant_menu_bundles set combo_price_amount=174 where id=bundle;
 q:=public.save_restaurant_pos_selection(cart,dish,'solo','{}','{}',1,null,1,req);
 i1:=(public.list_sale_cart_bundle_instances(cart)#>>'{0,id}')::uuid;
 if (q->>'total_amount')::numeric<>116 then raise exception 'Precio solo incorrecto: %',q;end if;
 result:=public.save_restaurant_pos_selection(cart,dish,'solo','{}','{}',1,null,1,req);
 if result->>'revision'<>q->>'revision' then raise exception 'Reintento duplicó platillo';end if;
 selections:=jsonb_build_object(g1::text,jsonb_build_array(o1),g2::text,jsonb_build_array(o2));
 q:=public.save_restaurant_pos_selection(cart,dish,'complete',selections,array[extra],2,null,(q->>'revision')::integer,gen_random_uuid());
 select id into i2 from public.sale_cart_bundle_instances where cart_item_id in(select id from public.sale_cart_items where cart_id=cart)and mode='complete';
 if (q->>'total_amount')::numeric<>487.20 then raise exception 'Mezcla de modalidades/extras incorrecta: %',q;end if;
 if (select sum(quantity)from public.sale_cart_bundle_selections where instance_id=i2)<>4 then raise exception 'No multiplicó las elecciones';end if;
 update public.product_prices set amount=110 where product_id=dish;
 q:=public.quote_restaurant_pos_cart(cart);
 if (q->>'total_amount')::numeric<>498.80 then raise exception 'No recalculó el precio vigente de la parte solo';end if;
 update public.product_prices set amount=100 where product_id=dish;
 q:=public.quote_restaurant_pos_cart(cart);
 result:=public.preview_restaurant_pos_selection(cart,dish,'complete',selections,array[extra],1,i2,(q->>'revision')::integer);
 if (result#>>'{quote,total_amount}')::numeric<>301.60 then raise exception 'Vista previa incorrecta';end if;
 if public.quote_restaurant_pos_cart(cart)->>'revision'<>q->>'revision' or (select quantity from public.sale_cart_bundle_instances where id=i2)<>2 then raise exception 'La vista previa dejó cambios';end if;
 before_revision:=(q->>'revision')::integer;
 begin perform public.save_restaurant_pos_selection(cart,dish,'complete','{}',array[extra],2,i2,before_revision,gen_random_uuid());raise exception 'TEST: guardó selección incompleta';exception when others then if sqlerrm like 'TEST:%'then raise;end if;end;
 if public.quote_restaurant_pos_cart(cart)->>'revision'<>q->>'revision' then raise exception 'Una edición fallida cambió la venta';end if;
 update public.inventory_balances set quantity_on_hand=350 where product_id=ing and location_id=loc;
 begin perform public.save_restaurant_pos_selection(cart,dish,'complete',selections,array[extra],2,i2,before_revision,gen_random_uuid());raise exception 'TEST: permitió sobreconsumo agregado';exception when others then if sqlerrm like 'TEST:%'then raise;end if;end;
 update public.inventory_balances set quantity_on_hand=10000 where product_id=ing and location_id=loc;
 q:=public.save_restaurant_pos_selection(cart,dish,'solo','{}','{}',1,i2,before_revision,gen_random_uuid());
 if (q->>'total_amount')::numeric<>232 or exists(select 1 from public.sale_cart_items where cart_id=cart and product_id=extra) then raise exception 'Editar dejó extras sueltos: %',q;end if;
 q:=public.save_restaurant_pos_selection(cart,dish,'solo','{}','{}',0,i2,(q->>'revision')::integer,gen_random_uuid());
 q:=public.add_restaurant_bundle_to_cart(cart,dish,selections,array[extra],(q->>'revision')::integer,gen_random_uuid());
 select id into i2 from public.sale_cart_bundle_instances where cart_item_id in(select id from public.sale_cart_items where cart_id=cart)and mode='complete';
 -- Hold/resume preserves the actual persisted configuration.
 update public.sale_carts set status='held',held_at=now() where id=cart;
 if jsonb_array_length(public.list_sale_cart_bundle_instances(cart))<>2 then raise exception 'Espera perdió selecciones';end if;
 update public.sale_carts set status='active',held_at=null where id=cart;
 q:=public.quote_restaurant_pos_cart(cart);
 if (q->>'total_amount')::numeric<>301.60 then raise exception 'Retomar cambió precio';end if;
 perform set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
 begin perform public.save_restaurant_pos_selection(cart,dish,'solo','{}','{}',1,null,(q->>'revision')::integer,gen_random_uuid());raise exception 'TEST: permitió otro usuario';exception when others then if sqlerrm like 'TEST:%'then raise;end if;end;
 perform set_config('request.jwt.claim.sub',u::text,true);
 sale:=public.complete_restaurant_pos_sale(cart,(q->>'revision')::integer,'cash',payment,400,sale_req,null);
 select quantity_on_hand into balance from public.inventory_balances where product_id=ing and location_id=loc;
 if balance<>9500 then raise exception 'Consumo incorrecto: %, esperado 9500',balance;end if;
 result:=public.complete_restaurant_pos_sale(cart,(q->>'revision')::integer,'cash',payment,400,sale_req,null);
 if result->>'sale_id'<>sale->>'sale_id' or not(result->>'idempotent')::boolean then raise exception 'Cobro duplicado';end if;
 if not exists(select 1 from public.sale_item_bundle_instances where id=i2 and mode='complete' and jsonb_array_length(extras)=1) then raise exception 'No conservó opciones vendidas';end if;
 raise notice 'PASS: impuestos, precio faltante, mezcla, cantidades, extras, edición atómica, stock agregado, espera, permisos, cobro, consumo e idempotencia';
end$$;
rollback;
