"use client";

import { AlertCircle,CheckCircle2,ChevronDown,ChevronRight,CopyPlus,LoaderCircle,Plus,RefreshCw,Trash2,TrendingUp } from "lucide-react";
import { useCallback,useEffect,useMemo,useState,type FormEvent } from "react";
import { DataPagination,DataState,PageHeading,Table } from "@/app/components/ui/data";
import { Badge,Button,Input,Modal,Select } from "@/app/components/ui/primitives";
import { getSupabaseClient } from "@/app/lib/supabase";
import { useSatrapy } from "@/app/components/SatrapyProvider";

type BudgetStatus="draft"|"approved"|"superseded";
type ScopeType="company"|"location"|"responsible"|"category"|"location_category"|"responsible_category"|"product"|"location_product"|"responsible_product";
type BaseScope="company"|"location"|"responsible";
type CaptureMode="annual"|"quarterly"|"monthly";
type BudgetRow={
  id:string;name:string;description?:string|null;metric_code:"net_sales"|"gross_margin"|"units_sold";
  period_type:"monthly"|"quarterly"|"annual";period_start:string;period_end:string;scope_type:ScopeType;
  location_id?:string|null;collaborator_id?:string|null;category_id?:string|null;product_id?:string|null;
  scope_label:string;value:number;unit_code:string;status:BudgetStatus;budget_kind:"independent"|"distribution";
  actual_available:boolean;actual_value:number|null;actual_reason?:string|null;attainment_percent:number|null;remaining_value:number|null;projected_value:number|null;
  assigned_value:number|null;pending_distribution:number|null;distribution_excess:number|null;parent_version_id?:string|null;
};
type PageResult={items:BudgetRow[];pagination:{page:number;page_size:number;total:number};updated_at:string};
type Option={id:string;label:string;secondary?:string;category_id?:string};
type MonthlyAllocation={month:string;value:string};
type CommercialAllocation={key:string;option:Option|null;value:string};
type DetailDistribution=BudgetRow&{scope_label:string;actual_available:boolean;actual_value:number|null;attainment_percent:number|null};
type Detail={version:BudgetRow;actual:{available:boolean;value:number|null;reason?:string};previous_period:{available:boolean;value:number|null};series:Array<{date:string;actual:number|null;budget_pace:number}>;history:Array<{id:string;action:string;reason:string;occurred_at:string}>;distributions:DetailDistribution[]};

const METRICS=[
  {value:"net_sales",label:"Venta neta"},{value:"gross_margin",label:"Margen"},{value:"units_sold",label:"Unidades vendidas"},
];
const CAPTURE_MODES=[{value:"annual",label:"Anual"},{value:"quarterly",label:"Trimestral"},{value:"monthly",label:"Mensual"}];
const BASE_SCOPES=[{value:"company",label:"Toda la operación"},{value:"location",label:"Sucursal"},{value:"responsible",label:"Responsable"}];
const METRIC_LABEL:Record<string,string>={net_sales:"Venta neta",gross_margin:"Margen",units_sold:"Unidades vendidas"};
const STATUS_LABEL:Record<BudgetStatus,string>={draft:"Borrador",approved:"Aprobado",superseded:"Sustituido"};
const EVENT_LABEL:Record<string,string>={created:"Creación",approved:"Aprobación",superseded:"Sustitución",updated:"Actualización"};

function firstOfMonth(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-01`;}
function periodStart(value:string,period:"monthly"|"quarterly"|"annual"){const date=new Date(`${value}T12:00:00`);if(period==="annual")date.setMonth(0);if(period==="quarterly")date.setMonth(Math.floor(date.getMonth()/3)*3);date.setDate(1);return date.toISOString().slice(0,10);}
function allocationMonths(period:"monthly"|"quarterly"|"annual",start:string){const count=period==="annual"?12:period==="quarterly"?3:1;const first=new Date(`${periodStart(start,period)}T12:00:00`);return Array.from({length:count},(_,index)=>{const date=new Date(first);date.setMonth(first.getMonth()+index);return date.toISOString().slice(0,10);});}
function monthLabel(value:string){return new Intl.DateTimeFormat("es-MX",{month:"long",year:"numeric"}).format(new Date(`${value}T12:00:00`));}
function parseAmountInput(value:string){return Number(value.replace(/,/g,""))||0;}
function normalizeAmountInput(value:string){const cleaned=value.replace(/,/g,"").replace(/[^\d.]/g,"");if(!cleaned)return"";const hasDecimal=cleaned.includes(".");const[whole,...fractionParts]=cleaned.split(".");const normalizedWhole=(whole.replace(/^0+(?=\d)/,"")||"0");const fraction=fractionParts.join("").slice(0,6);return hasDecimal?`${normalizedWhole}.${fraction}`:normalizedWhole;}
function formatAmountInput(value:string){if(!value)return"";const hasDecimal=value.includes(".");const[whole="0",fraction=""]=value.split(".");const grouped=(whole||"0").replace(/\B(?=(\d{3})+(?!\d))/g,",");return hasDecimal?`${grouped}.${fraction}`:grouped;}
function evenAllocations(period:"monthly"|"quarterly"|"annual",start:string,total:string){const months=allocationMonths(period,start),amount=parseAmountInput(total),base=Math.floor(amount/months.length*100)/100;return months.map((month,index)=>({month,value:String(index===months.length-1?Math.round((amount-base*(months.length-1))*100)/100:base)}));}
function annualMonths(start:string){return allocationMonths("annual",periodStart(start,"annual"));}
function scaleAllocations(allocations:MonthlyAllocation[],total:number){const sourceTotal=allocations.reduce((sum,item)=>sum+parseAmountInput(item.value),0);if(sourceTotal<=0)return evenAllocations("annual",allocations[0]?.month??firstOfMonth(),String(total));let assigned=0;return allocations.map((item,index)=>{const next=index===allocations.length-1?Math.round((total-assigned)*1000000)/1000000:Math.round(total*parseAmountInput(item.value)/sourceTotal*1000000)/1000000;assigned+=next;return{month:item.month,value:String(next)};});}
function quarterAllocations(quarters:string[],start:string){const months=annualMonths(start);return months.map((month,index)=>{const quarter=Math.floor(index/3),quarterValue=parseAmountInput(quarters[quarter]??"");const base=Math.floor(quarterValue/3*100)/100;return{month,value:String(index%3===2?Math.round((quarterValue-base*2)*100)/100:base)};});}
function amount(value:number|null|undefined,unit:string){if(value==null)return"—";return unit==="unit"?value.toLocaleString("es-MX",{maximumFractionDigits:2}):new Intl.NumberFormat("es-MX",{style:"currency",currency:unit,maximumFractionDigits:0}).format(value);}
function percent(value:number|null|undefined){return value==null?"—":`${value.toLocaleString("es-MX",{maximumFractionDigits:1})}%`;}

function AmountInput({value,onValueChange,required=false,ariaLabel}:{value:string;onValueChange:(next:string)=>void;required?:boolean;ariaLabel:string}){return <Input className="bi-amount-input" type="text" inputMode="decimal" value={formatAmountInput(value)} onChange={event=>onValueChange(normalizeAmountInput(event.target.value))} required={required} aria-label={ariaLabel}/>;}

export function BiBudgetsModule({companyId}:{companyId:string}){
  const{appState}=useSatrapy();const permissions=appState?.membership.permissions??[];const has=(code:string)=>permissions.includes("*")||permissions.includes(code);
  const[status,setStatus]=useState<BudgetStatus|"all">("all");
  const[page,setPage]=useState(1);const[data,setData]=useState<PageResult|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);
  const[collapsedPlans,setCollapsedPlans]=useState<Set<string>>(()=>new Set());
  const[editor,setEditor]=useState<{row?:BudgetRow;replace?:BudgetRow}|null>(null);const[selected,setSelected]=useState<string|null>(null);
  const[detail,setDetail]=useState<Detail|null>(null);const[detailLoading,setDetailLoading]=useState(false);
  const[approve,setApprove]=useState<BudgetRow|null>(null);const[approvalReason,setApprovalReason]=useState("");const[actionLoading,setActionLoading]=useState(false);
  const[projection,setProjection]=useState<BudgetRow|null>(null);const[increase,setIncrease]=useState("10");const[projectionReason,setProjectionReason]=useState("");

  const load=useCallback(async(nextPage=page)=>{
    setLoading(true);setError(null);
    const{data:result,error:rpcError}=await getSupabaseClient().rpc("bi_list_budget_performance",{
      p_company_id:companyId,p_status:status==="all"?null:status,p_from:null,p_to:null,p_page:nextPage,p_page_size:25,
    });
    if(rpcError)setError(rpcError.message);else setData(result as PageResult);setLoading(false);
  },[companyId,page,status]);
  useEffect(()=>{let active=true;void Promise.resolve().then(()=>{if(active)return load();});return()=>{active=false;};},[load]);
  useEffect(()=>{if(!selected)return;let active=true;void Promise.resolve().then(async()=>{if(!active)return;setDetailLoading(true);const{data:result,error:rpcError}=await getSupabaseClient().rpc("bi_get_budget_detail",{p_company_id:companyId,p_version_id:selected});if(active){setDetailLoading(false);if(!rpcError)setDetail(result as Detail);}});return()=>{active=false;};},[companyId,selected]);
  async function approveVersion(event:FormEvent){event.preventDefault();if(!approve)return;setActionLoading(true);const rpc=approve.budget_kind==="independent"?"bi_approve_budget_plan":"bi_approve_budget_version";const{error:rpcError}=await getSupabaseClient().rpc(rpc,{p_company_id:companyId,p_version_id:approve.id,p_reason:approvalReason});setActionLoading(false);if(rpcError){setError(rpcError.message);return;}setApprove(null);setApprovalReason("");await load();}
  async function projectNextYear(event:FormEvent){event.preventDefault();if(!projection)return;setActionLoading(true);const{error:rpcError}=await getSupabaseClient().rpc("bi_project_budget_plan",{p_company_id:companyId,p_version_id:projection.id,p_increase_percent:parseAmountInput(increase),p_reason:projectionReason});setActionLoading(false);if(rpcError){setError(rpcError.message);return;}setProjection(null);setProjectionReason("");setIncrease("10");setStatus("draft");await load(1);}

  return <section className="content-frame module-page bi-budgets">
    <PageHeading eyebrow="Business Intelligence" title="Metas y presupuestos" description="Una sola meta por alcance y año, capturable por total, trimestre o mes. Las asignaciones comerciales pertenecen a esa misma meta y nunca se suman dos veces." action={<div className="bi-heading-actions">{has("create_bi_budget_drafts")&&<Button variant="primary" size="sm" onClick={()=>setEditor({})}><Plus aria-hidden="true" size={14}/> Nueva meta</Button>}<Button size="sm" onClick={()=>void load()}><RefreshCw aria-hidden="true" size={14}/> Actualizar</Button></div>}/>
    <div className="bi-budget-toolbar"><Select ariaLabel="Estado de la meta" value={status} onValueChange={value=>{setStatus(value as BudgetStatus|"all");setPage(1);}} options={[{value:"approved",label:"Aprobadas"},{value:"draft",label:"Borradores"},{value:"superseded",label:"Sustituidas"},{value:"all",label:"Todas"}]}/><span>{data?.pagination.total.toLocaleString("es-MX")??0} {data?.pagination.total===1?"meta":"metas"} dentro de tu alcance</span></div>
    <DataState loading={loading&&!data} error={error} hasData={data?.items.length??0} empty="Aún no hay metas en este estado y alcance." emptyAction={has("create_bi_budget_drafts")?<Button size="sm" onClick={()=>setEditor({})}>Crear primera meta</Button>:undefined}>
        <Table className="bi-budget-table"><thead><tr><th>Meta</th><th>Alcance</th><th>Periodo</th><th>Meta anual</th><th>Resultado</th><th>Cumplimiento</th><th>Proyección</th><th>Asignaciones</th><th>Estado</th><th/></tr></thead><tbody>{data?.items.flatMap(row=>{
          if(row.budget_kind==="distribution"&&row.parent_version_id&&data.items.some(parent=>parent.id===row.parent_version_id))return[];
          const children=row.budget_kind==="independent"?data.items.filter(item=>item.parent_version_id===row.id):[];
          const expanded=!collapsedPlans.has(row.id);
          const toggle=()=>setCollapsedPlans(current=>{const next=new Set(current);if(expanded)next.add(row.id);else next.delete(row.id);return next;});
          const parent=<tr className={children.length?"bi-budget-parent-row":""} key={row.id}>
            <td><div className="bi-budget-plan-title">{children.length>0&&<button type="button" className="bi-plan-disclosure" aria-label={`${expanded?"Contraer":"Mostrar"} las ${children.length} asignaciones de ${row.name}`} aria-expanded={expanded} aria-controls={children.map(child=>`budget-distribution-${child.id}`).join(" ")} onClick={toggle}><ChevronDown aria-hidden="true" size={15}/></button>}<button className="table-link" onClick={()=>setSelected(row.id)}><strong>{row.name}</strong><small>{METRIC_LABEL[row.metric_code]} · v{String((row as BudgetRow&{version?:number}).version??1)}{children.length>0?` · ${children.length} categorías`:""}</small></button></div></td>
            <td>{row.scope_label}<small>Independiente</small></td>
            <td>{row.period_start}<small>al {row.period_end}</small></td><td><strong>{amount(row.value,row.unit_code)}</strong></td>
            <td>{row.actual_available?amount(row.actual_value,row.unit_code):<span title={row.actual_reason??undefined}>No disponible</span>}</td>
            <td><strong>{percent(row.attainment_percent)}</strong><small>Pendiente {amount(row.remaining_value,row.unit_code)}</small></td><td>{amount(row.projected_value,row.unit_code)}</td>
            <td><><span>Asignado {amount(row.assigned_value,row.unit_code)}</span><small className={Number(row.distribution_excess)>0?"is-danger":""}>{Number(row.distribution_excess)>0?`Excedente ${amount(row.distribution_excess,row.unit_code)}`:`Pendiente ${amount(row.pending_distribution,row.unit_code)}`}</small></></td>
            <td><Badge tone={row.status==="approved"?"success":row.status==="draft"?"warning":"neutral"}>{STATUS_LABEL[row.status]}</Badge></td>
            <td><div className="table-actions">{row.status==="draft"&&has("create_bi_budget_drafts")&&(["company","location","responsible"] as ScopeType[]).includes(row.scope_type)&&<Button size="sm" variant="ghost" onClick={()=>setEditor({row})}>Editar</Button>}{row.status==="draft"&&has("approve_bi_budgets")&&<Button size="sm" variant="ghost" onClick={()=>setApprove(row)}>Aprobar plan</Button>}{row.status==="approved"&&row.period_type==="annual"&&has("create_bi_budget_drafts")&&(["company","location","responsible"] as ScopeType[]).includes(row.scope_type)&&<Button size="sm" variant="ghost" onClick={()=>setProjection(row)}><TrendingUp aria-hidden="true" size={14}/> Siguiente año</Button>}{row.status==="approved"&&has("create_bi_budget_drafts")&&(["company","location","responsible"] as ScopeType[]).includes(row.scope_type)&&<Button size="sm" variant="ghost" onClick={()=>setEditor({replace:row})}>Sustituir</Button>}<button type="button" className="table-link" aria-label={`Abrir ${row.name}`} onClick={()=>setSelected(row.id)}><ChevronRight aria-hidden="true" size={15}/></button></div></td>
          </tr>;
          const distributions=expanded?children.map(child=>{const prefix=`${row.name} · `;const label=child.name.startsWith(prefix)?child.name.slice(prefix.length):child.name;return <tr className="bi-budget-distribution-row" id={`budget-distribution-${child.id}`} key={child.id}>
            <td><div className="bi-budget-distribution-title"><span aria-hidden="true"/><button className="table-link" onClick={()=>setSelected(child.id)}><strong>{label}</strong><small>Categoría incluida en esta meta</small></button></div></td>
            <td><small>Categoría</small></td><td><small>Incluida arriba</small></td><td><strong>{amount(child.value,child.unit_code)}</strong></td>
            <td>{child.actual_available?amount(child.actual_value,child.unit_code):"—"}</td><td><strong>{percent(child.attainment_percent)}</strong><small>Pendiente {amount(child.remaining_value,child.unit_code)}</small></td><td>{amount(child.projected_value,child.unit_code)}</td><td>—</td><td><small>{STATUS_LABEL[child.status]}</small></td>
            <td><div className="table-actions"><button type="button" className="table-link" aria-label={`Abrir asignación ${label}`} onClick={()=>setSelected(child.id)}><ChevronRight aria-hidden="true" size={15}/></button></div></td>
          </tr>;}) : [];return[parent,...distributions];
        })}</tbody></Table>
    </DataState>
    {data&&<DataPagination page={page} total={data.pagination.total} pageSize={25} label="metas" onChange={next=>{setPage(next);void load(next);}}/>}
    {editor&&<BudgetEditor key={editor.row?.id??editor.replace?.id??"new"} companyId={companyId} state={editor} onClose={()=>setEditor(null)} onSaved={()=>{setEditor(null);setStatus("draft");void load(1);}}/>}
    <Modal open={Boolean(approve)} onOpenChange={open=>!open&&setApprove(null)} eyebrow="Aprobación inmutable" title={`Aprobar ${approve?.name??"presupuesto"}`} description="Una versión aprobada no se edita destructivamente; cualquier cambio posterior crea una sustitución.">
      <form className="bi-save-form" onSubmit={approveVersion}><label>Motivo de aprobación<Input value={approvalReason} onChange={event=>setApprovalReason(event.target.value)} minLength={5} required/></label><p>Se aprobarán la meta general y todas sus asignaciones en una sola operación.</p><Button type="submit" variant="primary" loading={actionLoading}><CheckCircle2 size={15}/> Aprobar plan</Button></form>
    </Modal>
    <Modal open={Boolean(projection)} onOpenChange={open=>!open&&setProjection(null)} eyebrow="Proyección anual" title="Crear meta del siguiente año" description="Se creará un borrador nuevo con la misma distribución mensual y comercial.">
      <form className="bi-save-form" onSubmit={projectNextYear}><label>Incremento porcentual<AmountInput value={increase} onValueChange={setIncrease} required ariaLabel="Incremento porcentual"/><small>El nuevo total será {amount((projection?.value??0)*(1+parseAmountInput(increase)/100),projection?.unit_code??"MXN")}.</small></label><label>Motivo de la proyección<Input value={projectionReason} onChange={event=>setProjectionReason(event.target.value)} minLength={5} required placeholder="Ej. Crecimiento aprobado para el siguiente año"/></label><Button type="submit" variant="primary" loading={actionLoading}><CopyPlus size={15}/> Crear borrador proyectado</Button></form>
    </Modal>
    <BudgetDetail detail={detail} loading={detailLoading} companyId={companyId} open={Boolean(selected)} onClose={()=>setSelected(null)}/>
  </section>;
}

function BudgetEditor({companyId,state,onClose,onSaved}:{companyId:string;state:{row?:BudgetRow;replace?:BudgetRow};onClose:()=>void;onSaved:()=>void}){
  const row=state.row,base=row??state.replace;
  const initialScope:BaseScope=base?.scope_type==="location"?"location":base?.scope_type==="responsible"?"responsible":"company";
  const[metric,setMetric]=useState(base?.metric_code??"net_sales");const[captureMode,setCaptureMode]=useState<CaptureMode>("annual");
  const[start,setStart]=useState(periodStart(base?.period_start??firstOfMonth(),"annual"));const[scope,setScope]=useState<BaseScope>(initialScope);
  const[name,setName]=useState(base?.name??"");const[description,setDescription]=useState(base?.description??"");const[value,setValue]=useState(String(base?.value??""));
  const[unit,setUnit]=useState(base?.unit_code??"MXN");const[reason,setReason]=useState("");
  const[location,setLocation]=useState<Option|null>(base?.location_id?{id:base.location_id,label:base.scope_label}:null);const[responsible,setResponsible]=useState<Option|null>(base?.collaborator_id?{id:base.collaborator_id,label:base.scope_label}:null);
  const[allocations,setAllocations]=useState<MonthlyAllocation[]>(()=>evenAllocations("annual",start,String(base?.value??"")));const[quarters,setQuarters]=useState<string[]>(["","","",""]);
  const[commercialType,setCommercialType]=useState<"none"|"category"|"product">("none");const[commercial,setCommercial]=useState<CommercialAllocation[]>([]);
  const[advancedOpen,setAdvancedOpen]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);

  useEffect(()=>{const versionId=row?.id??state.replace?.id;if(!versionId)return;let active=true;void getSupabaseClient().rpc("bi_get_budget_plan_editor",{p_company_id:companyId,p_version_id:versionId}).then(({data})=>{if(!active||!data)return;const editor=data as{monthly_allocations:Array<{month_start:string;value:number}>;commercial_allocations:Array<{id:string;scope_type:string;category_id:string|null;product_id:string|null;label:string;value:number}>};const months=editor.monthly_allocations.length===12?editor.monthly_allocations.map(item=>({month:item.month_start,value:String(item.value)})):evenAllocations("annual",start,String(base?.value??""));setAllocations(months);setQuarters([0,1,2,3].map(q=>String(months.slice(q*3,q*3+3).reduce((sum,item)=>sum+parseAmountInput(item.value),0))));if(editor.commercial_allocations.length){const productMode=editor.commercial_allocations.some(item=>Boolean(item.product_id));setCommercialType(productMode?"product":"category");setCommercial(editor.commercial_allocations.map(item=>({key:item.id,option:{id:(item.product_id??item.category_id)!,label:item.label,category_id:item.category_id??undefined},value:String(item.value)})));}});return()=>{active=false;};},[base?.value,companyId,row?.id,start,state.replace?.id]);

  const total=parseAmountInput(value),monthlyTotal=allocations.reduce((sum,item)=>sum+parseAmountInput(item.value),0),monthlyDifference=total-monthlyTotal,difference=monthlyDifference;
  const commercialTotal=commercial.reduce((sum,item)=>sum+parseAmountInput(item.value),0),commercialDifference=total-commercialTotal;
  const yearOptions=useMemo(()=>Array.from({length:16},(_,index)=>String(new Date().getFullYear()-4+index)).map(year=>({value:year,label:year})),[]);
  function changeYear(next:string){const normalized=`${next}-01-01`;setStart(normalized);setAllocations(current=>annualMonths(normalized).map((month,index)=>({month,value:current[index]?.value??"0"})));}
  function changeCaptureMode(next:CaptureMode){setCaptureMode(next);if(next==="quarterly"){const nextQuarters=[0,1,2,3].map(q=>String(allocations.slice(q*3,q*3+3).reduce((sum,item)=>sum+parseAmountInput(item.value),0)));setQuarters(nextQuarters);setValue(String(nextQuarters.reduce((sum,item)=>sum+parseAmountInput(item),0)));}if(next==="monthly")setValue(String(monthlyTotal));}
  function updateMonth(index:number,next:string){const updated=allocations.map((item,itemIndex)=>itemIndex===index?{...item,value:next}:item);setAllocations(updated);if(captureMode==="monthly")setValue(String(updated.reduce((sum,item)=>sum+parseAmountInput(item.value),0)));}
  function copyPrevious(index:number,increase=false){if(index===0)return;const previous=parseAmountInput(allocations[index-1]?.value??"");updateMonth(index,String(Math.round(previous*(increase?1.1:1)*100)/100));}
  function updateQuarter(index:number,next:string){const updated=quarters.map((item,itemIndex)=>itemIndex===index?next:item);setQuarters(updated);setAllocations(quarterAllocations(updated,start));setValue(String(updated.reduce((sum,item)=>sum+parseAmountInput(item),0)));}
  function updateTotal(next:string){setValue(next);if(captureMode==="annual")setAllocations(current=>scaleAllocations(current,parseAmountInput(next)));}
  function setAllocationType(next:"none"|"category"|"product"){setCommercialType(next);setCommercial(next==="none"?[]:[{key:crypto.randomUUID(),option:null,value:""}]);}
  function updateCommercial(key:string,patch:Partial<CommercialAllocation>){setCommercial(current=>current.map(item=>item.key===key?{...item,...patch}:item));}
  async function save(event:FormEvent){event.preventDefault();setError(null);if(monthlyDifference>0.005||monthlyDifference<-.005){setError("La distribución temporal debe sumar exactamente la meta anual.");return;}if(commercialTotal>total+.005){setError("Reduce las asignaciones comerciales: actualmente exceden la meta total.");return;}if(commercial.some(item=>!item.option)){setError(`Selecciona ${commercialType==="product"?"un producto":"una categoría"} en cada asignación.`);return;}const selectedIds=commercial.map(item=>item.option?.id).filter(Boolean);if(new Set(selectedIds).size!==selectedIds.length){setError(`Cada ${commercialType==="product"?"producto":"categoría"} sólo puede aparecer una vez en la meta.`);return;}setSaving(true);const commercialPayload=commercial.map(item=>{const childTotal=parseAmountInput(item.value);return{category_id:commercialType==="category"?item.option?.id:item.option?.category_id,product_id:commercialType==="product"?item.option?.id:null,value:childTotal,monthly_allocations:scaleAllocations(allocations,childTotal).map(month=>({month_start:month.month,value:parseAmountInput(month.value)}))};});const{error:rpcError}=await getSupabaseClient().rpc("bi_save_budget_plan_draft",{p_company_id:companyId,p_version_id:row?.id??null,p_name:name,p_description:description,p_metric_code:metric,p_period_start:start,p_scope_type:scope,p_location_id:scope==="location"?location?.id:null,p_collaborator_id:scope==="responsible"?responsible?.id:null,p_value:total,p_unit_code:metric==="units_sold"?"unit":unit,p_reason:reason,p_monthly_allocations:allocations.map(item=>({month_start:item.month,value:parseAmountInput(item.value)})),p_commercial_allocations:commercialPayload,p_replace_version_id:state.replace?.id??null});setSaving(false);if(rpcError){setError(rpcError.message);return;}onSaved();}

  return <Modal className="bi-budget-dialog" open onOpenChange={open=>!open&&onClose()} eyebrow={state.replace?"Nueva versión":"Plan comercial anual"} title={row?"Editar borrador":state.replace?`Sustituir ${state.replace.name}`:"Crear meta anual"} description="Define una sola meta y captúrala por total, trimestre o mes. Satrapy mantiene todos los periodos conciliados.">
    <form className="bi-budget-form" onSubmit={save} aria-describedby={error?"budget-plan-error":undefined}>
      <section className="bi-budget-step span-2"><span>1. Define la meta</span><p>La métrica y el alcance identifican una única meta durante el año.</p><div><label>Métrica<Select ariaLabel="Métrica" value={metric} onValueChange={next=>{setMetric(next as typeof metric);if(next==="units_sold")setUnit("unit");}} options={METRICS}/></label><label>Nombre de la meta<Input value={name} onChange={event=>setName(event.target.value)} placeholder="Ej. Venta de SUISSAL 2027" required maxLength={140}/></label></div></section>
      <section className="bi-budget-step span-2"><span>2. Captura el periodo y el total</span><p>El modo de captura no crea metas separadas. Trimestres y meses siempre pertenecen a esta misma meta anual.</p><div className="bi-period-capture"><label>Año<Select ariaLabel="Año de la meta" value={start.slice(0,4)} onValueChange={changeYear} options={yearOptions}/><small>La meta siempre cubre del 1 de enero al 31 de diciembre.</small></label><label>Capturar por<div className="bi-period-options" role="group" aria-label="Modo de captura">{CAPTURE_MODES.map(item=><button key={item.value} type="button" className={captureMode===item.value?"is-active":""} aria-pressed={captureMode===item.value} onClick={()=>changeCaptureMode(item.value as CaptureMode)}>{item.label}</button>)}</div></label></div></section>
      {captureMode==="annual"&&<><label><span className="bi-field-label">Meta anual</span><AmountInput value={value} onValueChange={updateTotal} required ariaLabel="Meta anual"/></label><label><span className="bi-field-label">{metric==="units_sold"?"Unidad":"Moneda"}</span><Input value={metric==="units_sold"?"unit":unit} onChange={event=>setUnit(event.target.value.toUpperCase())} maxLength={3} disabled={metric==="units_sold"} required/><small>{metric==="units_sold"?"Esta métrica siempre se registra en unidades.":"Se aplica a toda la meta. Cámbiala sólo si usarás otra moneda."}</small></label></>}
      {captureMode==="quarterly"&&<section className="bi-quarter-grid span-2">{quarters.map((quarter,index)=><label key={index}>Trimestre {index+1}<AmountInput value={quarter} onValueChange={next=>updateQuarter(index,next)} required ariaLabel={`Meta del trimestre ${index+1}`}/></label>)}<strong>Total anual calculado: {amount(total,metric==="units_sold"?"unit":unit)}</strong></section>}
      {captureMode==="monthly"&&<section className="bi-allocation-editor span-2"><header><div><strong>Metas mensuales</strong><small>Los 12 meses forman una sola meta anual.</small></div><strong>{amount(total,metric==="units_sold"?"unit":unit)} al año</strong></header><div className="bi-allocation-grid">{allocations.map((item,index)=><label key={item.month}><span>{monthLabel(item.month)}</span><AmountInput value={item.value} onValueChange={next=>updateMonth(index,next)} required ariaLabel={`Meta de ${monthLabel(item.month)}`}/>{index>0&&<div><button type="button" onClick={()=>copyPrevious(index)}>Copiar anterior</button><button type="button" onClick={()=>copyPrevious(index,true)}>+10%</button></div>}</label>)}</div></section>}
      {captureMode!=="monthly"&&<section className="bi-temporal-summary span-2"><button type="button" aria-expanded={advancedOpen} onClick={()=>setAdvancedOpen(open=>!open)}><span><strong>Distribución por mes</strong><small>{Math.abs(difference)<.005?"Los 12 meses cuadran con la meta anual.":difference>0?`Faltan ${amount(difference,metric==="units_sold"?"unit":unit)} por distribuir`:`Excedente de ${amount(Math.abs(difference),metric==="units_sold"?"unit":unit)}`}</small></span><ChevronDown size={16}/></button>{advancedOpen&&<div className="bi-temporal-details"><Button type="button" size="sm" variant="secondary" onClick={()=>setAllocations(evenAllocations("annual",start,value))}>Distribuir por igual</Button><div className="bi-allocation-grid">{allocations.map((item,index)=><label key={item.month}><span>{monthLabel(item.month)}</span><AmountInput value={item.value} onValueChange={next=>updateMonth(index,next)} ariaLabel={`Meta de ${monthLabel(item.month)}`}/>{index>0&&<div><button type="button" onClick={()=>copyPrevious(index)}>Copiar anterior</button><button type="button" onClick={()=>copyPrevious(index,true)}>+10%</button></div>}</label>)}</div></div>}</section>}
      <section className="bi-budget-step span-2"><span>3. Asigna la meta</span><p>Elige a quién aplica la meta. Si la desglosas, categorías y productos siguen formando parte del mismo total.</p><div className="bi-assignment-options" role="group" aria-label="Alcance principal de la meta">{BASE_SCOPES.map(item=><button key={item.value} type="button" className={scope===item.value?"is-active":""} aria-pressed={scope===item.value} onClick={()=>{setScope(item.value as BaseScope);setLocation(null);setResponsible(null);}}>{item.label}</button>)}</div></section>
      {scope==="location"&&<ScopePicker companyId={companyId} type="location" label="Sucursal responsable" value={location} onChange={setLocation}/>}
      {scope==="responsible"&&<ScopePicker companyId={companyId} type="responsible" label="Responsable de la meta" value={responsible} onChange={setResponsible}/>}
      <section className="bi-commercial-editor span-2"><header><div><strong>Distribución comercial</strong><small>Opcional. Cada categoría o producto forma parte de esta misma meta; lo que no asignes permanece en el total general.</small></div><div className="bi-segmented" role="group" aria-label="Nivel de distribución"><button type="button" className={commercialType==="none"?"is-active":""} aria-pressed={commercialType==="none"} onClick={()=>setAllocationType("none")}>Sin desglose</button><button type="button" className={commercialType==="category"?"is-active":""} aria-pressed={commercialType==="category"} onClick={()=>setAllocationType("category")}>Categorías</button><button type="button" className={commercialType==="product"?"is-active":""} aria-pressed={commercialType==="product"} onClick={()=>setAllocationType("product")}>Productos</button></div></header>{commercialType!=="none"&&<div className="bi-commercial-list">{commercial.map((item,index)=><div className="bi-commercial-row" key={item.key}><span>{index+1}</span><ScopePicker companyId={companyId} type={commercialType} label={commercialType==="product"?"Producto":"Categoría"} value={item.option} onChange={option=>updateCommercial(item.key,{option})}/><label>Meta asignada<AmountInput value={item.value} onValueChange={next=>updateCommercial(item.key,{value:next})} required ariaLabel={`Meta asignada a ${item.option?.label??`${commercialType} ${index+1}`}`}/></label><button className="bi-remove-allocation" type="button" aria-label={`Quitar asignación ${index+1}`} onClick={()=>setCommercial(current=>current.filter(currentItem=>currentItem.key!==item.key))}><Trash2 size={15}/></button></div>)}<Button type="button" size="sm" variant="secondary" onClick={()=>setCommercial(current=>[...current,{key:crypto.randomUUID(),option:null,value:""}])}><Plus size={14}/> Agregar {commercialType==="product"?"producto":"categoría"}</Button></div>}<footer className={commercialDifference>=-.005?"is-balanced":""} role="status"><span>{commercialDifference>=0?`${amount(commercialDifference,metric==="units_sold"?"unit":unit)} sin asignar`:`Excedente de ${amount(Math.abs(commercialDifference),metric==="units_sold"?"unit":unit)}`}</span><strong>{amount(commercialTotal,metric==="units_sold"?"unit":unit)} de {amount(total,metric==="units_sold"?"unit":unit)}</strong></footer></section>
      <label className="span-2 bi-required-field"><span className="bi-field-label">Motivo del plan <i aria-hidden="true">*</i></span><small>Explica brevemente por qué se crea o ajusta esta meta.</small><Input value={reason} onChange={event=>setReason(event.target.value)} minLength={5} required placeholder="Ej. Planeación comercial 2027"/></label><label className="span-2"><span className="bi-field-label">Descripción <small>Opcional</small></span><Input value={description} onChange={event=>setDescription(event.target.value)} placeholder="Ej. Prioridad comercial y criterio de seguimiento"/></label>
      {error&&<div id="budget-plan-error" className="form-error span-2" role="alert">{error}</div>}<div className="drawer-actions span-2"><Button type="button" onClick={onClose}>Cancelar</Button><Button type="submit" variant="primary" loading={saving}>Guardar borrador</Button></div>
    </form>
  </Modal>;
}

function ScopePicker({companyId,type,label,value,onChange}:{companyId:string;type:"location"|"responsible"|"category"|"product";label:string;value:Option|null;onChange:(value:Option|null)=>void}){
  const[query,setQuery]=useState("");const[options,setOptions]=useState<Option[]>([]);const[loading,setLoading]=useState(false);
  const normalizedQuery=query.trim();const needsQuery=type==="category"||type==="product";const canSearch=!value&&(!needsQuery||normalizedQuery.length>=2);
  useEffect(()=>{if(!canSearch)return;const timer=window.setTimeout(async()=>{setLoading(true);const{data}=await getSupabaseClient().rpc("bi_search_budget_scope_options",{p_company_id:companyId,p_scope:type,p_query:normalizedQuery||null,p_page:1,p_page_size:20});setOptions(((data as{items?:Option[]}|null)?.items??[]));setLoading(false);},180);return()=>window.clearTimeout(timer);},[canSearch,companyId,normalizedQuery,type]);
  return <label>{label}<div className="bi-budget-picker"><Input value={value?.label??query} onChange={event=>{onChange(null);setQuery(event.target.value);}} placeholder={needsQuery?`Escribe 2 letras para buscar ${label.toLowerCase()}`:`Buscar ${label.toLowerCase()}`} required/>{!value&&needsQuery&&normalizedQuery.length<2&&<small className="bi-picker-hint">Escribe al menos 2 letras para ver opciones.</small>}<div>{canSearch&&loading?<span><LoaderCircle className="spin" size={13}/> Buscando…</span>:canSearch&&!value&&options.map(option=><button type="button" key={option.id} onClick={()=>{onChange(option);setQuery("");}}><strong>{option.label}</strong>{option.secondary&&option.secondary!==option.label&&<small>{option.secondary}</small>}</button>)}</div></div></label>;
}

function BudgetDetail({detail,loading,companyId,open,onClose}:{detail:Detail|null;loading:boolean;companyId:string;open:boolean;onClose:()=>void}){
  const[drill,setDrill]=useState<Array<{id:string;completed_at:string;location_name:string;responsible_name:string;value:number}>|null>(null);
  async function loadDrill(){if(!detail)return;const{data}=await getSupabaseClient().rpc("bi_budget_drilldown",{p_company_id:companyId,p_version_id:detail.version.id,p_page:1,p_page_size:25});setDrill(((data as{items?:typeof drill}|null)?.items??[])as NonNullable<typeof drill>);}
  const max=useMemo(()=>Math.max(...(detail?.series.map(point=>Math.max(point.actual??0,point.budget_pace))??[1]),1),[detail]);
  return <Modal open={open} onOpenChange={value=>!value&&onClose()} eyebrow="Meta contra resultado" title={detail?.version.name??"Detalle"} description="El resultado se recalcula desde el catálogo BI y conserva acceso a las operaciones que lo explican.">
    {loading?<div className="bi-drill-state"><LoaderCircle className="spin" size={16}/> Calculando…</div>:detail&&<div className="bi-budget-detail">
      <div className="bi-budget-kpis"><article><span>Meta anual</span><strong>{amount(detail.version.value,detail.version.unit_code)}</strong></article><article><span>Resultado</span><strong>{detail.actual.available?amount(detail.actual.value,detail.version.unit_code):"—"}</strong></article><article><span>Periodo anterior</span><strong>{amount(detail.previous_period.value,detail.version.unit_code)}</strong></article></div>
      {!detail.actual.available&&<div className="bi-partial-state"><AlertCircle size={15}/><span>{detail.actual.reason}</span></div>}
      <div className="bi-budget-legend" aria-hidden="true"><span><i/>Resultado acumulado</span><span><b/>Ritmo de la meta</span></div>
      <div className="bi-budget-series" role="img" aria-label="Comparación diaria entre resultado acumulado y ritmo de la meta">{detail.series.map(point=><div aria-hidden="true" key={point.date} title={`${point.date}: ${amount(point.actual,detail.version.unit_code)}`}><i style={{height:`${((point.actual??0)/max)*100}%`}}/><b style={{height:`${(point.budget_pace/max)*100}%`}}/></div>)}</div>
      {detail.distributions.length>0&&<section className="bi-detail-distributions"><header><h3>Asignaciones comerciales</h3><small>Forman parte de esta misma meta; no se suman nuevamente al total.</small></header><div>{detail.distributions.map(item=><article key={item.id}><span><strong>{item.scope_label}</strong><small>{item.scope_type.includes("product")?"Producto":"Categoría"}</small></span><span><strong>{amount(item.value,detail.version.unit_code)}</strong><small>{item.actual_available?`${percent(item.attainment_percent)} de cumplimiento`:"Resultado no disponible"}</small></span></article>)}</div></section>}
      <section><header><h3>Historial inmutable</h3></header><ul className="history-list">{detail.history.map(event=><li key={event.id}><strong>{EVENT_LABEL[event.action]??event.action}</strong><span>{new Date(event.occurred_at).toLocaleString("es-MX")}</span><small>{event.reason}</small></li>)}</ul></section>
      <Button size="sm" onClick={()=>void loadDrill()} disabled={!detail.actual.available}>Ver operaciones que explican el resultado</Button>
      {drill&&<Table><thead><tr><th>Fecha</th><th>Ubicación</th><th>Responsable</th><th>Resultado</th></tr></thead><tbody>{drill.map(item=><tr key={item.id}><td>{new Date(item.completed_at).toLocaleString("es-MX")}</td><td>{item.location_name}</td><td>{item.responsible_name}</td><td>{amount(item.value,detail.version.unit_code)}</td></tr>)}</tbody></Table>}
    </div>}
  </Modal>;
}
