"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Mail, MapPin, Pencil, RefreshCw, ShieldCheck, UserPlus } from "lucide-react";
import { Badge, Button, Drawer, Field, Input, Select, useToast } from "@/app/components/ui/primitives";
import { DataPagination, DataState, DataToolbar, InteractiveTableRow, PageHeading } from "@/app/components/ui/data";
import { getSupabaseClient } from "@/app/lib/supabase";
import { OperationIdempotencyKeys } from "@/app/lib/operation-idempotency";
import { roleDisplayName } from "@/app/lib/role-labels";

type LocationOption={id:string;code:string;name:string;type:string};
type RoleOption={code:string;name:string;description:string};
type UserLocation={id:string;code:string;name:string};
type CompanyUser={record_type?:"user"|"invitation";user_id:string|null;invitation_id?:string|null;email:string;full_name:string;role_code:string;role_name:string;role_assignable:boolean;status:"active"|"invited"|"suspended";invited_at:string;last_sign_in_at:string|null;updated_at:string;locations:UserLocation[]};
type UserResult={items:CompanyUser[];total:number;page:number;page_size:number};
type OptionsResult={roles:RoleOption[];locations:LocationOption[]};
type UserForm={email:string;roleCode:string;locationIds:string[];status:"active"|"suspended";reason:string};

const PAGE_SIZE=25;
const emptyForm:UserForm={email:"",roleCode:"",locationIds:[],status:"active",reason:""};

export function CompanyUsersView({companyId}:{companyId:string}){
  const {toast}=useToast();const idempotency=useRef(new OperationIdempotencyKeys());
  const [rows,setRows]=useState<CompanyUser[]>([]);const [roles,setRoles]=useState<RoleOption[]>([]);const [locations,setLocations]=useState<LocationOption[]>([]);const [total,setTotal]=useState(0);
  const [page,setPage]=useState(1);const [search,setSearch]=useState("");const [debounced,setDebounced]=useState("");const [roleFilter,setRoleFilter]=useState("all");const [statusFilter,setStatusFilter]=useState("all");
  const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [editing,setEditing]=useState<CompanyUser|null|undefined>(undefined);const [form,setForm]=useState<UserForm>(emptyForm);
  useEffect(()=>{const timer=window.setTimeout(()=>{setDebounced(search.trim());setPage(1);},280);return()=>window.clearTimeout(timer);},[search]);
  const load=useCallback(async()=>{setLoading(true);setError(null);const supabase=getSupabaseClient();const [{data,error:listError},{data:options,error:optionsError}]=await Promise.all([
    supabase.rpc("list_company_users",{p_company_id:companyId,p_query:debounced||null,p_role_code:roleFilter==="all"?null:roleFilter,p_status:statusFilter==="all"?null:statusFilter,p_page:page,p_page_size:PAGE_SIZE}),
    supabase.rpc("get_company_user_access_options",{p_company_id:companyId}),
  ]);const result=data as UserResult|null;const available=options as OptionsResult|null;setRows(result?.items??[]);setTotal(result?.total??0);setRoles(available?.roles??[]);setLocations(available?.locations??[]);setError(listError||optionsError?"No se pudieron cargar los usuarios y accesos.":null);setLoading(false);},[companyId,debounced,page,roleFilter,statusFilter]);
  useEffect(()=>{void Promise.resolve().then(load);},[load]);
  function open(user?:CompanyUser){setEditing(user??null);setForm(user?{email:user.email,roleCode:user.role_assignable?user.role_code:"",locationIds:user.locations.map(item=>item.id),status:user.status==="suspended"?"suspended":"active",reason:""}:{...emptyForm});}
  function toggleLocation(id:string){setForm(current=>({...current,locationIds:current.locationIds.includes(id)?current.locationIds.filter(item=>item!==id):[...current.locationIds,id]}));}
  const scoped=form.roleCode==="sucursal"||form.roleCode==="ingeniero_campo";
  async function save(){
    const fingerprint=JSON.stringify({companyId,userId:editing?.user_id??null,invitationId:editing?.invitation_id??null,...form,updatedAt:editing?.updated_at??null});const requestId=idempotency.current.get("save-company-user",fingerprint);setBusy(true);
    try{
      let pendingRegistration=false;
      if(editing?.record_type==="invitation"){const {error:saveError}=await getSupabaseClient().rpc("save_company_user_invitation",{p_company_id:companyId,p_invitation_id:editing.invitation_id,p_email:form.email,p_role_code:form.roleCode,p_location_ids:scoped?form.locationIds:[],p_status:form.status,p_reason:form.reason,p_expected_updated_at:editing.updated_at,p_client_request_id:requestId});if(saveError)throw new Error(saveError.message);}
      else if(editing){const {error:saveError}=await getSupabaseClient().rpc("save_company_user_access",{p_company_id:companyId,p_user_id:editing.user_id,p_role_code:form.roleCode,p_location_ids:scoped?form.locationIds:[],p_status:form.status,p_reason:form.reason,p_expected_updated_at:editing.updated_at,p_client_request_id:requestId});if(saveError)throw new Error(saveError.message);}
      else{const session=(await getSupabaseClient().auth.getSession()).data.session;if(!session)throw new Error("Sesión no válida.");const response=await fetch("/api/admin/users",{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({companyId,email:form.email,roleCode:form.roleCode,locationIds:scoped?form.locationIds:[],reason:form.reason,clientRequestId:requestId})});const result=await response.json();if(!response.ok)throw new Error(result.message??"No se pudo preparar el acceso.");pendingRegistration=Boolean(result.pendingRegistration);}
      idempotency.current.clear("save-company-user");toast({title:editing?"Acceso actualizado":pendingRegistration?"Correo autorizado":"Usuario incorporado",description:editing?"El cambio quedó auditado.":pendingRegistration?"La persona ya puede crear su cuenta con ese correo.":"La cuenta existente quedó ligada a la empresa.",tone:"success"});setEditing(undefined);await load();
    }catch(saveError){toast({title:"No se pudo guardar",description:saveError instanceof Error?saveError.message:"Intenta nuevamente.",tone:"error"});}finally{setBusy(false);}
  }
  const active=rows.filter(row=>row.status==="active").length;const invited=rows.filter(row=>row.status==="invited").length;const suspended=rows.filter(row=>row.status==="suspended").length;
  const canSave=Boolean(form.roleCode&&form.reason.trim()&&(!scoped||form.locationIds.length)&&((editing&&form.status)||(!editing&&form.email.trim())));
  return <div className="content-frame company-users"><PageHeading eyebrow="Empresa" title="Usuarios y accesos" description="Invita personas, asigna un rol entendible y limita su operación a las sucursales necesarias." action={<Button variant="primary" onClick={()=>open()}><UserPlus size={15}/>Invitar usuario</Button>}/>
    <section className="user-access-summary"><article><span>Resultados</span><strong>{total.toLocaleString("es-MX")}</strong><small>según los filtros</small></article><article><span>Activos en página</span><strong>{active}</strong><small>con acceso vigente</small></article><article><span>Invitados</span><strong>{invited}</strong><small>sin primer acceso</small></article><article><span>Suspendidos</span><strong>{suspended}</strong><small>historial conservado</small></article><div><ShieldCheck size={20}/><p>Alta individual para equipos pequeños. Los cambios de rol y suspensión se validan en servidor y quedan auditados.</p></div></section>
    <DataToolbar search={search} onSearchChange={setSearch} placeholder="Buscar nombre o correo" filters={<><Select value={roleFilter} onValueChange={value=>{setRoleFilter(value);setPage(1);}} ariaLabel="Filtrar por rol" options={[{value:"all",label:"Todos los roles"},...roles.map(role=>({value:role.code,label:roleDisplayName(role.code,role.name)}))]}/><Select value={statusFilter} onValueChange={value=>{setStatusFilter(value);setPage(1);}} ariaLabel="Filtrar por estado" options={[{value:"all",label:"Todos los estados"},{value:"active",label:"Activos"},{value:"invited",label:"Invitados"},{value:"suspended",label:"Suspendidos"}]}/></>} activeFilters={(search.trim()?1:0)+(roleFilter!=="all"?1:0)+(statusFilter!=="all"?1:0)} onClear={()=>{setSearch("");setDebounced("");setRoleFilter("all");setStatusFilter("all");setPage(1);}} results={total}/>
    <DataState loading={loading&&rows.length===0} error={error} errorAction={<Button size="sm" onClick={()=>void load()}><RefreshCw size={14}/>Reintentar</Button>} hasData={rows.length} empty="No hay usuarios para estos filtros."><div className="table-wrap surface-table"><table><thead><tr><th>Persona</th><th>Rol</th><th>Alcance</th><th>Estado</th><th>Último acceso</th><th className="user-access-actions-heading">Acciones</th></tr></thead><tbody>{rows.map(row=>{const protectedAccess=row.record_type!=="invitation"&&row.role_code==="super_admin";const rowKey=row.user_id??row.invitation_id??row.email;return <InteractiveTableRow key={rowKey} label={protectedAccess?`Acceso global protegido de ${row.full_name}`:`Administrar acceso de ${row.email}`} onActivate={()=>open(row)} disabled={protectedAccess} className={protectedAccess?"user-access-row--protected":undefined}><td><div className="user-identity"><span>{row.record_type==="invitation"?"?":row.full_name.slice(0,1).toUpperCase()}</span><div><strong>{row.full_name}</strong><small>{row.email}</small></div></div></td><td><strong>{roleDisplayName(row.role_code,row.role_name)}</strong>{protectedAccess?<small className="user-role-note">Acceso global protegido</small>:!row.role_assignable&&<small className="user-role-note user-role-note--warning">Rol anterior; requiere reasignación</small>}</td><td>{row.locations.length?<span className="user-scope"><MapPin size={13}/>{row.locations.length===1?row.locations[0].name:`${row.locations.length} sucursales`}</span>:<span className="settings-muted">Toda la empresa</span>}</td><td><UserStatus status={row.status}/></td><td>{row.last_sign_in_at?new Date(row.last_sign_in_at).toLocaleString("es-MX"):<span className="settings-muted">Sin ingresar</span>}</td><td className="user-access-actions">{protectedAccess?<span className="settings-muted">Protegido</span>:<Button size="sm" variant="secondary" onClick={()=>open(row)}><Pencil size={13}/>Editar acceso</Button>}</td></InteractiveTableRow>})}</tbody></table></div></DataState>
    <DataPagination page={page} total={total} pageSize={PAGE_SIZE} onChange={setPage}/>
    <Drawer open={editing!==undefined} onOpenChange={openValue=>{if(!openValue&&!busy)setEditing(undefined);}} title={editing?`Acceso de ${editing.email}`:"Invitar usuario"} className="company-user-drawer"><div className="company-user-form"><p className="company-user-note">{editing?"Los cambios aplican al siguiente acceso y conservan toda la actividad anterior.":"No se enviará correo. La persona podrá crear su cuenta únicamente con el correo que autorices aquí."}</p>{editing?<div className="company-user-current"><span>{editing.record_type==="invitation"?"?":editing.full_name.slice(0,1).toUpperCase()}</span><div><strong>{editing.full_name}</strong><small><Mail size={13}/>{editing.email}</small></div></div>:<Field label="Correo autorizado"><Input type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})} placeholder="persona@empresa.com"/> </Field>}
      <Field label="Rol" hint={roles.find(role=>role.code===form.roleCode)?.description}><Select ariaLabel="Rol del usuario" value={form.roleCode} onValueChange={value=>setForm({...form,roleCode:value,locationIds:[]})} placeholder="Selecciona un rol" options={roles.map(role=>({value:role.code,label:role.name}))}/></Field>
      {scoped&&<Field label="Sucursales autorizadas" hint="Selecciona todas las ubicaciones donde podrá operar."><div className="user-location-picker">{locations.map(location=><label key={location.id}><input type="checkbox" checked={form.locationIds.includes(location.id)} onChange={()=>toggleLocation(location.id)}/><span><strong>{location.name}</strong><small>{location.code}</small></span></label>)}</div></Field>}
      {editing&&<Field label="Estado"><Select ariaLabel="Estado del acceso" value={form.status} onValueChange={value=>setForm({...form,status:value as UserForm["status"]})} options={editing.record_type==="invitation"?[{value:"active",label:"Pendiente"},{value:"suspended",label:"Cancelado"}]:[{value:"active",label:"Activo"},{value:"suspended",label:"Suspendido"}]}/></Field>}
      <Field label="Motivo" hint="Se conserva en auditoría"><Input value={form.reason} onChange={event=>setForm({...form,reason:event.target.value})} placeholder={editing?"Ej. Cambio autorizado por Dirección":"Ej. Alta para operación de sucursal"}/></Field>
      <div className="company-user-actions"><Button disabled={busy} onClick={()=>setEditing(undefined)}>Cancelar</Button><Button variant="primary" loading={busy} disabled={!canSave} onClick={()=>void save()}>{editing?"Guardar acceso":"Autorizar correo"}</Button></div></div></Drawer>
  </div>;
}

function UserStatus({status}:{status:CompanyUser["status"]}){if(status==="active")return <Badge tone="success">Activo</Badge>;if(status==="invited")return <Badge tone="info">Invitado</Badge>;return <Badge tone="neutral">Suspendido</Badge>;}
