"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, Layers3, Mail, MapPin, Pencil, Plus, RefreshCw, ShieldCheck, UserPlus, Users } from "lucide-react";
import { Badge, Button, Drawer, Field, Input, Select, Tabs, useToast } from "@/app/components/ui/primitives";
import { DataPagination, DataState, DataToolbar, InteractiveTableRow, PageHeading } from "@/app/components/ui/data";
import { getSupabaseClient } from "@/app/lib/supabase";
import { OperationIdempotencyKeys } from "@/app/lib/operation-idempotency";
import { roleDisplayName } from "@/app/lib/role-labels";

type LocationOption={id:string;code:string;name:string;type:string};
type RoleOption={id:string;code:string;name:string;description:string;category:string;scope_kind:"company"|"locations";is_system:boolean;permission_count:number};
type UserRole=Pick<RoleOption,"code"|"name"|"description"|"category"|"scope_kind">&{is_assignable:boolean};
type UserLocation={id:string;code:string;name:string};
type CompanyUser={record_type?:"user"|"invitation";user_id:string|null;invitation_id?:string|null;email:string;full_name:string;role_code:string;role_name:string;role_assignable:boolean;role_codes:string[];roles:UserRole[];status:"active"|"invited"|"suspended";invited_at:string;last_sign_in_at:string|null;updated_at:string;locations:UserLocation[];collaborator?:{id:string;code:string;name:string}|null};
type UserResult={items:CompanyUser[];total:number;page:number;page_size:number};
type OptionsResult={roles:RoleOption[];locations:LocationOption[]};
type PermissionOption={code:string;description:string;category:string};
type AccessProfile=RoleOption&{updated_at:string;assignee_count:number;permissions:string[]};
type ProfilesResult={profiles:AccessProfile[];permissions:PermissionOption[]};
type UserForm={email:string;roleCodes:string[];locationIds:string[];status:"active"|"suspended";reason:string};
type ProfileForm={id:string|null;name:string;description:string;scopeKind:"company"|"locations";permissionCodes:string[];reason:string;updatedAt:string|null};

const PAGE_SIZE=25;
const emptyUserForm:UserForm={email:"",roleCodes:[],locationIds:[],status:"active",reason:""};
const emptyProfileForm:ProfileForm={id:null,name:"",description:"",scopeKind:"company",permissionCodes:[],reason:"",updatedAt:null};
const categoryLabels:Record<string,string>={administration:"Administración",sales:"Ventas",inventory:"Inventario",field_service:"Servicio en campo",payroll:"Nómina",procurement:"Compras",accounting:"Contabilidad",custom:"Personalizados",general:"General"};

export function CompanyUsersView({companyId}:{companyId:string}){
  const {toast}=useToast();const idempotency=useRef(new OperationIdempotencyKeys());
  const [section,setSection]=useState("users");const [rows,setRows]=useState<CompanyUser[]>([]);const [roles,setRoles]=useState<RoleOption[]>([]);const [locations,setLocations]=useState<LocationOption[]>([]);const [profiles,setProfiles]=useState<AccessProfile[]>([]);const [permissions,setPermissions]=useState<PermissionOption[]>([]);const [total,setTotal]=useState(0);
  const [page,setPage]=useState(1);const [search,setSearch]=useState("");const [debounced,setDebounced]=useState("");const [roleFilter,setRoleFilter]=useState("all");const [statusFilter,setStatusFilter]=useState("all");
  const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [editing,setEditing]=useState<CompanyUser|null|undefined>(undefined);const [form,setForm]=useState<UserForm>(emptyUserForm);
  const [profileEditing,setProfileEditing]=useState(false);const [profileForm,setProfileForm]=useState<ProfileForm>(emptyProfileForm);const [permissionSearch,setPermissionSearch]=useState("");

  useEffect(()=>{const timer=window.setTimeout(()=>{setDebounced(search.trim());setPage(1);},280);return()=>window.clearTimeout(timer);},[search]);
  const load=useCallback(async()=>{setLoading(true);setError(null);const supabase=getSupabaseClient();const [{data,error:listError},{data:options,error:optionsError},{data:catalog,error:catalogError}]=await Promise.all([
    supabase.rpc("list_company_users",{p_company_id:companyId,p_query:debounced||null,p_role_code:roleFilter==="all"?null:roleFilter,p_status:statusFilter==="all"?null:statusFilter,p_page:page,p_page_size:PAGE_SIZE}),
    supabase.rpc("get_company_user_access_options",{p_company_id:companyId}),supabase.rpc("list_access_profiles",{p_company_id:companyId}),
  ]);const result=data as UserResult|null;const available=options as OptionsResult|null;const profileCatalog=catalog as ProfilesResult|null;setRows(result?.items??[]);setTotal(result?.total??0);setRoles(available?.roles??[]);setLocations(available?.locations??[]);setProfiles(profileCatalog?.profiles??[]);setPermissions((profileCatalog?.permissions??[]).filter(permission=>permission.code!=="manage_company_users"));setError(listError||optionsError||catalogError?"No se pudieron cargar los usuarios y perfiles de acceso.":null);setLoading(false);},[companyId,debounced,page,roleFilter,statusFilter]);
  useEffect(()=>{void Promise.resolve().then(load);},[load]);

  function open(user?:CompanyUser){setEditing(user??null);setForm(user?{email:user.email,roleCodes:(user.roles??[]).filter(role=>role.is_assignable).map(role=>role.code),locationIds:user.locations.map(item=>item.id),status:user.status==="suspended"?"suspended":"active",reason:""}:{...emptyUserForm});}
  function toggleLocation(id:string){setForm(current=>({...current,locationIds:toggle(current.locationIds,id)}));}
  function toggleRole(code:string){setForm(current=>({...current,roleCodes:code==="direccion_admin"?(current.roleCodes.includes(code)?[]:[code]):toggle(current.roleCodes,code)}));}
  const selectedRoles=roles.filter(role=>form.roleCodes.includes(role.code));
  const adminSelected=form.roleCodes.includes("direccion_admin");
  const scoped=selectedRoles.some(role=>role.scope_kind==="locations");
  const warnings=useMemo(()=>profileWarnings(form.roleCodes),[form.roleCodes]);
  const newFieldEngineer=form.roleCodes.includes("ingeniero_campo")&&!editing;
  const canSave=Boolean(form.roleCodes.length&&form.reason.trim()&&(!scoped||form.locationIds.length)&&((editing&&form.status)||(!editing&&form.email.trim()))&&!newFieldEngineer);

  async function saveUser(){
    const fingerprint=JSON.stringify({companyId,userId:editing?.user_id??null,invitationId:editing?.invitation_id??null,...form,updatedAt:editing?.updated_at??null});const requestId=idempotency.current.get("save-company-user",fingerprint);setBusy(true);
    try{let pendingRegistration=false;
      if(editing?.record_type==="invitation"){const {error:saveError}=await getSupabaseClient().rpc("save_company_user_invitation_profiles",{p_company_id:companyId,p_invitation_id:editing.invitation_id,p_email:form.email,p_role_codes:form.roleCodes,p_location_ids:scoped?form.locationIds:[],p_status:form.status,p_reason:form.reason,p_expected_updated_at:editing.updated_at,p_client_request_id:requestId});if(saveError)throw new Error(saveError.message);}
      else if(editing){const {error:saveError}=await getSupabaseClient().rpc("save_company_user_access_profiles",{p_company_id:companyId,p_user_id:editing.user_id,p_role_codes:form.roleCodes,p_location_ids:scoped?form.locationIds:[],p_status:form.status,p_reason:form.reason,p_expected_updated_at:editing.updated_at,p_client_request_id:requestId});if(saveError)throw new Error(saveError.message);}
      else{const session=(await getSupabaseClient().auth.getSession()).data.session;if(!session)throw new Error("Sesión no válida.");const response=await fetch("/api/admin/users",{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({companyId,email:form.email,roleCodes:form.roleCodes,locationIds:scoped?form.locationIds:[],reason:form.reason,clientRequestId:requestId})});const result=await response.json();if(!response.ok)throw new Error(result.message??"No se pudo preparar el acceso.");pendingRegistration=Boolean(result.pendingRegistration);}
      idempotency.current.clear("save-company-user");toast({title:editing?"Acceso actualizado":pendingRegistration?"Correo autorizado":"Usuario incorporado",description:warnings.length?"El cambio quedó auditado con una advertencia de separación de funciones.":"El cambio quedó auditado.",tone:"success"});setEditing(undefined);await load();
    }catch(saveError){toast({title:"No se pudo guardar",description:saveError instanceof Error?saveError.message:"Intenta nuevamente.",tone:"error"});}finally{setBusy(false);}
  }

  function openProfile(profile?:AccessProfile){if(profile?.is_system)return;setProfileForm(profile?{id:profile.id,name:profile.name,description:profile.description,scopeKind:profile.scope_kind,permissionCodes:profile.permissions,reason:"",updatedAt:profile.updated_at}:{...emptyProfileForm});setPermissionSearch("");setProfileEditing(true);}
  async function saveProfile(){const fingerprint=JSON.stringify({...profileForm,companyId});const requestId=idempotency.current.get("save-access-profile",fingerprint);setBusy(true);try{const {error:saveError}=await getSupabaseClient().rpc("save_access_profile",{p_company_id:companyId,p_profile_id:profileForm.id,p_name:profileForm.name,p_description:profileForm.description,p_permission_codes:profileForm.permissionCodes,p_scope_kind:profileForm.scopeKind,p_reason:profileForm.reason,p_expected_updated_at:profileForm.updatedAt,p_client_request_id:requestId});if(saveError)throw new Error(saveError.message);idempotency.current.clear("save-access-profile");toast({title:profileForm.id?"Perfil actualizado":"Perfil creado",description:"Los usuarios asignados recibirán el acceso efectivo del perfil.",tone:"success"});setProfileEditing(false);await load();}catch(saveError){toast({title:"No se pudo guardar el perfil",description:saveError instanceof Error?saveError.message:"Intenta nuevamente.",tone:"error"});}finally{setBusy(false);}}
  const canSaveProfile=Boolean(profileForm.name.trim()&&profileForm.description.trim()&&profileForm.permissionCodes.length&&profileForm.reason.trim());
  const visiblePermissions=permissions.filter(permission=>!permissionSearch.trim()||`${permission.code} ${permission.description}`.toLowerCase().includes(permissionSearch.trim().toLowerCase()));
  const active=rows.filter(row=>row.status==="active").length;const invited=rows.filter(row=>row.status==="invited").length;const suspended=rows.filter(row=>row.status==="suspended").length;

  return <div className="content-frame company-users"><PageHeading eyebrow="Empresa" title="Usuarios y accesos" description="Asigna perfiles combinables y conserva permisos, alcance y cambios en auditoría." action={section==="users"?<Button variant="primary" onClick={()=>open()}><UserPlus size={15}/>Autorizar correo</Button>:<Button variant="primary" onClick={()=>openProfile()}><Plus size={15}/>Crear perfil</Button>}/>
    <Tabs value={section} onValueChange={setSection} items={[{value:"users",label:"Usuarios"},{value:"profiles",label:"Perfiles de acceso"}]}/>
    {section==="users"?<>
      <section className="user-access-summary"><article><span>Resultados</span><strong>{total.toLocaleString("es-MX")}</strong><small>según los filtros</small></article><article><span>Activos en página</span><strong>{active}</strong><small>con acceso vigente</small></article><article><span>Invitados</span><strong>{invited}</strong><small>sin primer acceso</small></article><article><span>Suspendidos</span><strong>{suspended}</strong><small>historial conservado</small></article><div><ShieldCheck size={20}/><p>Combina solo los perfiles necesarios. La suma de permisos se calcula en servidor y cada cambio conserva motivo y autor.</p></div></section>
      <DataToolbar search={search} onSearchChange={setSearch} placeholder="Buscar nombre o correo" filters={<><Select value={roleFilter} onValueChange={value=>{setRoleFilter(value);setPage(1);}} ariaLabel="Filtrar por perfil" options={[{value:"all",label:"Todos los perfiles"},...roles.map(role=>({value:role.code,label:roleDisplayName(role.code,role.name)}))]}/><Select value={statusFilter} onValueChange={value=>{setStatusFilter(value);setPage(1);}} ariaLabel="Filtrar por estado" options={[{value:"all",label:"Todos los estados"},{value:"active",label:"Activos"},{value:"invited",label:"Invitados"},{value:"suspended",label:"Suspendidos"}]}/></>} activeFilters={(search.trim()?1:0)+(roleFilter!=="all"?1:0)+(statusFilter!=="all"?1:0)} onClear={()=>{setSearch("");setDebounced("");setRoleFilter("all");setStatusFilter("all");setPage(1);}} results={total}/>
      <DataState loading={loading&&rows.length===0} error={error} errorAction={<Button size="sm" onClick={()=>void load()}><RefreshCw size={14}/>Reintentar</Button>} hasData={rows.length} empty="No hay usuarios para estos filtros."><div className="table-wrap surface-table"><table><thead><tr><th>Cuenta</th><th>Perfiles de acceso</th><th>Colaborador</th><th>Alcance</th><th>Estado</th><th>Último acceso</th><th className="user-access-actions-heading">Acciones</th></tr></thead><tbody>{rows.map(row=>{const protectedAccess=row.record_type!=="invitation"&&(row.role_codes??[]).includes("super_admin");const rowKey=row.user_id??row.invitation_id??row.email;return <InteractiveTableRow key={rowKey} label={protectedAccess?`Acceso global protegido de ${row.full_name}`:`Administrar acceso de ${row.email}`} onActivate={()=>open(row)} disabled={protectedAccess} className={protectedAccess?"user-access-row--protected":undefined}><td><div className="user-identity"><span>{row.record_type==="invitation"?"?":row.full_name.slice(0,1).toUpperCase()}</span><div><strong>{row.full_name}</strong><small>{row.email}</small></div></div></td><td><div className="user-profile-chips">{(row.roles??[]).map(role=><Badge tone="neutral" key={role.code}>{roleDisplayName(role.code,role.name)}</Badge>)}</div>{protectedAccess&&<small className="user-role-note">Acceso global protegido</small>}</td><td>{row.collaborator?<span className="user-scope">{row.collaborator.name}<small>{row.collaborator.code}</small></span>:<span className="settings-muted">Sin vínculo</span>}</td><td>{row.locations.length?<span className="user-scope"><MapPin size={13}/>{row.locations.length===1?row.locations[0].name:`${row.locations.length} sucursales`}</span>:<span className="settings-muted">Toda la empresa</span>}</td><td><UserStatus status={row.status}/></td><td>{row.last_sign_in_at?new Date(row.last_sign_in_at).toLocaleString("es-MX"):<span className="settings-muted">Sin ingresar</span>}</td><td className="user-access-actions">{protectedAccess?<span className="settings-muted">Protegido</span>:<Button size="sm" variant="secondary" onClick={()=>open(row)}><Pencil size={13}/>Editar acceso</Button>}</td></InteractiveTableRow>})}</tbody></table></div></DataState><DataPagination page={page} total={total} pageSize={PAGE_SIZE} onChange={setPage}/>
    </>:<ProfileCatalog profiles={profiles} loading={loading} error={error} onRetry={load} onEdit={openProfile}/>}

    <Drawer open={editing!==undefined} onOpenChange={openValue=>{if(!openValue&&!busy)setEditing(undefined);}} title={editing?`Acceso de ${editing.email}`:"Autorizar correo"} className="company-user-drawer"><div className="company-user-form"><p className="company-user-note">Selecciona uno o varios perfiles. El acceso efectivo será la suma de sus permisos; las sucursales se comparten entre los perfiles con alcance local.</p>{editing?<div className="company-user-current"><span>{editing.record_type==="invitation"?"?":editing.full_name.slice(0,1).toUpperCase()}</span><div><strong>{editing.full_name}</strong><small><Mail size={13}/>{editing.email}</small></div></div>:<><p className="company-user-note">No se enviará correo ni se crearán credenciales; la persona completará su registro por separado.</p><Field label="Correo autorizado"><Input type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})} placeholder="persona@empresa.com"/></Field></>}
      <Field label="Perfiles de acceso" hint={adminSelected?"Acceso total mediante Administrador":form.roleCodes.length?`${form.roleCodes.length} seleccionado${form.roleCodes.length===1?"":"s"}`:"Selecciona al menos uno"}><div className="access-profile-picker">{groupRoles(roles).map(group=><section key={group.category}><h3>{categoryLabels[group.category]??group.category}</h3>{group.roles.map(role=>{const includedByAdmin=adminSelected&&role.code!=="direccion_admin";return <label className={includedByAdmin?"is-included":undefined} key={role.code}><input type="checkbox" aria-label={includedByAdmin?`Perfil ${roleDisplayName(role.code,role.name)} incluido en Administrador`:`Asignar perfil ${roleDisplayName(role.code,role.name)}`} checked={includedByAdmin||form.roleCodes.includes(role.code)} disabled={includedByAdmin} onChange={()=>toggleRole(role.code)}/><span><strong>{roleDisplayName(role.code,role.name)}</strong><small>{roleDescription(role)}</small></span><b>{includedByAdmin?"Incluido":`${role.permission_count} permisos`}</b></label>;})}</section>)}</div></Field>
      {adminSelected&&<p className="company-user-note" role="status"><strong>Administrador incluye todos los permisos.</strong> Los demás perfiles ya están cubiertos y no se guardan por separado.</p>}
      {newFieldEngineer&&<p className="company-user-note">El perfil Ingeniero de campo se asigna desde el expediente en <strong>Colaboradores</strong> para ligar cuenta, persona y puesto.</p>}
      {warnings.map(warning=><p className="access-warning" role="status" key={warning}><AlertTriangle size={15}/><span><strong>Revisa esta combinación</strong>{warning}</span></p>)}
      {scoped&&<Field label="Sucursales autorizadas" hint="Aplican a todos los perfiles con alcance local."><div className="user-location-picker">{locations.map(location=><label key={location.id}><input type="checkbox" aria-label={`Autorizar sucursal ${location.name}`} checked={form.locationIds.includes(location.id)} onChange={()=>toggleLocation(location.id)}/><span><strong>{location.name}</strong><small>{location.code}</small></span></label>)}</div></Field>}
      {editing&&<Field label="Estado"><Select ariaLabel="Estado del acceso" value={form.status} onValueChange={value=>setForm({...form,status:value as UserForm["status"]})} options={editing.record_type==="invitation"?[{value:"active",label:"Pendiente"},{value:"suspended",label:"Cancelado"}]:[{value:"active",label:"Activo"},{value:"suspended",label:"Suspendido"}]}/></Field>}
      <Field label="Motivo" hint="Se conserva en auditoría"><Input value={form.reason} onChange={event=>setForm({...form,reason:event.target.value})} placeholder={editing?"Ej. Separación de funciones autorizada":"Ej. Alta para operación de nómina"}/></Field>
      <div className="company-user-actions"><Button disabled={busy} onClick={()=>setEditing(undefined)}>Cancelar</Button><Button variant="primary" loading={busy} disabled={!canSave} onClick={()=>void saveUser()}>{editing?"Guardar acceso":"Autorizar correo"}</Button></div></div></Drawer>

    <Drawer open={profileEditing} onOpenChange={openValue=>{if(!openValue&&!busy)setProfileEditing(false);}} title={profileForm.id?"Editar perfil personalizado":"Crear perfil personalizado"} className="company-user-drawer"><div className="company-user-form"><p className="company-user-note">Úsalo solo si los perfiles recomendados no cubren la responsabilidad real. Los perfiles del sistema no se modifican.</p><Field label="Nombre"><Input value={profileForm.name} onChange={event=>setProfileForm({...profileForm,name:event.target.value})} placeholder="Ej. Auxiliar de tesorería"/></Field><Field label="Descripción"><Input value={profileForm.description} onChange={event=>setProfileForm({...profileForm,description:event.target.value})} placeholder="Qué puede hacer y qué queda fuera"/></Field><Field label="Alcance"><Select ariaLabel="Alcance del perfil" value={profileForm.scopeKind} onValueChange={value=>setProfileForm({...profileForm,scopeKind:value as ProfileForm["scopeKind"]})} options={[{value:"company",label:"Toda la empresa"},{value:"locations",label:"Sucursales asignadas"}]}/></Field>
      <Field label="Permisos" hint={`${profileForm.permissionCodes.length} seleccionados`}><Input value={permissionSearch} onChange={event=>setPermissionSearch(event.target.value)} placeholder="Buscar permiso" aria-label="Buscar permisos"/><div className="permission-picker">{groupPermissions(visiblePermissions).map(group=><section key={group.category}><h3>{categoryLabels[group.category]??group.category}</h3>{group.permissions.map(permission=><label key={permission.code}><input type="checkbox" aria-label={`Incluir permiso ${permission.description}`} checked={profileForm.permissionCodes.includes(permission.code)} onChange={()=>setProfileForm(current=>({...current,permissionCodes:toggle(current.permissionCodes,permission.code)}))}/><span><strong>{permission.description}</strong><small>{permission.code}</small></span></label>)}</section>)}</div></Field>
      <Field label="Motivo" hint="Se conserva en auditoría"><Input value={profileForm.reason} onChange={event=>setProfileForm({...profileForm,reason:event.target.value})} placeholder="Ej. Responsabilidad aprobada por Dirección"/></Field><div className="company-user-actions"><Button disabled={busy} onClick={()=>setProfileEditing(false)}>Cancelar</Button><Button variant="primary" loading={busy} disabled={!canSaveProfile} onClick={()=>void saveProfile()}>Guardar perfil</Button></div></div></Drawer>
  </div>;
}

function ProfileCatalog({profiles,loading,error,onRetry,onEdit}:{profiles:AccessProfile[];loading:boolean;error:string|null;onRetry:()=>Promise<void>;onEdit:(profile:AccessProfile)=>void}){return <DataState loading={loading&&!profiles.length} error={error} errorAction={<Button size="sm" onClick={()=>void onRetry()}><RefreshCw size={14}/>Reintentar</Button>} hasData={profiles.length} empty="No hay perfiles disponibles."><section className="access-profile-catalog">{groupProfiles(profiles).map(group=><div key={group.category}><header><div><h2>{categoryLabels[group.category]??group.category}</h2><p>{group.profiles.length} perfil{group.profiles.length===1?"":"es"}</p></div></header><div>{group.profiles.map(profile=><article key={profile.code}><span className="profile-icon"><Layers3 size={17}/></span><div><strong>{profile.name}</strong><p>{roleDescription(profile)}</p><small>{profile.permission_count} permisos · {profile.scope_kind==="company"?"Toda la empresa":"Sucursales asignadas"}</small></div><div className="profile-assignees"><Users size={14}/><span>{profile.assignee_count}</span></div>{profile.is_system?<Badge tone="neutral">Recomendado</Badge>:<Button size="sm" variant="secondary" onClick={()=>onEdit(profile)}><Pencil size={13}/>Editar</Button>}</article>)}</div></div>)}</section></DataState>;}
function UserStatus({status}:{status:CompanyUser["status"]}){if(status==="active")return <Badge tone="success">Activo</Badge>;if(status==="invited")return <Badge tone="info">Invitado</Badge>;return <Badge tone="neutral">Suspendido</Badge>;}
function toggle(values:string[],value:string){return values.includes(value)?values.filter(item=>item!==value):[...values,value];}
function profileWarnings(codes:string[]){const warnings:string[]=[];if(codes.includes("payroll_capture_review")&&codes.includes("payroll_approval"))warnings.push("La misma persona podrá capturar incidencias y aprobar nómina.");if(codes.includes("payroll_preparation")&&codes.includes("payroll_approval"))warnings.push("La misma persona podrá preparar y aprobar la nómina.");if(codes.includes("procurement_operations")&&codes.includes("procurement_approval"))warnings.push("La misma persona podrá operar y aprobar compras.");return warnings;}
function roleDescription(role:Pick<RoleOption,"code"|"description">){return role.code==="direccion_admin"?"Administra toda la información de la empresa.":role.description;}
function groupByCategory<T extends {category:string}>(items:T[]){const groups=new Map<string,T[]>();for(const item of items)groups.set(item.category,[...(groups.get(item.category)??[]),item]);return [...groups].map(([category,values])=>({category,values}));}
function groupRoles(roles:RoleOption[]){return groupByCategory(roles).map(group=>({category:group.category,roles:group.values}));}
function groupProfiles(profiles:AccessProfile[]){return groupByCategory(profiles).map(group=>({category:group.category,profiles:group.values}));}
function groupPermissions(permissions:PermissionOption[]){return groupByCategory(permissions).map(group=>({category:group.category,permissions:group.values}));}
