"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Building2, ChartNoAxesCombined, MapPin, Pencil, Plus, RefreshCw, UserRoundCheck } from "lucide-react";
import { Badge, Button, CurrencyInput, Drawer, Field, Input, Modal, Select, Tabs, useToast } from "@/app/components/ui/primitives";
import { DataPagination, DataState, DataToolbar, InteractiveTableRow, PageHeading } from "@/app/components/ui/data";
import { getSupabaseClient } from "@/app/lib/supabase";
import { OperationIdempotencyKeys } from "@/app/lib/operation-idempotency";
import { useSatrapy } from "@/app/components/SatrapyProvider";

type Location={id:string;external_code:string;name:string;location_type:string;is_active:boolean;updated_at:string;inventory_quantity:number;open_cash_sessions:number;active_counts:number;active_transfers:number;can_deactivate:boolean};
type Result={items:Location[];total:number;page:number;page_size:number};
type Profile={address_line_1?:string|null;address_line_2?:string|null;neighborhood?:string|null;municipality?:string|null;state_name?:string|null;postal_code?:string|null;country_code?:string|null;latitude?:number|null;longitude?:number|null;sales_floor_sqm?:number|null;storage_sqm?:number|null;storage_capacity_units?:number|null;cost_center_code?:string|null;opened_on?:string|null;closed_on?:string|null};
type EconomicTerms={effective_from?:string|null;currency_code?:string|null;monthly_base_rent?:number|null;monthly_services_budget?:number|null;initial_investment?:number|null};
type ResponsibilityType="branch_manager"|"inventory_owner"|"financial_owner";
type Responsibility={id:string;responsibility_type:ResponsibilityType;collaborator_id:string;collaborator_name:string;collaborator_code:string;effective_from:string;effective_to:string|null};
type Workspace=Location&{profile:Profile;economic_terms:EconomicTerms;responsibilities:Responsibility[]};
type CollaboratorOption={id:string;code:string;name:string};
type Profitability={currency_code:string|null;metrics:{gross_sales:number;returns:number;net_sales:number;net_cogs:number|null;gross_margin:number|null;gross_margin_percent:number|null;operating_expenses:number;operating_contribution:number|null;sales_per_sqm:number|null;break_even_sales:number|null;break_even_coverage_percent:number|null};coverage:{sale_item_count:number;costed_sale_item_count:number;recognized_cost_percent:number|null;sales_floor_sqm:number|null;planned_monthly_rent:number;planned_monthly_services:number};limitations:string[]};
type Form={code:string;name:string;type:string;status:string;address1:string;address2:string;neighborhood:string;municipality:string;state:string;postalCode:string;countryCode:string;latitude:string;longitude:string;salesFloor:string;storageArea:string;storageCapacity:string;costCenter:string;openedOn:string;closedOn:string;monthlyRent:string;monthlyServices:string;initialInvestment:string;economicEffectiveFrom:string;currencyCode:string;reason:string};

const PAGE_SIZE=25;
const typeOptions=[{value:"sucursal",label:"Sucursal"},{value:"almacen_central",label:"Almacén central"},{value:"almacen_operativo",label:"Almacén operativo"},{value:"campo",label:"Campo"}];
const responsibilityLabels:Record<ResponsibilityType,string>={branch_manager:"Responsable de sucursal",inventory_owner:"Responsable de inventario",financial_owner:"Responsable financiero"};
const emptyForm:Form={code:"",name:"",type:"sucursal",status:"active",address1:"",address2:"",neighborhood:"",municipality:"",state:"",postalCode:"",countryCode:"MX",latitude:"",longitude:"",salesFloor:"",storageArea:"",storageCapacity:"",costCenter:"",openedOn:"",closedOn:"",monthlyRent:"",monthlyServices:"",initialInvestment:"",economicEffectiveFrom:new Date().toISOString().slice(0,10),currencyCode:"MXN",reason:""};
const today=()=>new Date().toISOString().slice(0,10);
const monthStart=()=>`${today().slice(0,7)}-01`;
const optionalNumber=(value:string)=>value.trim()===""?null:Number(value);
const money=(value:number|null|undefined,currency="MXN")=>value==null?"No disponible":new Intl.NumberFormat("es-MX",{style:"currency",currency,maximumFractionDigits:0}).format(value);
const percent=(value:number|null|undefined)=>value==null?"No disponible":`${new Intl.NumberFormat("es-MX",{maximumFractionDigits:1}).format(value)}%`;

export function CompanyLocationsView({companyId,permissions}:{companyId:string;permissions:string[]}){
  const {isSuperAdmin}=useSatrapy();const {toast}=useToast();const idempotency=useRef(new OperationIdempotencyKeys());const can=(code:string)=>isSuperAdmin||permissions.includes("*")||permissions.includes(code);
  const [rows,setRows]=useState<Location[]>([]);const [total,setTotal]=useState(0);const [page,setPage]=useState(1);const [search,setSearch]=useState("");const [debounced,setDebounced]=useState("");const [type,setType]=useState("all");const [status,setStatus]=useState("active");const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);
  const [editing,setEditing]=useState<Location|null|undefined>(undefined);const [form,setForm]=useState<Form>(emptyForm);const [workspace,setWorkspace]=useState<Workspace|null>(null);const [workspaceLoading,setWorkspaceLoading]=useState(false);const [workspaceTab,setWorkspaceTabState]=useState("overview");
  const [collaborators,setCollaborators]=useState<CollaboratorOption[]>([]);const [responsibilityType,setResponsibilityType]=useState<ResponsibilityType>("branch_manager");const [collaboratorId,setCollaboratorId]=useState("");const [responsibilityDate,setResponsibilityDate]=useState(today());const [responsibilityReason,setResponsibilityReason]=useState("");
  const [dateFrom,setDateFrom]=useState(monthStart());const [dateTo,setDateTo]=useState(today());const [profitability,setProfitability]=useState<Profitability|null>(null);const [profitabilityLoading,setProfitabilityLoading]=useState(false);
  useEffect(()=>{const timer=window.setTimeout(()=>{setDebounced(search.trim());setPage(1);},280);return()=>window.clearTimeout(timer);},[search]);
  const load=useCallback(async()=>{setLoading(true);setError(null);const {data,error:rpcError}=await getSupabaseClient().rpc("list_company_locations",{p_company_id:companyId,p_query:debounced||null,p_location_type:type==="all"?null:type,p_status:status==="all"?null:status,p_page:page,p_page_size:PAGE_SIZE});const result=data as Result|null;setRows(result?.items??[]);setTotal(result?.total??0);setError(rpcError?"No se pudieron cargar las sucursales.":null);setLoading(false);},[companyId,debounced,page,status,type]);
  useEffect(()=>{void Promise.resolve().then(load);},[load]);
  const responsibilityByType=useMemo(()=>Object.fromEntries((workspace?.responsibilities??[]).map(item=>[item.responsibility_type,item])) as Partial<Record<ResponsibilityType,Responsibility>>,[workspace]);

  function formFromWorkspace(value:Workspace):Form{const p=value.profile??{};const e=value.economic_terms??{};return{code:value.external_code,name:value.name,type:value.location_type,status:value.is_active?"active":"inactive",address1:p.address_line_1??"",address2:p.address_line_2??"",neighborhood:p.neighborhood??"",municipality:p.municipality??"",state:p.state_name??"",postalCode:p.postal_code??"",countryCode:p.country_code??"MX",latitude:p.latitude?.toString()??"",longitude:p.longitude?.toString()??"",salesFloor:p.sales_floor_sqm?.toString()??"",storageArea:p.storage_sqm?.toString()??"",storageCapacity:p.storage_capacity_units?.toString()??"",costCenter:p.cost_center_code??"",openedOn:p.opened_on??"",closedOn:p.closed_on??"",monthlyRent:e.monthly_base_rent?.toString()??"",monthlyServices:e.monthly_services_budget?.toString()??"",initialInvestment:e.initial_investment?.toString()??"",economicEffectiveFrom:e.effective_from??today(),currencyCode:e.currency_code??"MXN",reason:""};}
  async function loadWorkspace(location:Location){setWorkspaceLoading(true);setWorkspaceTab("overview");setProfitability(null);const {data,error:rpcError}=await getSupabaseClient().rpc("get_location_operating_workspace",{p_company_id:companyId,p_location_id:location.id});if(rpcError){toast({title:"No se pudo abrir la sucursal",description:rpcError.message,tone:"error"});}else setWorkspace(data as Workspace);setWorkspaceLoading(false);}
  async function loadCollaborators(){if(!can("manage_location_responsibilities"))return;const {data}=await getSupabaseClient().rpc("search_location_responsibility_collaborators",{p_company_id:companyId,p_query:null,p_page:1,p_page_size:100});setCollaborators(((data as {items?:CollaboratorOption[]}|null)?.items)??[]);}
  function setWorkspaceTab(value:string){
    setWorkspaceTabState(value);
    if(value==="responsibilities")void loadCollaborators();
    if(value==="profitability"&&can("view_location_profitability"))void loadProfitability();
  }
  function openNew(){setEditing(null);setForm({...emptyForm,economicEffectiveFrom:today()});}
  function openEdit(){if(!workspace)return;setEditing(workspace);setForm(formFromWorkspace(workspace));}
  async function save(){const fingerprint=JSON.stringify({companyId,id:editing?.id??null,...form,updatedAt:editing?.updated_at??null});const requestId=idempotency.current.get("save-company-location-operating",fingerprint);setBusy(true);const {data,error:rpcError}=await getSupabaseClient().rpc("save_company_location_operating_model",{p_company_id:companyId,p_location_id:editing?.id??null,p_external_code:form.code,p_name:form.name,p_location_type:form.type,p_is_active:form.status==="active",p_address_line_1:form.address1||null,p_address_line_2:form.address2||null,p_neighborhood:form.neighborhood||null,p_municipality:form.municipality||null,p_state_name:form.state||null,p_postal_code:form.postalCode||null,p_country_code:form.countryCode,p_latitude:optionalNumber(form.latitude),p_longitude:optionalNumber(form.longitude),p_sales_floor_sqm:optionalNumber(form.salesFloor),p_storage_sqm:optionalNumber(form.storageArea),p_storage_capacity_units:optionalNumber(form.storageCapacity),p_cost_center_code:form.costCenter||null,p_opened_on:form.openedOn||null,p_closed_on:form.closedOn||null,p_monthly_base_rent:optionalNumber(form.monthlyRent),p_monthly_services_budget:optionalNumber(form.monthlyServices),p_initial_investment:optionalNumber(form.initialInvestment),p_economic_effective_from:form.economicEffectiveFrom||null,p_currency_code:form.currencyCode,p_reason:form.reason,p_expected_updated_at:editing?.updated_at??null,p_client_request_id:requestId});if(rpcError){toast({title:"No se pudo guardar",description:rpcError.message,tone:"error"});}else{idempotency.current.clear("save-company-location-operating");toast({title:editing?"Sucursal actualizada":"Sucursal creada",description:"El maestro operativo y su vigencia económica quedaron auditados.",tone:"success"});setEditing(undefined);setWorkspace(data as Workspace);await load();}setBusy(false);}
  async function assignResponsibility(){if(!workspace||!collaboratorId)return;const fingerprint=JSON.stringify({locationId:workspace.id,responsibilityType,collaboratorId,responsibilityDate,responsibilityReason});setBusy(true);const {data,error:rpcError}=await getSupabaseClient().rpc("assign_location_responsibility",{p_company_id:companyId,p_location_id:workspace.id,p_responsibility_type:responsibilityType,p_collaborator_id:collaboratorId,p_effective_from:responsibilityDate,p_reason:responsibilityReason,p_client_request_id:idempotency.current.get("assign-location-responsibility",fingerprint)});if(rpcError)toast({title:"No se asignó la responsabilidad",description:rpcError.message,tone:"error"});else{idempotency.current.clear("assign-location-responsibility");setWorkspace(data as Workspace);setResponsibilityReason("");toast({title:"Responsable asignado",description:"La asignación conserva vigencia, función y motivo.",tone:"success"});}setBusy(false);}
  async function loadProfitability(){if(!workspace)return;setProfitabilityLoading(true);const {data,error:rpcError}=await getSupabaseClient().rpc("get_location_profitability",{p_company_id:companyId,p_location_id:workspace.id,p_date_from:dateFrom,p_date_to:dateTo});if(rpcError){setProfitability(null);toast({title:"No se pudo calcular la rentabilidad",description:rpcError.message,tone:"error"});}else setProfitability(data as Profitability);setProfitabilityLoading(false);}
  const active=rows.filter(row=>row.is_active).length;const blocked=rows.filter(row=>!row.can_deactivate).length;const canSave=Boolean((editing?form.code.trim():true)&&form.name.trim()&&form.reason.trim()&&(!form.closedOn||form.status==="inactive"));
  return <div className="content-frame company-locations"><PageHeading eyebrow="Empresa" title="Sucursales y ubicaciones" description="Administra estructura, responsables y rentabilidad sin perder vigencias ni historial." action={can("manage_location_operating_profiles")?<Button variant="primary" onClick={openNew}><Plus size={15}/>Crear sucursal</Button>:undefined}/>
    <section className="location-management-summary"><article><span>Resultados</span><strong>{total.toLocaleString("es-MX")}</strong><small>según los filtros</small></article><article><span>Activas en página</span><strong>{active}</strong><small>disponibles para operar</small></article><article><span>Con operación</span><strong>{blocked}</strong><small>requieren cierre antes de desactivar</small></article></section>
    <DataToolbar search={search} onSearchChange={setSearch} placeholder="Buscar código o nombre" filters={<><Select value={type} onValueChange={value=>{setType(value);setPage(1);}} ariaLabel="Filtrar por tipo" options={[{value:"all",label:"Todos los tipos"},...typeOptions,{value:"pendiente_revision",label:"Pendiente de revisión"}]}/><Select value={status} onValueChange={value=>{setStatus(value);setPage(1);}} ariaLabel="Filtrar por estado" options={[{value:"all",label:"Todos los estados"},{value:"active",label:"Activas"},{value:"inactive",label:"Inactivas"}]}/></>} activeFilters={(search.trim()?1:0)+(type!=="all"?1:0)+(status!=="all"?1:0)} onClear={()=>{setSearch("");setDebounced("");setType("all");setStatus("all");setPage(1);}} results={total}/>
    <DataState loading={loading&&rows.length===0} error={error} errorAction={<Button size="sm" onClick={()=>void load()}><RefreshCw size={14}/>Reintentar</Button>} hasData={rows.length} empty="No hay sucursales para estos filtros."><div className="table-wrap surface-table"><table><thead><tr><th>Código</th><th>Nombre</th><th>Tipo</th><th>Estado</th><th>Operación vinculada</th></tr></thead><tbody>{rows.map(row=><InteractiveTableRow key={row.id} label={`Abrir operación de ${row.name}`} onActivate={()=>void loadWorkspace(row)}><td><span className="location-chip">{row.external_code}</span></td><td><strong>{row.name}</strong><small>Actualizada {new Date(row.updated_at).toLocaleDateString("es-MX")}</small></td><td><Badge tone={row.location_type==="pendiente_revision"?"warning":"primary"}>{typeOptions.find(item=>item.value===row.location_type)?.label??"Pendiente de revisión"}</Badge></td><td><Badge tone={row.is_active?"success":"neutral"}>{row.is_active?"Activa":"Inactiva"}</Badge></td><td>{row.can_deactivate?<span className="settings-muted">Sin pendientes</span>:<small>{[Number(row.inventory_quantity)?`${Number(row.inventory_quantity).toLocaleString("es-MX")} existencias`:"",row.open_cash_sessions?`${row.open_cash_sessions} cajas`:"",row.active_counts?`${row.active_counts} conteos`:"",row.active_transfers?`${row.active_transfers} transferencias`:""].filter(Boolean).join(" · ")}</small>}</td></InteractiveTableRow>)}</tbody></table></div></DataState><DataPagination page={page} total={total} pageSize={PAGE_SIZE} onChange={setPage}/>

    <Drawer open={workspace!==null||workspaceLoading} onOpenChange={open=>{if(!open&&!busy){setWorkspace(null);setWorkspaceLoading(false);}}} title={workspace?.name??"Cargando sucursal…"} className="location-operating-drawer">{workspaceLoading?<div className="loading-copy" role="status">Cargando operación…</div>:workspace&&<><Tabs value={workspaceTab} onValueChange={setWorkspaceTab} items={[{value:"overview",label:"Maestro"},{value:"responsibilities",label:"Responsables"},{value:"profitability",label:"Rentabilidad",disabled:!can("view_location_profitability")}]}/>{workspaceTab==="overview"&&<LocationOverview workspace={workspace} onEdit={can("manage_location_operating_profiles")?openEdit:undefined}/>} {workspaceTab==="responsibilities"&&<section className="location-responsibility-section"><header><div><span className="eyebrow">Accountability</span><h2>Responsables vigentes</h2><p>La responsabilidad operativa no cambia permisos de acceso.</p></div></header><div className="location-responsibility-grid">{(Object.keys(responsibilityLabels) as ResponsibilityType[]).map(kind=>{const assignment=responsibilityByType[kind];return <article key={kind}><UserRoundCheck size={18}/><span>{responsibilityLabels[kind]}</span><strong>{assignment?.collaborator_name??"Sin asignar"}</strong><small>{assignment?`${assignment.collaborator_code} · desde ${new Date(`${assignment.effective_from}T00:00:00`).toLocaleDateString("es-MX")}`:"Asigna una persona activa"}</small></article>;})}</div>{can("manage_location_responsibilities")&&<div className="location-responsibility-form"><Field label="Responsabilidad"><Select ariaLabel="Responsabilidad a asignar" value={responsibilityType} onValueChange={value=>setResponsibilityType(value as ResponsibilityType)} options={(Object.keys(responsibilityLabels) as ResponsibilityType[]).map(value=>({value,label:responsibilityLabels[value]}))}/></Field><Field label="Colaborador"><Select ariaLabel="Colaborador responsable" value={collaboratorId||"unselected"} onValueChange={value=>setCollaboratorId(value==="unselected"?"":value)} options={[{value:"unselected",label:"Selecciona una persona",disabled:true},...collaborators.map(item=>({value:item.id,label:`${item.name} · ${item.code}`}))]}/></Field><Field label="Vigente desde"><Input type="date" value={responsibilityDate} onChange={event=>setResponsibilityDate(event.target.value)}/></Field><Field label="Motivo"><Input value={responsibilityReason} onChange={event=>setResponsibilityReason(event.target.value)} placeholder="Ej. Nombramiento aprobado por Dirección"/></Field><Button variant="primary" loading={busy} disabled={!collaboratorId||!responsibilityDate||!responsibilityReason.trim()} onClick={()=>void assignResponsibility()}>Asignar responsable</Button></div>}</section>}{workspaceTab==="profitability"&&<ProfitabilityView data={profitability} loading={profitabilityLoading} dateFrom={dateFrom} dateTo={dateTo} onDateFrom={setDateFrom} onDateTo={setDateTo} onLoad={loadProfitability}/>}</>}</Drawer>

    <Modal open={editing!==undefined} onOpenChange={open=>{if(!open&&!busy)setEditing(undefined);}} eyebrow={editing?"Maestro de sucursal":"Nueva sucursal"} title={editing?editing.name:"Crear sucursal"} description="La estructura física y los costos de operación quedan auditados en una sola operación. Satrapy asignará el código automáticamente." className="location-operating-modal" footer={<><Button variant="secondary" disabled={busy} onClick={()=>setEditing(undefined)}>Cancelar</Button><Button variant="primary" loading={busy} disabled={!canSave} onClick={()=>void save()}>Guardar sucursal</Button></>}><LocationForm form={form} setForm={setForm} blocked={Boolean(editing&&!editing.can_deactivate)} creating={editing===null}/></Modal>
  </div>;
}

function LocationOverview({workspace,onEdit}:{workspace:Workspace;onEdit?:()=>void}){const p=workspace.profile??{};const e=workspace.economic_terms??{};return <section className="location-operating-overview"><header><div><span className="eyebrow">{workspace.external_code}</span><h2>{typeOptions.find(item=>item.value===workspace.location_type)?.label??workspace.location_type}</h2></div>{onEdit&&<Button variant="secondary" onClick={onEdit}><Pencil size={14}/>Editar maestro</Button>}</header><div className="location-operating-facts"><article><MapPin size={18}/><span>Ubicación</span><strong>{[p.address_line_1,p.neighborhood,p.municipality,p.state_name,p.postal_code].filter(Boolean).join(", ")||"Domicilio pendiente"}</strong><small>{p.latitude!=null&&p.longitude!=null?`${p.latitude}, ${p.longitude}`:"Coordenadas pendientes"}</small></article><article><Building2 size={18}/><span>Capacidad</span><strong>{p.sales_floor_sqm?`${p.sales_floor_sqm} m² de venta`:"Superficie pendiente"}</strong><small>{p.storage_sqm?`${p.storage_sqm} m² de almacén`:"Área de almacén pendiente"}</small></article><article><ChartNoAxesCombined size={18}/><span>Costos de operación</span><strong>{money(e.monthly_base_rent,e.currency_code??"MXN")} renta mensual</strong><small>{p.cost_center_code?`Centro de costo ${p.cost_center_code}`:"Centro de costo pendiente"}</small></article></div></section>;}

function ProfitabilityView({data,loading,dateFrom,dateTo,onDateFrom,onDateTo,onLoad}:{data:Profitability|null;loading:boolean;dateFrom:string;dateTo:string;onDateFrom:(value:string)=>void;onDateTo:(value:string)=>void;onLoad:()=>Promise<void>}){const currency=data?.currency_code??"MXN";const breakEvenDetail=data?.metrics.break_even_sales?`Equilibrio ${money(data.metrics.break_even_sales,currency)}`:data&&(data.coverage.planned_monthly_rent+data.coverage.planned_monthly_services>0)?"Sin ventas para calcular":"Faltan costos planeados";return <section className="location-profitability"><header><div><span className="eyebrow">Resultado por sucursal</span><h2>Rentabilidad del periodo</h2><p>Compara ventas, costo reconocido y gastos atribuidos a esta ubicación.</p></div></header><div className="location-profitability-filters"><Field label="Desde"><Input type="date" value={dateFrom} onChange={event=>onDateFrom(event.target.value)}/></Field><Field label="Hasta"><Input type="date" value={dateTo} onChange={event=>onDateTo(event.target.value)}/></Field><Button variant="secondary" loading={loading} disabled={!dateFrom||!dateTo||dateTo<dateFrom} onClick={()=>void onLoad()}>Calcular periodo</Button></div>{loading&&!data?<div className="loading-copy" role="status">Calculando rentabilidad…</div>:data?<><div className="location-profitability-grid"><Metric label="Ventas netas" value={money(data.metrics.net_sales,currency)}/><Metric label="Margen bruto" value={money(data.metrics.gross_margin,currency)} detail={percent(data.metrics.gross_margin_percent)}/><Metric label="Gastos atribuidos" value={money(data.metrics.operating_expenses,currency)}/><Metric label="Contribución operativa" value={money(data.metrics.operating_contribution,currency)}/><Metric label="Ventas por m²" value={money(data.metrics.sales_per_sqm,currency)}/><Metric label="Cobertura de equilibrio" value={percent(data.metrics.break_even_coverage_percent)} detail={breakEvenDetail}/></div><div className="location-profitability-coverage" role="status"><strong>Cobertura de costo reconocido: {percent(data.coverage.recognized_cost_percent)}</strong><span>{data.coverage.costed_sale_item_count} de {data.coverage.sale_item_count} partidas</span></div><ul className="location-profitability-notes">{data.limitations.map(item=><li key={item}>{item}</li>)}</ul></>:<div className="customer-master-empty">Selecciona un periodo para calcular resultados desde ventas, costos y contabilidad.</div>}</section>;}
function Metric({label,value,detail}:{label:string;value:string;detail?:string}){return <article><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</article>;}

function LocationForm({form,setForm,blocked,creating}:{form:Form;setForm:(value:Form)=>void;blocked:boolean;creating:boolean}){
  const update=<K extends keyof Form>(key:K,value:Form[K])=>setForm({...form,[key]:value});
  return <div className="location-operating-form">
    <section><h3>Identidad y vigencia</h3><div className="location-admin-form">
      {!creating&&<Field label="Código" hint="Asignado por Satrapy"><Input disabled value={form.code}/></Field>}
      <Field label="Nombre"><Input maxLength={160} value={form.name} onChange={event=>update("name",event.target.value)} placeholder="Sucursal Norte"/></Field>
      <Field label="Tipo"><Select ariaLabel="Tipo de ubicación" value={form.type} onValueChange={value=>update("type",value)} options={typeOptions}/></Field>
      <Field label="Estado"><Select ariaLabel="Estado de ubicación" value={form.status} onValueChange={value=>update("status",value)} options={[{value:"active",label:"Activa"},{value:"inactive",label:"Inactiva"}]}/></Field>
      <Field label="Fecha de apertura"><Input type="date" value={form.openedOn} onChange={event=>update("openedOn",event.target.value)}/></Field>
      <Field label="Fecha de cierre"><Input type="date" min={form.openedOn||undefined} value={form.closedOn} onChange={event=>update("closedOn",event.target.value)}/></Field>
      <Field label="Centro de costo"><Input value={form.costCenter} onChange={event=>update("costCenter",event.target.value)} placeholder="CC-SUC-03"/></Field>
    </div></section>
    <section><h3>Domicilio y capacidad</h3><div className="location-admin-form">
      <Field label="Domicilio"><Input value={form.address1} onChange={event=>update("address1",event.target.value)} placeholder="Calle y número"/></Field>
      <Field label="Complemento"><Input value={form.address2} onChange={event=>update("address2",event.target.value)} placeholder="Local, piso o referencia"/></Field>
      <Field label="Colonia"><Input value={form.neighborhood} onChange={event=>update("neighborhood",event.target.value)}/></Field>
      <Field label="Municipio"><Input value={form.municipality} onChange={event=>update("municipality",event.target.value)}/></Field>
      <Field label="Estado"><Input value={form.state} onChange={event=>update("state",event.target.value)}/></Field>
      <Field label="Código postal"><Input inputMode="numeric" value={form.postalCode} onChange={event=>update("postalCode",event.target.value)}/></Field>
      <Field label="País"><Input maxLength={2} value={form.countryCode} onChange={event=>update("countryCode",event.target.value.toUpperCase())}/></Field>
      <Field label="Latitud"><Input inputMode="decimal" value={form.latitude} onChange={event=>update("latitude",event.target.value)} placeholder="19.432608"/></Field>
      <Field label="Longitud"><Input inputMode="decimal" value={form.longitude} onChange={event=>update("longitude",event.target.value)} placeholder="-99.133209"/></Field>
      <Field label="Área de venta (m²)"><Input type="number" min="0.01" step="0.01" value={form.salesFloor} onChange={event=>update("salesFloor",event.target.value)}/></Field>
      <Field label="Área de almacén (m²)"><Input type="number" min="0" step="0.01" value={form.storageArea} onChange={event=>update("storageArea",event.target.value)}/></Field>
      <Field label="Capacidad de almacén"><Input type="number" min="0" step="0.001" value={form.storageCapacity} onChange={event=>update("storageCapacity",event.target.value)}/></Field>
    </div></section>
    <section><h3>Costos de operación</h3><div className="location-admin-form">
      <Field label="Vigente desde"><Input type="date" value={form.economicEffectiveFrom} onChange={event=>update("economicEffectiveFrom",event.target.value)}/></Field>
      <Field label="Renta mensual"><CurrencyInput currency={form.currencyCode} value={form.monthlyRent} onValueChange={value=>update("monthlyRent",value)}/></Field>
      <Field label="Servicios mensuales planeados"><CurrencyInput currency={form.currencyCode} value={form.monthlyServices} onValueChange={value=>update("monthlyServices",value)}/></Field>
      <Field label="Inversión inicial"><CurrencyInput currency={form.currencyCode} value={form.initialInvestment} onValueChange={value=>update("initialInvestment",value)}/></Field>
      <Field label="Moneda"><Input maxLength={3} value={form.currencyCode} onChange={event=>update("currencyCode",event.target.value.toUpperCase())}/></Field>
    </div></section>
    <Field label="Motivo del cambio" hint="Se conserva en auditoría"><Input value={form.reason} onChange={event=>update("reason",event.target.value)} placeholder="Ej. Apertura aprobada por Dirección"/></Field>
    {blocked&&<p className="location-operation-warning">Esta ubicación tiene operación vinculada. Puedes corregir sus datos, pero no cambiar el tipo ni desactivarla hasta resolver los pendientes.</p>}
    {form.closedOn&&form.status==="active"&&<p className="form-error" role="alert">Cambia el estado a Inactiva cuando exista una fecha de cierre.</p>}
  </div>;
}
