"use client";

import { CheckCircle2, FileCheck2, Plus, RefreshCw, Search, XCircle } from "lucide-react";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { useSearchParams } from "next/navigation";
import { Badge, Drawer, useToast } from "@/app/components/ui/primitives";
import { SalesButton as Button, SalesDataPagination as DataPagination, SalesDataToolbar as DataToolbar, SalesField as Field, SalesInput as Input, SalesSelect as Select } from "@/app/components/reui/sales-controls";
import { DataState, InteractiveTableRow, PageHeading } from "@/app/components/ui/data";
import { getSupabaseClient } from "@/app/lib/supabase";
import { OperationIdempotencyKeys } from "@/app/lib/operation-idempotency";
import { useSatrapy } from "@/app/components/SatrapyProvider";

type Status="pending_review"|"ready_to_issue"|"issued"|"rejected"|"cancelled";
type RequestRow={id:string;sale_id:string;folio:string;location_name:string;status:Status;tax_id:string;legal_name:string;tax_regime_code:string;fiscal_postal_code:string;cfdi_use_code:string;email:string;rejection_reason:string|null;issued_cfdi_uuid:string|null;created_at:string};
type SaleOption={sale_id:string;folio:string;customer_name:string|null;cancelled:boolean;completed_at:string};
const statusOptions=[{value:"all",label:"Todos los estados"},{value:"pending_review",label:"Pendientes de revisión"},{value:"ready_to_issue",label:"Listas para emitir"},{value:"issued",label:"Emitidas"},{value:"rejected",label:"Rechazadas"},{value:"cancelled",label:"Canceladas"}];
const statusLabel:Record<Status,string>={pending_review:"Pendiente de revisión",ready_to_issue:"Lista para emitir",issued:"Emitida",rejected:"Rechazada",cancelled:"Cancelada"};
const statusTone=(value:Status)=>value==="issued"?"success":value==="ready_to_issue"?"info":value==="pending_review"?"warning":"neutral" as const;
const initialDraft={taxId:"",legalName:"",taxRegime:"",postalCode:"",cfdiUse:"G03",email:""};

export function InvoiceRequestsModule({companyId,permissions}:{companyId:string;permissions:string[]}){
 const params=useSearchParams();const {toast}=useToast();const {isSuperAdmin}=useSatrapy();const keys=useRef(new OperationIdempotencyKeys()).current;const canManage=isSuperAdmin||permissions.includes("manage_invoice_requests");
 const [rows,setRows]=useState<RequestRow[]>([]);const [total,setTotal]=useState(0);const [page,setPage]=useState(1);const [query,setQuery]=useState("");const [status,setStatus]=useState("all");const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
 const [createOpen,setCreateOpen]=useState(Boolean(params.get("ticket")&&canManage));const [ticketQuery,setTicketQuery]=useState(params.get("ticket")??"");const [sales,setSales]=useState<SaleOption[]>([]);const [selectedSale,setSelectedSale]=useState<SaleOption|null>(null);const [draft,setDraft]=useState(initialDraft);const [saving,setSaving]=useState(false);const [selected,setSelected]=useState<RequestRow|null>(null);const [reason,setReason]=useState("");const [cfdiUuid,setCfdiUuid]=useState("");
 const load=useCallback(async()=>{setLoading(true);const{data,error:loadError}=await getSupabaseClient().rpc("list_sale_invoice_requests",{p_company_id:companyId,p_query:query||null,p_status:status,p_page:page,p_page_size:50});const result=data as{items?:RequestRow[];total?:number}|null;setRows(result?.items??[]);setTotal(result?.total??0);setError(loadError?"No se pudieron consultar las solicitudes de factura.":null);setLoading(false);},[companyId,page,query,status]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),180);return()=>window.clearTimeout(timer);},[load]);
 useEffect(()=>{if(!createOpen||ticketQuery.trim().length<2)return;const timer=window.setTimeout(async()=>{const{data}=await getSupabaseClient().rpc("list_sales",{p_company_id:companyId,p_location_id:null,p_query:ticketQuery.trim(),p_page:1,p_page_size:10});setSales(((data as{items?:SaleOption[]}|null)?.items??[]).filter(item=>!item.cancelled));},220);return()=>window.clearTimeout(timer);},[companyId,createOpen,ticketQuery]);
 function resetCreate(){setCreateOpen(false);setSelectedSale(null);setTicketQuery("");setSales([]);setDraft(initialDraft);}
 async function save(event:FormEvent){event.preventDefault();if(!selectedSale)return;const normalized={taxId:draft.taxId.trim().toUpperCase().replace(/[^A-Z0-9Ñ&]/g,""),legalName:draft.legalName.trim(),taxRegime:draft.taxRegime.trim().toUpperCase(),postalCode:draft.postalCode.trim(),cfdiUse:draft.cfdiUse.trim().toUpperCase(),email:draft.email.trim().toLowerCase()};if(!/^[A-Z&Ñ]{3,4}\d{6}[A-Z0-9]{3}$/.test(normalized.taxId)||!normalized.legalName||!normalized.taxRegime||!/^\d{5}$/.test(normalized.postalCode)||!normalized.cfdiUse||!/^\S+@\S+\.\S+$/.test(normalized.email)){toast({title:"Completa los datos fiscales",description:"Revisa RFC, razón social, régimen, código postal, uso CFDI y correo.",tone:"info"});return;}setSaving(true);const fingerprint=JSON.stringify({sale:selectedSale.sale_id,...normalized});const{error:saveError}=await getSupabaseClient().rpc("save_sale_invoice_request",{p_company_id:companyId,p_sale_id:selectedSale.sale_id,p_tax_id:normalized.taxId,p_legal_name:normalized.legalName,p_tax_regime_code:normalized.taxRegime,p_fiscal_postal_code:normalized.postalCode,p_cfdi_use_code:normalized.cfdiUse,p_email:normalized.email,p_client_request_id:keys.get("invoice-request",fingerprint)});setSaving(false);if(saveError){toast({title:"No se registró la solicitud",description:saveError.message,tone:"error"});return;}keys.clear("invoice-request");resetCreate();toast({title:"Solicitud registrada",description:"Quedó pendiente de revisión y ligada al ticket original.",tone:"success"});await load();}
 async function changeStatus(next:Status){if(!selected)return;setSaving(true);const{data,error:updateError}=await getSupabaseClient().rpc("update_sale_invoice_request_status",{p_company_id:companyId,p_request_id:selected.id,p_status:next,p_reason:reason.trim()||null,p_cfdi_uuid:cfdiUuid.trim()||null});setSaving(false);if(updateError){toast({title:"No se actualizó la solicitud",description:updateError.message,tone:"error"});return;}setSelected(data as RequestRow);setReason("");setCfdiUuid("");toast({title:"Estado actualizado",description:`La solicitud quedó ${statusLabel[next].toLowerCase()}.`,tone:"success"});await load();}
 return <div className="content-frame invoice-requests"><PageHeading eyebrow="Facturación asistida" title="Solicitudes de factura" description="Revisa los datos fiscales de cada ticket y prepara solicitudes para emisión. Una solicitud no es un CFDI timbrado." action={<div className="invoice-requests__actions"><Button variant="secondary" onClick={()=>void load()}><RefreshCw size={15}/>Actualizar</Button>{canManage&&<Button variant="primary" onClick={()=>setCreateOpen(true)}><Plus size={15}/>Nueva solicitud</Button>}</div>}/><DataToolbar search={query} onSearchChange={value=>{setQuery(value);setPage(1);}} placeholder="Buscar folio, RFC o razón social" filters={<Select ariaLabel="Filtrar por estado" value={status} onValueChange={value=>{setStatus(value);setPage(1);}} options={statusOptions}/>} activeFilters={(query?1:0)+(status!=="all"?1:0)} onClear={()=>{setQuery("");setStatus("all");setPage(1);}} results={total}/><DataState loading={loading&&rows.length===0} error={error} errorAction={<Button size="sm" onClick={()=>void load()}>Reintentar</Button>} hasData={rows.length} emptyTitle={query||status!=="all"?"Sin coincidencias":"Aún no hay solicitudes"} empty={query||status!=="all"?"Cambia la búsqueda o limpia los filtros.":"Registra una solicitud desde un ticket para comenzar."}><div className="table-wrap surface-table"><table><thead><tr><th>Ticket</th><th>Receptor</th><th>Datos fiscales</th><th>Correo</th><th>Estado</th><th>Solicitud</th></tr></thead><tbody>{rows.map(row=><InteractiveTableRow key={row.id} label={`Abrir solicitud del ticket ${row.folio}`} onActivate={()=>setSelected(row)}><td><strong>{row.folio}</strong><small>{row.location_name}</small></td><td><strong>{row.legal_name}</strong><small className="mono">{row.tax_id}</small></td><td><span>{row.tax_regime_code} · CP {row.fiscal_postal_code}</span><small>Uso CFDI {row.cfdi_use_code}</small></td><td>{row.email}</td><td><Badge tone={statusTone(row.status)}>{statusLabel[row.status]}</Badge></td><td><small>{new Date(row.created_at).toLocaleString("es-MX")}</small></td></InteractiveTableRow>)}</tbody></table></div><DataPagination page={page} total={total} pageSize={50} onChange={setPage}/></DataState>
 <Drawer open={createOpen} onOpenChange={open=>!open&&!saving&&resetCreate()} title="Nueva solicitud de factura" description="Selecciona el ticket y captura únicamente los datos fiscales que falten." className="invoice-request-drawer"><form onSubmit={save}><section><h3>Ticket</h3><Field label="Folio del ticket"><div className="invoice-ticket-search"><Search size={16} aria-hidden="true"/><Input autoFocus value={ticketQuery} onChange={event=>{setTicketQuery(event.target.value);setSelectedSale(null);}} placeholder="Ej. VTA-000123"/></div></Field>{sales.length>0&&!selectedSale&&<div className="invoice-ticket-results" role="list" aria-label="Tickets encontrados">{sales.map(sale=><button type="button" role="listitem" key={sale.sale_id} onClick={()=>setSelectedSale(sale)}><strong>{sale.folio}</strong><span>{sale.customer_name??"Venta de mostrador"} · {new Date(sale.completed_at).toLocaleString("es-MX")}</span></button>)}</div>}{selectedSale&&<p className="invoice-ticket-selected"><CheckCircle2 size={16}/><span><strong>{selectedSale.folio}</strong>{selectedSale.customer_name??"Venta de mostrador"}</span></p>}</section><section><h3>Datos fiscales del receptor</h3><div className="invoice-request-grid"><Field label="RFC"><Input required maxLength={13} value={draft.taxId} onChange={event=>setDraft({...draft,taxId:event.target.value.toUpperCase()})} placeholder="XAXX010101000" autoComplete="off"/></Field><Field label="Razón social"><Input required value={draft.legalName} onChange={event=>setDraft({...draft,legalName:event.target.value})} autoComplete="organization"/></Field><Field label="Régimen fiscal"><Input required value={draft.taxRegime} onChange={event=>setDraft({...draft,taxRegime:event.target.value})} placeholder="Ej. 601"/></Field><Field label="Código postal fiscal"><Input required inputMode="numeric" maxLength={5} value={draft.postalCode} onChange={event=>setDraft({...draft,postalCode:event.target.value.replace(/\D/g,"")})} placeholder="00000" autoComplete="postal-code"/></Field><Field label="Uso CFDI"><Input required value={draft.cfdiUse} onChange={event=>setDraft({...draft,cfdiUse:event.target.value.toUpperCase()})} placeholder="G03"/></Field><Field label="Correo para entrega"><Input required type="email" value={draft.email} onChange={event=>setDraft({...draft,email:event.target.value})} placeholder="facturas@empresa.mx" autoComplete="email"/></Field></div></section><footer><Button type="button" disabled={saving} onClick={resetCreate}>Cancelar</Button><Button type="submit" variant="primary" loading={saving}>Registrar solicitud</Button></footer></form></Drawer>
 <Drawer open={Boolean(selected)} onOpenChange={open=>!open&&!saving&&setSelected(null)} eyebrow="Solicitud ligada al ticket" title={selected?.folio??"Solicitud"} description="Los datos son una fotografía fiscal; no modifican la venta ni el ticket originales." className="invoice-request-drawer">{selected&&<div className="invoice-request-detail"><dl><div><dt>Estado</dt><dd><Badge tone={statusTone(selected.status)}>{statusLabel[selected.status]}</Badge></dd></div><div><dt>RFC</dt><dd className="mono">{selected.tax_id}</dd></div><div><dt>Razón social</dt><dd>{selected.legal_name}</dd></div><div><dt>Régimen y CP</dt><dd>{selected.tax_regime_code} · {selected.fiscal_postal_code}</dd></div><div><dt>Uso CFDI</dt><dd>{selected.cfdi_use_code}</dd></div><div><dt>Correo</dt><dd>{selected.email}</dd></div></dl>{selected.rejection_reason&&<p className="settings-note is-danger">Motivo: {selected.rejection_reason}</p>}{selected.issued_cfdi_uuid&&<p className="settings-note">UUID fiscal: <span className="mono">{selected.issued_cfdi_uuid}</span></p>}{canManage&&selected.status==="pending_review"&&<section><h3>Revisión</h3><Field label="Motivo si se rechaza"><Input value={reason} onChange={event=>setReason(event.target.value)} placeholder="Describe qué debe corregirse"/></Field><div className="invoice-request-status-actions"><Button variant="danger" disabled={!reason.trim()} onClick={()=>void changeStatus("rejected")}><XCircle size={15}/>Rechazar solicitud</Button><Button variant="primary" onClick={()=>void changeStatus("ready_to_issue")}><FileCheck2 size={15}/>Marcar lista para emitir</Button></div></section>}{canManage&&selected.status==="ready_to_issue"&&<section><h3>Emisión asistida</h3><p>Registra el UUID sólo después de confirmar que el CFDI fue timbrado fuera de Satrapy.</p><Field label="UUID fiscal"><Input value={cfdiUuid} onChange={event=>setCfdiUuid(event.target.value)} placeholder="00000000-0000-0000-0000-000000000000"/></Field><div className="invoice-request-status-actions"><Button variant="danger" disabled={!reason.trim()} onClick={()=>void changeStatus("rejected")}><XCircle size={15}/>Rechazar solicitud</Button><Button variant="primary" disabled={!cfdiUuid.trim()} onClick={()=>void changeStatus("issued")}><CheckCircle2 size={15}/>Registrar como emitida</Button></div></section>}</div>}</Drawer></div>;
}
