"use client";

import { Pencil, Plus, RefreshCw } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { DataPagination, DataRefreshStatus, DataState, DataToolbar, InteractiveTableRow, Table } from "@/app/components/ui/data";
import { Badge, Button, Drawer, Field, Input, Select, Tabs, useToast } from "@/app/components/ui/primitives";
import { OperationIdempotencyKeys } from "@/app/lib/operation-idempotency";
import { presentImportedSourceText } from "@/app/lib/presentation-text";
import { getSupabaseClient } from "@/app/lib/supabase";

const PAGE_SIZE=50;
type PriceList={id:string;internal_code:string;external_code:string|null;name:string;currency_code:string;is_active:boolean;is_default:boolean;source:string;updated_at:string;current_price_count:number};
type PriceProduct={product_id:string;internal_sku:string;name:string;unit:string|null;is_active:boolean;amount:number|null;tax_rate:number|null;tax_amount:number|null;total_amount:number|null;valid_from:string|null;valid_to:string|null;next_amount:number|null;next_valid_from:string|null};
type Location={id:string;name:string;external_code:string;default_price_list_id:string|null};
type ListDraft={id:string|null;internalCode:string;name:string;currencyCode:string;active:boolean;isDefault:boolean;reason:string;updatedAt:string|null;externalCode:string|null};
type PriceDraft={product:PriceProduct;amount:string;effectiveFrom:string;reason:string};
const blankList=():ListDraft=>({id:null,internalCode:"",name:"",currencyCode:"MXN",active:true,isDefault:false,reason:"",updatedAt:null,externalCode:null});
function message(error:{message?:string}|null,fallback:string){return presentImportedSourceText(error?.message||fallback);}
function money(value:number|null,currency:string){return value==null?"—":new Intl.NumberFormat("es-MX",{style:"currency",currency,minimumFractionDigits:2}).format(value);}
function date(value:string|null){return value?new Intl.DateTimeFormat("es-MX",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";}

export function PriceCatalogManagement({companyId,locations,onAssignLocation,onChanged}:{companyId:string;locations:Location[];onAssignLocation:(location?:Location)=>void;onChanged:()=>Promise<void>}){
  const {toast}=useToast();const idempotency=useRef(new OperationIdempotencyKeys()).current;
  const [section,setSection]=useState("lists");const [lists,setLists]=useState<PriceList[]>([]);const [selectedListId,setSelectedListId]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
  const [listDraft,setListDraft]=useState<ListDraft|null>(null);const [priceDraft,setPriceDraft]=useState<PriceDraft|null>(null);const [saving,setSaving]=useState(false);
  const [products,setProducts]=useState<PriceProduct[]>([]);const [productLoading,setProductLoading]=useState(false);const [productError,setProductError]=useState<string|null>(null);const [query,setQuery]=useState("");const [debouncedQuery,setDebouncedQuery]=useState("");const [page,setPage]=useState(1);const [total,setTotal]=useState(0);
  const selectedList=lists.find(item=>item.id===selectedListId)??null;
  const loadLists=useCallback(async()=>{setLoading(true);setError(null);const {data,error:loadError}=await getSupabaseClient().rpc("list_price_lists_admin",{p_company_id:companyId});const next=(data??[]) as PriceList[];setLists(next);setSelectedListId(current=>next.some(item=>item.id===current)?current:(next.find(item=>item.is_default&&item.is_active)??next.find(item=>item.is_active)??next[0])?.id??"");setError(loadError?message(loadError,"No se pudieron cargar las listas."):null);setLoading(false);},[companyId]);
  useEffect(()=>{void Promise.resolve().then(loadLists);},[loadLists]);
  useEffect(()=>{const timer=window.setTimeout(()=>{setDebouncedQuery(query.trim());setPage(1);},280);return()=>window.clearTimeout(timer);},[query]);
  const loadProducts=useCallback(async()=>{if(!selectedListId){setProducts([]);setTotal(0);return;}setProductLoading(true);setProductError(null);const {data,error:loadError}=await getSupabaseClient().rpc("search_price_list_products",{p_company_id:companyId,p_price_list_id:selectedListId,p_query:debouncedQuery||null,p_page:page,p_page_size:PAGE_SIZE});const result=data as {items?:PriceProduct[];total?:number}|null;setProducts(result?.items??[]);setTotal(result?.total??0);setProductError(loadError?message(loadError,"No se pudieron cargar los productos."):null);setProductLoading(false);},[companyId,debouncedQuery,page,selectedListId]);
  useEffect(()=>{if(section==="prices")void Promise.resolve().then(loadProducts);},[loadProducts,section]);
  async function refreshAll(){await Promise.all([loadLists(),section==="prices"?loadProducts():Promise.resolve()]);}
  function editList(list?:PriceList){setListDraft(list?{id:list.id,internalCode:list.internal_code,name:list.name,currencyCode:list.currency_code,active:list.is_active,isDefault:list.is_default,reason:"",updatedAt:list.updated_at,externalCode:list.external_code}:blankList());}
  async function saveList(event:FormEvent){event.preventDefault();if(!listDraft)return;const clean={...listDraft,internalCode:listDraft.internalCode.trim().toUpperCase(),name:listDraft.name.trim(),currencyCode:listDraft.currencyCode.trim().toUpperCase(),reason:listDraft.reason.trim()};if(!clean.internalCode||!clean.name||clean.currencyCode.length!==3||!clean.reason)return;setSaving(true);const fingerprint=JSON.stringify(clean);const {error:saveError}=await getSupabaseClient().rpc("save_price_list",{p_company_id:companyId,p_price_list_id:clean.id,p_internal_code:clean.internalCode,p_name:clean.name,p_currency_code:clean.currencyCode,p_is_active:clean.active,p_is_default:clean.isDefault,p_reason:clean.reason,p_expected_updated_at:clean.updatedAt,p_client_request_id:idempotency.get("save-price-list",fingerprint)});if(saveError)toast({title:"No se pudo guardar la lista",description:message(saveError,"Verifica los datos."),tone:"error"});else{idempotency.clear("save-price-list");setListDraft(null);await loadLists();await onChanged();toast({title:clean.id?"Lista actualizada":"Lista creada",description:"El cambio quedó auditado.",tone:"success"});}setSaving(false);}
  async function savePrice(event:FormEvent){event.preventDefault();if(!priceDraft||!selectedList)return;const amount=Number(priceDraft.amount);const reason=priceDraft.reason.trim();if(!(amount>0)||!reason)return;setSaving(true);const effective=priceDraft.effectiveFrom?new Date(priceDraft.effectiveFrom).toISOString():null;const fingerprint=JSON.stringify({list:selectedList.id,product:priceDraft.product.product_id,amount,effective,reason});const {error:saveError}=await getSupabaseClient().rpc("save_product_price",{p_company_id:companyId,p_price_list_id:selectedList.id,p_product_id:priceDraft.product.product_id,p_amount:amount,p_effective_from:effective,p_reason:reason,p_client_request_id:idempotency.get("save-product-price",fingerprint)});if(saveError)toast({title:"No se pudo registrar el precio",description:message(saveError,"Verifica importe y vigencia."),tone:"error"});else{idempotency.clear("save-product-price");setPriceDraft(null);await Promise.all([loadProducts(),loadLists()]);toast({title:"Nueva vigencia registrada",description:"El precio anterior permanece en el historial.",tone:"success"});}setSaving(false);}
  const activeLists=lists.filter(item=>item.is_active);
  return <section className="settings-resource price-management">
    <header className="price-management__heading"><div><h2>Listas y precios</h2><p>Crea listas canónicas, registra nuevas vigencias y asígnalas a ubicaciones sin depender de archivos importados.</p></div><Button size="sm" variant="secondary" onClick={()=>void refreshAll()}><RefreshCw size={14}/> Actualizar</Button></header>
    <p className="price-management__volume"><strong>Captura puntual:</strong> adecuada para listas nuevas y cambios individuales. Para actualizar cientos o miles de productos, usa la importación masiva de precios.</p>
    <ol className="price-management__flow" aria-label="Pasos para preparar precios de venta"><li className={section==="lists"?"is-active":lists.length?"is-complete":""}><button type="button" onClick={()=>setSection("lists")} aria-current={section==="lists"?"step":undefined}><span>1</span><strong>Crear la lista</strong><small>Define nombre y moneda.</small></button></li><li className={section==="prices"?"is-active":lists.some(list=>list.current_price_count>0)?"is-complete":""}><button type="button" disabled={!lists.length} onClick={()=>setSection("prices")} aria-current={section==="prices"?"step":undefined}><span>2</span><strong>Capturar precios e IVA</strong><small>El IVA viene de cada producto.</small></button></li><li className={section==="locations"?"is-active":locations.some(location=>location.default_price_list_id)?"is-complete":""}><button type="button" onClick={()=>setSection("locations")} aria-current={section==="locations"?"step":undefined}><span>3</span><strong>Asignar a sucursales</strong><small>Elige qué lista usa cada una.</small></button></li></ol>
    <Tabs value={section} onValueChange={value=>setSection(value)} items={[{value:"lists",label:`Listas (${lists.length})`},{value:"prices",label:"Precios e IVA",disabled:!lists.length},{value:"locations",label:`Sucursales (${locations.length})`}]}/>
    {section==="lists"&&<><div className="price-management__section-heading"><div><h3>Listas canónicas</h3><p>Una lista predeterminada habilita a una empresa vacía para resolver precios sin una importación previa.</p></div><Button size="sm" variant="primary" onClick={()=>editList()}><Plus size={14}/> Nueva lista</Button></div><DataState loading={loading} error={error} hasData={lists.length} emptyTitle="Aún no hay listas de precios" empty="Crea la primera lista desde cero; después podrás asignar precios y ubicaciones." emptyAction={<Button size="sm" variant="primary" onClick={()=>editList()}><Plus size={14}/> Crear primera lista</Button>} errorAction={<Button size="sm" onClick={()=>void loadLists()}>Reintentar</Button>}><Table className="price-management__table"><thead><tr><th>Código</th><th>Lista</th><th>Moneda</th><th>Precios vigentes</th><th>Estado</th><th>Uso</th><th/></tr></thead><tbody>{lists.map(list=><tr key={list.id}><td><strong className="mono">{list.internal_code}</strong>{list.external_code&&list.external_code!==list.internal_code&&<small>Origen: {list.external_code}</small>}</td><td><strong>{list.name}</strong><small>{list.source==="manual"?"Creada en Satrapy":"Importada y canónica"}</small></td><td><Badge tone="info">{list.currency_code}</Badge></td><td>{list.current_price_count.toLocaleString("es-MX")}</td><td><Badge tone={list.is_active?"success":"neutral"}>{list.is_active?"Activa":"Inactiva"}</Badge></td><td>{list.is_default?<Badge tone="primary">Predeterminada</Badge>:"—"}</td><td className="settings-row-actions"><Button size="sm" variant="ghost" onClick={()=>editList(list)}><Pencil size={14}/> Editar</Button></td></tr>)}</tbody></Table></DataState></>}
    {section==="prices"&&<><div className="price-management__price-context"><Field label="Lista de precios"><Select ariaLabel="Lista para administrar precios" value={selectedListId} onValueChange={value=>{setSelectedListId(value);setPage(1);}} options={lists.map(list=>({value:list.id,label:`${list.name} · ${list.currency_code}${list.is_active?"":" · inactiva"}`}))}/></Field>{selectedList&&!selectedList.is_active&&<Badge tone="warning">Actívala para registrar precios</Badge>}</div><DataToolbar search={query} onSearchChange={setQuery} placeholder="Buscar código Satrapy, nombre o código de barras" results={total}/><DataRefreshStatus loading={productLoading} hasData={products.length}/><DataState loading={productLoading&&!products.length} error={productError} hasData={products.length} empty="No hay productos que coincidan con esta búsqueda." errorAction={<Button size="sm" onClick={()=>void loadProducts()}>Reintentar</Button>}><Table className="price-management__table"><thead><tr><th>Producto</th><th>Unidad</th><th>Precio sin IVA</th><th>IVA</th><th>Precio total</th><th>Desde</th><th>Próxima vigencia</th><th/></tr></thead><tbody>{products.map(product=><InteractiveTableRow key={product.product_id} disabled={!selectedList?.is_active} label={`Registrar precio para ${product.name}`} onActivate={()=>setPriceDraft({product,amount:product.amount==null?"":String(product.amount),effectiveFrom:"",reason:""})}><td><strong>{product.name}</strong><small className="mono">{product.internal_sku}</small></td><td>{product.unit??"—"}</td><td><strong>{money(product.amount,selectedList?.currency_code??"MXN")}</strong></td><td>{product.tax_rate==null?<Badge tone="warning">Sin tasa</Badge>:<><strong>{money(product.tax_amount,selectedList?.currency_code??"MXN")}</strong><small>{(product.tax_rate*100).toLocaleString("es-MX")}%</small></>}</td><td><strong>{money(product.total_amount,selectedList?.currency_code??"MXN")}</strong></td><td>{date(product.valid_from)}</td><td>{product.next_valid_from?<><strong>{money(product.next_amount,selectedList?.currency_code??"MXN")}</strong><small>{date(product.next_valid_from)} · sin IVA</small></>:"—"}</td><td className="settings-row-actions">{selectedList?.is_active&&<Button size="sm" variant="ghost" onClick={()=>setPriceDraft({product,amount:product.amount==null?"":String(product.amount),effectiveFrom:"",reason:""})}><Plus size={14}/> Nueva vigencia</Button>}</td></InteractiveTableRow>)}</tbody></Table></DataState><DataPagination page={page} total={total} pageSize={PAGE_SIZE} onChange={setPage} label="productos"/></>}
    {section==="locations"&&<><div className="price-management__section-heading"><div><h3>Asignación por ubicación</h3><p>Una asignación afecta ventas nuevas; nunca modifica ventas confirmadas ni el surtido comercial.</p></div>{activeLists.length>0&&<Button size="sm" variant="primary" onClick={()=>onAssignLocation()}><Plus size={14}/> Asignar lista</Button>}</div>{activeLists.length===0?<div className="price-management__empty-note">Crea y activa una lista antes de asignarla a una ubicación.</div>:<Table className="price-management__table"><thead><tr><th>Ubicación</th><th>Lista asignada</th><th/></tr></thead><tbody>{locations.map(location=>{const list=lists.find(item=>item.id===location.default_price_list_id);return <tr key={location.id}><td><strong>{location.name}</strong><small className="mono">{location.external_code}</small></td><td>{list?<><strong>{list.name}</strong><small>{list.currency_code}</small></>:<Badge tone="warning">Sin lista</Badge>}</td><td className="settings-row-actions"><Button size="sm" variant="ghost" onClick={()=>onAssignLocation(location)}><Pencil size={14}/> {list?"Cambiar":"Asignar"}</Button></td></tr>})}</tbody></Table>}</>}
    <Drawer open={Boolean(listDraft)} onOpenChange={open=>{if(!open&&!saving)setListDraft(null);}} title={listDraft?.id?"Editar lista de precios":"Nueva lista de precios"} className="price-management__drawer">{listDraft&&<form className="sales-form" onSubmit={saveList}><p className="settings-drawer-intro">La lista se crea en Satrapy y también puede recibir precios importados posteriormente.</p>{listDraft.externalCode&&<p className="price-management__source">Referencia importada conservada: <strong>{listDraft.externalCode}</strong></p>}<Field label="Código Satrapy"><Input required maxLength={80} value={listDraft.internalCode} onChange={event=>setListDraft({...listDraft,internalCode:event.target.value.toUpperCase()})} placeholder="MENUDEO"/></Field><Field label="Nombre"><Input required maxLength={160} value={listDraft.name} onChange={event=>setListDraft({...listDraft,name:event.target.value})} placeholder="Menudeo"/></Field><Field label="Moneda" hint="Código ISO de tres letras."><Input required maxLength={3} value={listDraft.currencyCode} onChange={event=>setListDraft({...listDraft,currencyCode:event.target.value.replace(/[^a-z]/gi,"").toUpperCase()})}/></Field><label className="sales-checkbox"><input type="checkbox" checked={listDraft.active} onChange={event=>setListDraft({...listDraft,active:event.target.checked,isDefault:event.target.checked?listDraft.isDefault:false})}/> Lista activa</label><label className="sales-checkbox"><input type="checkbox" disabled={!listDraft.active} checked={listDraft.isDefault} onChange={event=>setListDraft({...listDraft,isDefault:event.target.checked})}/> Predeterminada para la empresa</label><label className="operation-reason">Motivo obligatorio<textarea required rows={3} value={listDraft.reason} onChange={event=>setListDraft({...listDraft,reason:event.target.value})}/></label><div className="price-management__actions"><Button disabled={saving} onClick={()=>setListDraft(null)}>Cancelar</Button><Button type="submit" variant="primary" loading={saving} disabled={!listDraft.internalCode.trim()||!listDraft.name.trim()||listDraft.currencyCode.length!==3||!listDraft.reason.trim()}>Guardar lista</Button></div></form>}</Drawer>
    <Drawer open={Boolean(priceDraft)} onOpenChange={open=>{if(!open&&!saving)setPriceDraft(null);}} title="Registrar nueva vigencia" className="price-management__drawer">{priceDraft&&selectedList&&<form className="sales-form" onSubmit={savePrice}><p className="settings-drawer-intro">Se cerrará la vigencia anterior y se insertará una nueva. El historial no se edita ni se elimina.</p><div className="price-management__product"><strong>{priceDraft.product.name}</strong><small>{priceDraft.product.internal_sku} · {selectedList.name}</small></div>{priceDraft.product.tax_rate==null?<div className="price-management__tax-warning" role="status"><div><strong>Falta definir el IVA de este producto</strong><p>El impuesto se asigna en el producto porque puede reutilizarse en todas las listas. El POS seguirá bloqueándolo hasta completar esa configuración.</p></div><Link href="/satrapy/inventario/productos">Abrir productos</Link></div>:<div className="price-management__tax-ready"><span>Tratamiento fiscal<strong>IVA {(priceDraft.product.tax_rate*100).toLocaleString("es-MX")}%</strong></span><small>Se aplicará automáticamente al precio base.</small></div>}<Field label={`Precio sin IVA (${selectedList.currency_code})`} hint="Captura el importe base; Satrapy calcula el IVA y el total."><Input required type="number" min="0.000001" step="0.000001" inputMode="decimal" value={priceDraft.amount} onChange={event=>setPriceDraft({...priceDraft,amount:event.target.value})}/></Field><div className="price-management__price-summary" aria-label="Resumen del precio"><span>Precio sin IVA<strong>{money(Number(priceDraft.amount||0)||null,selectedList.currency_code)}</strong></span><span>IVA<strong>{priceDraft.product.tax_rate==null?"Pendiente":money(Number(priceDraft.amount||0)*priceDraft.product.tax_rate,selectedList.currency_code)}</strong></span><span>Precio final<strong>{priceDraft.product.tax_rate==null?"Pendiente":money(Number(priceDraft.amount||0)*(1+priceDraft.product.tax_rate),selectedList.currency_code)}</strong></span></div><Field label="Inicio de vigencia" hint="Déjalo vacío para aplicar al confirmar."><Input type="datetime-local" aria-label="Inicio de vigencia" value={priceDraft.effectiveFrom} onChange={event=>setPriceDraft({...priceDraft,effectiveFrom:event.target.value})}/></Field><label className="operation-reason">Motivo obligatorio<textarea required rows={3} value={priceDraft.reason} onChange={event=>setPriceDraft({...priceDraft,reason:event.target.value})} placeholder="Ej. Ajuste comercial autorizado"/></label><div className="price-management__actions"><Button disabled={saving} onClick={()=>setPriceDraft(null)}>Cancelar</Button><Button type="submit" variant="primary" loading={saving} disabled={!(Number(priceDraft.amount)>0)||!priceDraft.reason.trim()}>Registrar vigencia</Button></div></form>}</Drawer>
  </section>;
}
