"use client";

import { FileUp, Pencil, Plus, RefreshCw } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { DataPagination, DataRefreshStatus, DataState, DataToolbar, InteractiveTableRow, Table } from "@/app/components/ui/data";
import { Badge, Button, Drawer, Field, Input, Select, Tabs, useToast } from "@/app/components/ui/primitives";
import { OperationIdempotencyKeys } from "@/app/lib/operation-idempotency";
import { presentImportedSourceText } from "@/app/lib/presentation-text";
import { getSupabaseClient } from "@/app/lib/supabase";

const PAGE_SIZE=50;
type PriceList={id:string;internal_code:string;external_code:string|null;name:string;currency_code:string;is_active:boolean;is_default:boolean;source:string;updated_at:string;current_price_count:number};
type PriceProduct={product_id:string;internal_sku:string;name:string;unit:string|null;is_active:boolean;amount:number|null;tax_rate:number|null;tax_amount:number|null;total_amount:number|null;valid_from:string|null;valid_to:string|null;next_amount:number|null;next_valid_from:string|null};
type Location={id:string;name:string;external_code:string;default_price_list_id:string|null};
type ListDraft={id:string|null;internalCode:string;name:string;currencyCode:string;active:boolean;isDefault:boolean;updatedAt:string|null;externalCode:string|null};
type PriceDraft={product:PriceProduct;finalAmount:string;effectiveFrom:string};
const blankList=(isFirst:boolean):ListDraft=>({id:null,internalCode:"",name:"",currencyCode:"MXN",active:true,isDefault:isFirst,updatedAt:null,externalCode:null});
function codeFromName(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").slice(0,80).toUpperCase();}
function message(error:{message?:string}|null,fallback:string){return presentImportedSourceText(error?.message||fallback);}
function money(value:number|null,currency:string){return value==null?"—":new Intl.NumberFormat("es-MX",{style:"currency",currency,minimumFractionDigits:2}).format(value);}
function date(value:string|null){return value?new Intl.DateTimeFormat("es-MX",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";}
function PriceSectionHeading({title,description,action}:{title:string;description:string;action?:ReactNode}){return <header className="price-management__section-heading"><div><h3>{title}</h3><p>{description}</p></div>{action}</header>;}

export function PriceCatalogManagement({companyId,locations,onAssignLocation,onChanged}:{companyId:string;locations:Location[];onAssignLocation:(location?:Location)=>void;onChanged:()=>Promise<void>}){
  const {toast}=useToast();const idempotency=useRef(new OperationIdempotencyKeys()).current;
  const [section,setSection]=useState("lists");const [lists,setLists]=useState<PriceList[]>([]);const [selectedListId,setSelectedListId]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
  const [listDraft,setListDraft]=useState<ListDraft|null>(null);const [priceDraft,setPriceDraft]=useState<PriceDraft|null>(null);const [saving,setSaving]=useState(false);
  const [products,setProducts]=useState<PriceProduct[]>([]);const [productLoading,setProductLoading]=useState(false);const [productError,setProductError]=useState<string|null>(null);const [query,setQuery]=useState("");const [debouncedQuery,setDebouncedQuery]=useState("");const [page,setPage]=useState(1);const [total,setTotal]=useState(0);
  const selectedList=lists.find(item=>item.id===selectedListId)??null;
  const loadLists=useCallback(async()=>{setLoading(true);setError(null);const {data,error:loadError}=await getSupabaseClient().rpc("list_price_lists_admin",{p_company_id:companyId});const next=(data??[]) as PriceList[];setLists(next);setSelectedListId(current=>next.some(item=>item.id===current)?current:(next.find(item=>item.is_default&&item.is_active)??next.find(item=>item.is_active)??next[0])?.id??"");setError(loadError?message(loadError,"No se pudieron cargar las listas."):null);setLoading(false);},[companyId]);
  useEffect(()=>{void Promise.resolve().then(loadLists);},[loadLists]);
  useEffect(()=>{const timer=window.setTimeout(()=>{setDebouncedQuery(query.trim());setPage(1);},280);return()=>window.clearTimeout(timer);},[query]);
  const loadProducts=useCallback(async()=>{if(!selectedListId){setProducts([]);setTotal(0);return;}setProductLoading(true);setProductError(null);const {data,error:loadError}=await getSupabaseClient().rpc("search_price_list_products",{p_company_id:companyId,p_price_list_id:selectedListId,p_query:debouncedQuery||null,p_page:page,p_page_size:PAGE_SIZE});const result=data as {items?:PriceProduct[];total?:number}|null;setProducts(result?.items??[]);setTotal(result?.total??0);setProductError(loadError?message(loadError,"No se pudieron cargar los productos."):null);setProductLoading(false);},[companyId,debouncedQuery,page,selectedListId]);
  useEffect(()=>{if(section==="prices")void Promise.resolve().then(loadProducts);},[loadProducts,section]);
  async function refreshAll(){await Promise.all([loadLists(),section==="prices"?loadProducts():Promise.resolve()]);}
  function editList(list?:PriceList){setListDraft(list?{id:list.id,internalCode:list.internal_code,name:list.name,currencyCode:list.currency_code,active:list.is_active,isDefault:list.is_default,updatedAt:list.updated_at,externalCode:list.external_code}:blankList(lists.length===0));}
  function editPrice(product:PriceProduct){setPriceDraft({product,finalAmount:product.total_amount==null?"":String(product.total_amount),effectiveFrom:""});}
  async function saveList(event:FormEvent){event.preventDefault();if(!listDraft)return;const clean={...listDraft,internalCode:(listDraft.internalCode.trim()||codeFromName(listDraft.name)).toUpperCase(),name:listDraft.name.trim(),currencyCode:listDraft.currencyCode.trim().toUpperCase()};if(!clean.internalCode||!clean.name||clean.currencyCode.length!==3)return;const reason=clean.id?"Actualización de lista de precios":"Alta de lista de precios";setSaving(true);const fingerprint=JSON.stringify(clean);const {error:saveError}=await getSupabaseClient().rpc("save_price_list",{p_company_id:companyId,p_price_list_id:clean.id,p_internal_code:clean.internalCode,p_name:clean.name,p_currency_code:clean.currencyCode,p_is_active:clean.active,p_is_default:clean.isDefault,p_reason:reason,p_expected_updated_at:clean.updatedAt,p_client_request_id:idempotency.get("save-price-list",fingerprint)});if(saveError)toast({title:"No se pudo guardar la lista",description:message(saveError,"Verifica los datos."),tone:"error"});else{idempotency.clear("save-price-list");setListDraft(null);await loadLists();await onChanged();toast({title:clean.id?"Lista actualizada":"Lista creada",description:clean.isDefault?"Se usará como lista predeterminada.":"Ya puedes agregar precios.",tone:"success"});}setSaving(false);}
  async function savePrice(event:FormEvent){event.preventDefault();if(!priceDraft||!selectedList||priceDraft.product.tax_rate==null)return;const finalAmount=Number(priceDraft.finalAmount);if(!(finalAmount>0))return;const amount=finalAmount/(1+priceDraft.product.tax_rate);const reason=priceDraft.product.amount==null?"Alta manual de precio":"Actualización manual de precio";setSaving(true);const effective=priceDraft.effectiveFrom?new Date(priceDraft.effectiveFrom).toISOString():null;const fingerprint=JSON.stringify({list:selectedList.id,product:priceDraft.product.product_id,amount,effective});const {error:saveError}=await getSupabaseClient().rpc("save_product_price",{p_company_id:companyId,p_price_list_id:selectedList.id,p_product_id:priceDraft.product.product_id,p_amount:amount,p_effective_from:effective,p_reason:reason,p_client_request_id:idempotency.get("save-product-price",fingerprint)});if(saveError)toast({title:"No se pudo guardar el precio",description:message(saveError,"Verifica el importe y la fecha."),tone:"error"});else{idempotency.clear("save-product-price");setPriceDraft(null);await Promise.all([loadProducts(),loadLists()]);toast({title:"Precio guardado",description:effective?"Quedó programado para la fecha indicada.":"Ya está vigente para ventas nuevas.",tone:"success"});}setSaving(false);}
  const activeLists=lists.filter(item=>item.is_active);
  return <section className="settings-resource price-management">
    <header className="price-management__heading"><div><h2>Listas y precios</h2><p>Define cuánto cuesta cada producto y qué lista usa cada sucursal.</p></div><div className="price-management__heading-actions"><Link className="ui-button ui-button--secondary ui-button--sm" href="/satrapy/configuracion/importaciones"><FileUp size={14}/> Importar precios</Link><Button size="sm" variant="secondary" onClick={()=>void refreshAll()}><RefreshCw size={14}/> Actualizar</Button></div></header>
    <p className="price-management__flow-hint">Primero crea una lista, después agrega sus precios y al final asígnala a las sucursales.</p>
    <Tabs value={section} onValueChange={value=>setSection(value)} items={[{value:"lists",label:`Listas (${lists.length})`},{value:"prices",label:"Precios de productos",disabled:!lists.length},{value:"locations",label:`Asignación a sucursales (${locations.length})`}]}/>
    {section==="lists"&&<div className="price-management__panel"><PriceSectionHeading title="Listas de precios" description="Crea una lista por estrategia comercial, por ejemplo Menudeo o Mayoreo." action={<Button size="sm" variant="primary" onClick={()=>editList()}><Plus size={14}/> Crear lista</Button>}/><DataState loading={loading} error={error} hasData={lists.length} emptyTitle="Aún no hay listas de precios" empty="Crea la primera lista; quedará predeterminada y después podrás agregar precios." emptyAction={<Button size="sm" variant="primary" onClick={()=>editList()}><Plus size={14}/> Crear primera lista</Button>} errorAction={<Button size="sm" onClick={()=>void loadLists()}>Reintentar</Button>}><Table className="price-management__table"><thead><tr><th>Lista</th><th>Moneda</th><th>Productos con precio</th><th>Estado</th><th>Uso</th><th/></tr></thead><tbody>{lists.map(list=><tr key={list.id}><td><strong>{list.name}</strong><small className="mono">{list.internal_code}{list.external_code&&list.external_code!==list.internal_code?` · origen ${list.external_code}`:""}</small></td><td><Badge tone="info">{list.currency_code}</Badge></td><td>{list.current_price_count.toLocaleString("es-MX")}</td><td><Badge tone={list.is_active?"success":"neutral"}>{list.is_active?"Activa":"Inactiva"}</Badge></td><td>{list.is_default?<Badge tone="primary">Predeterminada</Badge>:"—"}</td><td className="settings-row-actions"><Button size="sm" variant="ghost" onClick={()=>editList(list)}><Pencil size={14}/> Editar</Button></td></tr>)}</tbody></Table></DataState></div>}
    {section==="prices"&&<div className="price-management__panel"><PriceSectionHeading title="Precios de productos" description="Elige una lista y captura el precio final de cada producto."/><div className="price-management__price-context"><Field label="Lista que quieres editar"><Select ariaLabel="Lista para administrar precios" value={selectedListId} onValueChange={value=>{setSelectedListId(value);setPage(1);}} options={lists.map(list=>({value:list.id,label:`${list.name} · ${list.currency_code}${list.is_active?"":" · inactiva"}`}))}/></Field>{selectedList&&!selectedList.is_active&&<Badge tone="warning">Activa la lista para cambiar precios</Badge>}</div><DataToolbar search={query} onSearchChange={setQuery} placeholder="Buscar producto por nombre, código o código de barras" results={total}/><DataRefreshStatus loading={productLoading} hasData={products.length}/><DataState loading={productLoading&&!products.length} error={productError} hasData={products.length} empty="No hay productos que coincidan con esta búsqueda." errorAction={<Button size="sm" onClick={()=>void loadProducts()}>Reintentar</Button>}><Table className="price-management__table"><thead><tr><th>Producto</th><th>Unidad</th><th>Precio final</th><th>IVA</th><th>Precio sin IVA</th><th>Vigente desde</th><th>Próximo cambio</th><th/></tr></thead><tbody>{products.map(product=><InteractiveTableRow key={product.product_id} disabled={!selectedList?.is_active} label={`${product.amount==null?"Agregar":"Cambiar"} precio de ${product.name}`} onActivate={()=>editPrice(product)}><td><strong>{product.name}</strong><small className="mono">{product.internal_sku}</small></td><td>{product.unit??"—"}</td><td><strong>{money(product.total_amount,selectedList?.currency_code??"MXN")}</strong></td><td>{product.tax_rate==null?<Badge tone="warning">Falta configurar</Badge>:<>{(product.tax_rate*100).toLocaleString("es-MX")}%</>}</td><td>{money(product.amount,selectedList?.currency_code??"MXN")}</td><td>{date(product.valid_from)}</td><td>{product.next_valid_from?<><strong>{money(product.next_amount==null||product.tax_rate==null?product.next_amount:product.next_amount*(1+product.tax_rate),selectedList?.currency_code??"MXN")}</strong><small>{date(product.next_valid_from)}</small></>:"—"}</td><td className="settings-row-actions">{selectedList?.is_active&&<Button size="sm" variant="ghost" onClick={()=>editPrice(product)}>{product.amount==null?<Plus size={14}/>:<Pencil size={14}/>} {product.amount==null?"Agregar precio":"Cambiar precio"}</Button>}</td></InteractiveTableRow>)}</tbody></Table></DataState><DataPagination page={page} total={total} pageSize={PAGE_SIZE} onChange={setPage} label="productos"/></div>}
    {section==="locations"&&<div className="price-management__panel"><PriceSectionHeading title="Lista por sucursal" description="La lista determina los precios de ventas nuevas. No cambia productos, existencias ni ventas anteriores." action={activeLists.length>0?<Button size="sm" variant="primary" onClick={()=>onAssignLocation()}><Plus size={14}/> Asignar lista</Button>:undefined}/>{activeLists.length===0?<div className="price-management__empty-note">Crea y activa una lista antes de asignarla a una sucursal.</div>:<Table className="price-management__table"><thead><tr><th>Sucursal</th><th>Lista asignada</th><th/></tr></thead><tbody>{locations.map(location=>{const list=lists.find(item=>item.id===location.default_price_list_id);return <tr key={location.id}><td><strong>{location.name}</strong><small className="mono">{location.external_code}</small></td><td>{list?<><strong>{list.name}</strong><small>{list.currency_code}</small></>:<Badge tone="warning">Usa la predeterminada</Badge>}</td><td className="settings-row-actions"><Button size="sm" variant="ghost" onClick={()=>onAssignLocation(location)}><Pencil size={14}/> {list?"Cambiar":"Asignar"}</Button></td></tr>})}</tbody></Table>}</div>}
    <Drawer open={Boolean(listDraft)} onOpenChange={open=>{if(!open&&!saving)setListDraft(null);}} title={listDraft?.id?"Editar lista de precios":"Crear lista de precios"} className="price-management__drawer">{listDraft&&<form className="sales-form" onSubmit={saveList}><p className="settings-drawer-intro">Sólo necesitas un nombre y la moneda. Podrás agregar precios después.</p>{listDraft.externalCode&&<p className="price-management__source">Referencia de importación: <strong>{listDraft.externalCode}</strong></p>}<Field label="Nombre de la lista"><Input required autoFocus maxLength={160} value={listDraft.name} onChange={event=>setListDraft({...listDraft,name:event.target.value})} placeholder="Ej. Menudeo"/></Field><Field label="Moneda" hint="Código de tres letras, por ejemplo MXN o USD."><Input required maxLength={3} value={listDraft.currencyCode} onChange={event=>setListDraft({...listDraft,currencyCode:event.target.value.replace(/[^a-z]/gi,"").toUpperCase()})}/></Field><details className="price-management__advanced" open={Boolean(listDraft.id)}><summary>Opciones avanzadas</summary><Field label="Código interno" hint="Si lo dejas vacío, se genera a partir del nombre."><Input maxLength={80} value={listDraft.internalCode} onChange={event=>setListDraft({...listDraft,internalCode:event.target.value.toUpperCase()})} placeholder={codeFromName(listDraft.name)||"MENUDEO"}/></Field><label className="sales-checkbox"><input type="checkbox" checked={listDraft.active} onChange={event=>setListDraft({...listDraft,active:event.target.checked,isDefault:event.target.checked?listDraft.isDefault:false})}/> Lista activa</label><label className="sales-checkbox"><input type="checkbox" disabled={!listDraft.active} checked={listDraft.isDefault} onChange={event=>setListDraft({...listDraft,isDefault:event.target.checked})}/> Usar como predeterminada</label></details><div className="price-management__actions"><Button disabled={saving} onClick={()=>setListDraft(null)}>Cancelar</Button><Button type="submit" variant="primary" loading={saving} disabled={!listDraft.name.trim()||listDraft.currencyCode.length!==3}>Guardar lista</Button></div></form>}</Drawer>
    <Drawer open={Boolean(priceDraft)} onOpenChange={open=>{if(!open&&!saving)setPriceDraft(null);}} title={priceDraft?.product.amount==null?"Agregar precio":"Cambiar precio"} className="price-management__drawer">{priceDraft&&selectedList&&<form className="sales-form" onSubmit={savePrice}><div className="price-management__product"><strong>{priceDraft.product.name}</strong><small>{priceDraft.product.internal_sku} · {selectedList.name}</small></div>{priceDraft.product.tax_rate==null?<div className="price-management__tax-warning" role="status"><div><strong>Primero configura el IVA</strong><p>El IVA pertenece al producto y se reutiliza en todas sus listas de precios.</p></div><Link href="/satrapy/inventario/productos">Abrir productos</Link></div>:<><Field label={`Precio final (${selectedList.currency_code})`} hint="Captura el precio que verá y pagará el cliente."><Input required autoFocus type="number" min="0.01" step="0.01" inputMode="decimal" value={priceDraft.finalAmount} onChange={event=>setPriceDraft({...priceDraft,finalAmount:event.target.value})}/></Field><div className="price-management__price-summary" aria-label="Desglose del precio"><span>Precio sin IVA<strong>{money((Number(priceDraft.finalAmount||0)||0)/(1+priceDraft.product.tax_rate)||null,selectedList.currency_code)}</strong></span><span>IVA {(priceDraft.product.tax_rate*100).toLocaleString("es-MX")}%<strong>{money((Number(priceDraft.finalAmount||0)||0)-((Number(priceDraft.finalAmount||0)||0)/(1+priceDraft.product.tax_rate))||null,selectedList.currency_code)}</strong></span><span>Precio final<strong>{money(Number(priceDraft.finalAmount||0)||null,selectedList.currency_code)}</strong></span></div><details className="price-management__advanced"><summary>Programar para otra fecha</summary><Field label="Inicio del nuevo precio" hint="Si no eliges fecha, se aplica al guardar."><Input type="datetime-local" aria-label="Inicio del nuevo precio" value={priceDraft.effectiveFrom} onChange={event=>setPriceDraft({...priceDraft,effectiveFrom:event.target.value})}/></Field></details></>}<div className="price-management__actions"><Button disabled={saving} onClick={()=>setPriceDraft(null)}>Cancelar</Button><Button type="submit" variant="primary" loading={saving} disabled={priceDraft.product.tax_rate==null||!(Number(priceDraft.finalAmount)>0)}>Guardar precio</Button></div></form>}</Drawer>
  </section>;
}
