"use client";

import { CircleAlert, Plus, RotateCcw } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { DataPagination, DataRefreshStatus, DataState, DataToolbar, InteractiveTableRow, PagedCollection, Table } from "@/app/components/ui/data";
import { Badge, Button, Drawer, Field, Input, Modal, Select, useToast } from "@/app/components/ui/primitives";
import { OperationIdempotencyKeys } from "@/app/lib/operation-idempotency";
import { getSupabaseClient } from "@/app/lib/supabase";

type ReceiptStatus="draft"|"confirmed"|"reversed";
type ReceiptRow={id:string;folio:string;status:ReceiptStatus;receipt_date:string;document_reference:string|null;purchase_order_id:string;purchase_order_folio:string;fulfillment_status:string;supplier_name:string;location_name:string;updated_at:string};
type OrderRow={id:string;folio:string;supplier_name:string;expected_date:string|null;total:number;currency_code:string;fulfillment_status?:string};
type Location={id:string;name:string;external_code:string};
type LotSuggestion={lot_code:string;expiration_date:string};
type ReceiptLot={id?:string;lot_code:string;expiration_date:string;quantity:number};
type LotDraft={lotCode:string;expirationDate:string;quantity:string};
type ReceivableLine={id:string;line_number:number;product_id:string|null;description:string;unit:string|null;ordered_quantity:number;previously_received:number;pending_quantity:number;unit_cost:number|null;lot_controlled:boolean;lot_suggestions:LotSuggestion[]};
 type OrderCandidate={purchase_order_id:string;folio:string;status:string;fulfillment_status:string;origin:string;inherited_location_id:string|null;inherited_location_name:string|null;inherited_location_code:string|null;historical_receipt_gap:boolean;historical_receipt_gap_note:string|null;lines:ReceivableLine[]};
type Detail=ReceiptRow&{notes:string|null;confirmed_at:string|null;reversed_at:string|null;reversal_reason:string|null;purchase_order:{folio:string;fulfillment_status:string;origin:string};supplier:{code:string;display_name:string};location:{code:string;name:string};lines:Array<ReceivableLine&{current_quantity:number;product_code:string;product_name:string;line_cost:number|null;lots:ReceiptLot[]}>;movements:Array<{id:string;movement_type:string;quantity_delta:number;balance_after:number;occurred_at:string}>};
type Draft={receiptId?:string;orderId:string;locationId:string;receiptDate:string;documentReference:string;notes:string;updatedAt?:string;quantities:Record<string,string>;lots:Record<string,LotDraft[]>};

const PAGE_SIZE=25;
const today=()=>new Date().toISOString().slice(0,10);

export function PurchaseReceiptsView({companyId,permissions}:{companyId:string;permissions:string[]}){
  const {toast}=useToast();const keys=useRef(new OperationIdempotencyKeys());
  const [rows,setRows]=useState<ReceiptRow[]>([]);const [total,setTotal]=useState(0);const [page,setPage]=useState(1);const [query,setQuery]=useState("");const [status,setStatus]=useState("all");const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
  const [orders,setOrders]=useState<OrderRow[]>([]);const [orderQuery,setOrderQuery]=useState("");const [orderTotal,setOrderTotal]=useState(0);const [orderSearching,setOrderSearching]=useState(false);const [orderPickerOpen,setOrderPickerOpen]=useState(false);const [locations,setLocations]=useState<Location[]>([]);const [candidate,setCandidate]=useState<OrderCandidate|null>(null);const [draft,setDraft]=useState<Draft|null>(null);const [detail,setDetail]=useState<Detail|null>(null);const [busy,setBusy]=useState(false);const [reverseReason,setReverseReason]=useState<string|null>(null);
  const draftOpen=draft!==null;
  const canDraft=permissions.includes("manage_purchase_receipt_drafts");const canConfirm=permissions.includes("confirm_purchase_receipts");const canReverse=permissions.includes("reverse_purchase_receipts");const canCost=permissions.includes("view_costs");
  const quantityOverflow=candidate?.lines.find(line=>Number(draft?.quantities[line.id]??0)>Number(line.pending_quantity))??null;
  const load=useCallback(async()=>{setLoading(true);setError(null);const {data,error:rpcError}=await getSupabaseClient().rpc("search_purchase_receipts",{p_company_id:companyId,p_query:query||null,p_status:status==="all"?null:status,p_location_id:null,p_supplier_id:null,p_date_from:null,p_date_to:null,p_page:page,p_page_size:PAGE_SIZE});const result=data as {items?:ReceiptRow[];pagination?:{total:number}}|null;if(!rpcError){setRows(result?.items??[]);setTotal(result?.pagination?.total??0);}setError(rpcError?"No se pudieron cargar las recepciones.":null);setLoading(false);},[companyId,page,query,status]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),200);return()=>clearTimeout(timer);},[load]);
  useEffect(()=>{if(!draftOpen)return;void getSupabaseClient().from("locations").select("id,name,external_code").eq("company_id",companyId).eq("is_active",true).order("name").then(({data})=>setLocations((data??[]) as Location[]));},[companyId,draftOpen]);
  useEffect(()=>{if(!draftOpen)return;const timer=window.setTimeout(async()=>{setOrderSearching(true);const {data,error:rpcError}=await getSupabaseClient().rpc("search_receivable_purchase_order_options",{p_company_id:companyId,p_query:orderQuery.trim()||null,p_limit:30});const result=data as {items?:OrderRow[]}|null;if(!rpcError){const items=result?.items??[];setOrders(items);setOrderTotal(items.length);}setOrderSearching(false);},200);return()=>window.clearTimeout(timer);},[companyId,draftOpen,orderQuery]);
  async function chooseOrder(orderId:string){if(!draft)return;setDraft(current=>current?{...current,orderId,locationId:"",quantities:{},lots:{}}:current);setCandidate(null);if(!orderId)return;const {data,error:rpcError}=await getSupabaseClient().rpc("get_receivable_purchase_order",{p_company_id:companyId,p_purchase_order_id:orderId});if(rpcError){toast({title:"No se pudo preparar la recepción",description:rpcError.message,tone:"error"});return;}const nextCandidate=data as OrderCandidate;setCandidate(nextCandidate);setDraft(current=>current?.orderId===orderId?{...current,locationId:nextCandidate.inherited_location_id??""}:current);}
  async function openDetail(id:string){const {data,error:rpcError}=await getSupabaseClient().rpc("get_purchase_receipt_detail",{p_company_id:companyId,p_receipt_id:id});if(rpcError)toast({title:"No se abrió la recepción",description:rpcError.message,tone:"error"});else setDetail(data as Detail);}
  function openNew(){setCandidate(null);setOrderQuery("");setOrders([]);setOrderTotal(0);setDraft({orderId:"",locationId:"",receiptDate:today(),documentReference:"",notes:"",quantities:{},lots:{}});}
  async function saveDraft(){
    if(!draft||!draft.orderId||!draft.locationId||quantityOverflow||!candidate)return;
    const lines=Object.entries(draft.quantities).filter(([,quantity])=>Number(quantity)>0).map(([purchase_order_line_id,quantity])=>{
      const line=candidate.lines.find(item=>item.id===purchase_order_line_id);
      const lots=(draft.lots[purchase_order_line_id]??[]).map(lot=>({lot_code:lot.lotCode.trim(),expiration_date:lot.expirationDate,quantity:Number(lot.quantity)}));
      return {purchase_order_line_id,quantity:Number(quantity),...(line?.lot_controlled?{lots}:{})};
    });
    if(!lines.length){toast({title:"Captura una cantidad",description:"Recibe al menos una partida sin superar su pendiente.",tone:"info"});return;}
    const invalidLotLine=lines.find(item=>{const line=candidate.lines.find(candidateLine=>candidateLine.id===item.purchase_order_line_id);if(!line?.lot_controlled)return false;const lots=(item.lots??[]);return !lots.length||lots.some(lot=>!lot.lot_code||!lot.expiration_date||!Number.isFinite(lot.quantity)||lot.quantity<=0)||Math.abs(lots.reduce((total,lot)=>total+lot.quantity,0)-item.quantity)>0.000001;});
    if(invalidLotLine){toast({title:"Completa los lotes",description:"Cada producto con control de lote necesita código, caducidad y cantidades que sumen lo recibido.",tone:"info"});return;}
    setBusy(true);const fingerprint=JSON.stringify({orderId:draft.orderId,locationId:draft.locationId,date:draft.receiptDate,lines});const {data,error:rpcError}=await getSupabaseClient().rpc("save_purchase_receipt",{p_company_id:companyId,p_receipt_id:draft.receiptId??null,p_purchase_order_id:draft.orderId,p_location_id:draft.locationId,p_receipt_date:draft.receiptDate,p_document_reference:draft.documentReference||null,p_notes:draft.notes||null,p_lines:lines,p_client_request_id:keys.current.get("receipt-save",fingerprint),p_expected_updated_at:draft.updatedAt??null});setBusy(false);if(rpcError){toast({title:"No se guardó la recepción",description:rpcError.message,tone:"error"});return;}keys.current.clear("receipt-save");setDraft(null);toast({title:"Borrador guardado",description:"Inventario y costo permanecen sin cambios hasta confirmar.",tone:"success"});await load();await openDetail((data as {id:string}).id);
  }
  async function confirm(){if(!detail)return;setBusy(true);const {data,error:rpcError}=await getSupabaseClient().rpc("confirm_purchase_receipt",{p_company_id:companyId,p_receipt_id:detail.id,p_client_request_id:keys.current.get("receipt-confirm",detail.id)});setBusy(false);if(rpcError){toast({title:"No se confirmó la recepción",description:rpcError.message,tone:"error"});return;}keys.current.clear("receipt-confirm");toast({title:"Recepción confirmada",description:`Inventario, costo y orden de compra actualizados una sola vez · ${(data as {fulfillment_status:string}).fulfillment_status}.`,tone:"success"});await load();await openDetail(detail.id);}
  async function reverse(){if(!detail||!reverseReason?.trim())return;setBusy(true);const fingerprint=`${detail.id}:${reverseReason.trim()}`;const {error:rpcError}=await getSupabaseClient().rpc("reverse_purchase_receipt",{p_company_id:companyId,p_receipt_id:detail.id,p_reason:reverseReason.trim(),p_client_request_id:keys.current.get("receipt-reverse",fingerprint)});setBusy(false);if(rpcError){toast({title:"No se anuló la recepción",description:rpcError.message,tone:"error"});return;}keys.current.clear("receipt-reverse");setReverseReason(null);toast({title:"Recepción anulada",description:"Se retiró del inventario lo agregado por esta recepción y se conservó el historial.",tone:"success"});await load();await openDetail(detail.id);}
  return <div className="content-frame">
    <div className="page-heading"><div><span className="eyebrow">Compras</span><h1>Recepciones</h1><p>Recibe únicamente contra órdenes de compra aprobadas. El inventario y costo cambian al confirmar, nunca al guardar el borrador.</p></div>{canDraft&&<Button variant="primary" onClick={openNew}><Plus size={16}/> Nueva recepción</Button>}</div>
    <DataToolbar search={query} onSearchChange={value=>{setQuery(value);setPage(1);}} placeholder="Recepción, orden de compra, proveedor o documento" results={total} activeFilters={status==="all"?0:1} onClear={()=>setStatus("all")} filters={<Select ariaLabel="Estado" value={status} onValueChange={value=>{setStatus(value);setPage(1);}} options={[{value:"all",label:"Todos"},{value:"draft",label:"Borrador"},{value:"confirmed",label:"Confirmada"},{value:"reversed",label:"Anulada"}]}/>}/>
    <DataRefreshStatus loading={loading} hasData={rows.length}/><DataState loading={loading&&rows.length===0} error={error} hasData={rows.length} emptyTitle={query||status!=="all"?"No encontramos recepciones.":"Aún no hay recepciones."} empty={query||status!=="all"?"Cambia o limpia los filtros para ampliar la búsqueda.":"Crea la primera recepción desde una orden aprobada."} errorAction={<Button size="sm" onClick={()=>void load()}>Reintentar</Button>}><Table><thead><tr><th>Recepción</th><th>Orden de compra / proveedor</th><th>Ubicación</th><th>Fecha</th><th>Estado</th><th>Cumplimiento de orden de compra</th></tr></thead><tbody>{rows.map(row=><InteractiveTableRow key={row.id} className="purchase-order-row" label={`Abrir recepción ${row.folio}`} onActivate={()=>void openDetail(row.id)}><td><strong className="mono">{row.folio}</strong><small>{row.document_reference??"Sin referencia"}</small></td><td><strong>{row.purchase_order_folio}</strong><small>{row.supplier_name}</small></td><td>{row.location_name}</td><td>{formatDate(row.receipt_date)}</td><td><ReceiptBadge status={row.status}/></td><td>{fulfillmentLabel(row.fulfillment_status)}</td></InteractiveTableRow>)}</tbody></Table><DataPagination page={page} total={total} pageSize={PAGE_SIZE} onChange={setPage} showTotal={false}/></DataState>
    <Drawer open={Boolean(draft)} onOpenChange={open=>!open&&!busy&&setDraft(null)} title="Nueva recepción" className="purchase-order-drawer">
      {draft&&<form noValidate className="purchase-order-form" onSubmit={event=>{event.preventDefault();void saveDraft();}}>
        <div className="purchase-order-grid">
          <Field label="Orden de compra aprobada" hint={orderSearching?"Buscando…":`${orderTotal} órdenes de compra disponibles; busca por folio, proveedor o clave.`}>
            <div className="purchase-order-supplier-picker"><Input role="combobox" aria-label="Orden de compra aprobada" aria-expanded={orderPickerOpen} autoComplete="off" value={orderQuery} placeholder="Buscar orden de compra aprobada" onFocus={()=>setOrderPickerOpen(true)} onBlur={()=>window.setTimeout(()=>setOrderPickerOpen(false),120)} onChange={event=>{setOrderQuery(event.target.value);setOrderPickerOpen(true);if(draft.orderId){setDraft({...draft,orderId:"",quantities:{},lots:{}});setCandidate(null);}}}/>{orderPickerOpen&&<div className="purchase-order-supplier-options" role="listbox">{orders.length?orders.map(order=><button type="button" role="option" aria-selected={draft.orderId===order.id} key={order.id} onMouseDown={event=>event.preventDefault()} onClick={()=>{setOrderQuery(`${order.folio} · ${order.supplier_name}`);setOrderPickerOpen(false);void chooseOrder(order.id);}}><strong>{order.folio}</strong><small>{order.supplier_name}</small><small>{`Entrega esperada: ${order.expected_date?formatDate(order.expected_date):"Sin fecha"} · Total: ${formatOrderTotal(order.total,order.currency_code)}`}</small></button>):!orderSearching&&<p>No se encontraron órdenes de compra disponibles.</p>}</div>}</div>
          </Field>
 <Field label="Almacén de recepción" hint={candidate?.inherited_location_id?"Heredado de la solicitud de compra.":"Las existencias se actualizarán en este almacén al confirmar."}><Select ariaLabel="Almacén de recepción" value={draft.locationId} disabled={Boolean(candidate?.inherited_location_id)} onValueChange={value=>setDraft({...draft,locationId:value})} options={[{value:"",label:"Selecciona dónde se recibirá la mercancía"},...(candidate?.inherited_location_id&&!locations.some(location=>location.id===candidate.inherited_location_id)?[{value:candidate.inherited_location_id,label:`${candidate.inherited_location_name} · ${candidate.inherited_location_code}`}]:[]),...locations.map(location=>({value:location.id,label:`${location.name} · ${location.external_code}`}))]}/></Field>
          <Field label="Almacén de recepción" hint={candidate?.inherited_location_id?"Heredado de la solicitud de compra.":"Las existencias se actualizarán en este almacén al confirmar."}><Select ariaLabel="Almacén de recepción" value={draft.locationId} disabled={Boolean(candidate?.inherited_location_id)} onValueChange={value=>setDraft({...draft,locationId:value})} options={[{value:"",label:"Selecciona dónde se recibirá la mercancía"},...(candidate?.inherited_location_id&&!locations.some(location=>location.id===candidate.inherited_location_id)?[{value:candidate.inherited_location_id,label:`${candidate.inherited_location_name} · ${candidate.inherited_location_code}`}]:[]),...locations.map(location=>({value:location.id,label:`${location.name} · ${location.external_code}`}))]}/></Field>
          <Field label="Fecha"><Input type="date" value={draft.receiptDate} onChange={event=>setDraft({...draft,receiptDate:event.target.value})}/></Field>
          <Field label="Referencia documental"><Input value={draft.documentReference} onChange={event=>setDraft({...draft,documentReference:event.target.value})}/></Field>
        </div>
        <Field label="Notas"><textarea rows={2} value={draft.notes} onChange={event=>setDraft({...draft,notes:event.target.value})}/></Field>
        {candidate&&<>
          <div className="receipt-evidence-gap">{candidate.historical_receipt_gap&&<Badge tone="warning">Brecha histórica visible</Badge>}<small>{candidate.historical_receipt_gap_note}</small></div>
          {candidate.lines.some(line=>line.lot_controlled)&&<p className="receipt-evidence-gap"><strong>Lotes requeridos:</strong> los productos marcados deben incluir lote, caducidad y cantidades que sumen la recepción. Las sugerencias son capturas previas, no existencias disponibles.</p>}
          <Table><thead><tr><th>Partida</th><th className="number-cell">Ordenada</th><th className="number-cell">Recibida</th><th className="number-cell">Pendiente</th><th className="number-cell">Actual</th>{canCost&&<th className="number-cell">Costo</th>}</tr></thead><tbody>{candidate.lines.map(line=>{
            const exceedsPending=Number(draft.quantities[line.id]??0)>Number(line.pending_quantity);
            const errorId=`receipt-quantity-error-${line.id}`;
            const hasQuantity=Number(draft.quantities[line.id]??0)>0;
            const lots=draft.lots[line.id]??[];
            const suggestionsId=`receipt-lot-suggestions-${line.id}`;
            return <tr key={line.id}>
              <td><strong>{line.description}</strong><small>{line.unit??"—"}</small>{line.lot_controlled&&hasQuantity&&<div className="receipt-lot-capture"><small><strong>Lotes y caducidad</strong></small><datalist id={suggestionsId}>{line.lot_suggestions.map(suggestion=><option key={`${suggestion.lot_code}-${suggestion.expiration_date}`} value={suggestion.lot_code}>{`Caduca ${formatDate(suggestion.expiration_date)}`}</option>)}</datalist>{lots.map((lot,index)=><div key={`${line.id}-${index}`} className="receipt-lot-capture__row"><Input aria-label={`Lote ${index+1} de ${line.description}`} list={suggestionsId} value={lot.lotCode} placeholder="Lote" onChange={event=>{const matching=line.lot_suggestions.find(suggestion=>suggestion.lot_code.toUpperCase()===event.target.value.trim().toUpperCase());const next=[...lots];next[index]={...lot,lotCode:event.target.value,expirationDate:lot.expirationDate||matching?.expiration_date||""};setDraft({...draft,lots:{...draft.lots,[line.id]:next}});}}/><Input aria-label={`Caducidad del lote ${index+1} de ${line.description}`} type="date" value={lot.expirationDate} onChange={event=>{const next=[...lots];next[index]={...lot,expirationDate:event.target.value};setDraft({...draft,lots:{...draft.lots,[line.id]:next}});}}/><Input aria-label={`Cantidad del lote ${index+1} de ${line.description}`} type="number" min="0" step="0.000001" value={lot.quantity} placeholder="Cantidad" onChange={event=>{const next=[...lots];next[index]={...lot,quantity:event.target.value};setDraft({...draft,lots:{...draft.lots,[line.id]:next}});}}/>{lots.length>1&&<Button type="button" size="sm" onClick={()=>setDraft({...draft,lots:{...draft.lots,[line.id]:lots.filter((_,lotIndex)=>lotIndex!==index)}})}>Quitar</Button>}</div>)}<Button type="button" size="sm" onClick={()=>setDraft({...draft,lots:{...draft.lots,[line.id]:[...lots,{lotCode:"",expirationDate:"",quantity:""}]}})}>Agregar lote</Button></div>}</td>
              <td className="number-cell">{number(line.ordered_quantity)}</td><td className="number-cell">{number(line.previously_received)}</td><td className="number-cell">{number(line.pending_quantity)}</td>
              <td className="number-cell"><div className="receipt-quantity-control"><Input aria-label={`Cantidad actual ${line.description}`} aria-invalid={exceedsPending} aria-describedby={exceedsPending?errorId:undefined} type="number" min="0" step="0.000001" value={draft.quantities[line.id]??""} onChange={event=>{const quantity=event.target.value;const nextLots=line.lot_controlled&&Number(quantity)>0&&!draft.lots[line.id]?[{lotCode:"",expirationDate:"",quantity}]:lots;setDraft({...draft,quantities:{...draft.quantities,[line.id]:quantity},lots:{...draft.lots,[line.id]:nextLots}});}}/>{exceedsPending&&<small id={errorId} className="receipt-quantity-error" role="alert"><CircleAlert size={14}/><span>La cantidad supera lo pendiente. Puedes recibir como máximo <strong>{number(line.pending_quantity)}</strong>.</span></small>}</div></td>
              {canCost&&<td className="number-cell">{line.unit_cost==null?"—":money(line.unit_cost)}</td>}
            </tr>;
          })}</tbody></Table>
        </>}
        <div className="purchase-order-actions"><Button type="button" onClick={()=>setDraft(null)}>Cancelar</Button><Button type="submit" variant="primary" loading={busy} disabled={!candidate||Boolean(quantityOverflow)}>Guardar borrador</Button></div>
      </form>}
    </Drawer>
    <Drawer open={Boolean(detail)} onOpenChange={open=>!open&&!busy&&setDetail(null)} title={detail?.folio??"Detalle"} className="purchase-order-detail-drawer">{detail&&<div className="purchase-order-detail"><header><div><ReceiptBadge status={detail.status}/><Badge>{fulfillmentLabel(detail.purchase_order.fulfillment_status)}</Badge></div><strong>{detail.purchase_order.folio}</strong></header><dl><div><dt>Proveedor</dt><dd>{detail.supplier.display_name} · {detail.supplier.code}</dd></div><div><dt>Ubicación</dt><dd>{detail.location.name} · {detail.location.code}</dd></div><div><dt>Fecha / documento</dt><dd>{formatDate(detail.receipt_date)} · {detail.document_reference??"—"}</dd></div></dl><PagedCollection items={detail.lines} resetKey={detail.id} label="partidas">{visibleLines=><Table><thead><tr><th>Producto</th><th className="number-cell">Ordenada</th><th className="number-cell">Previa</th><th className="number-cell">Actual</th><th className="number-cell">Pendiente</th>{canCost&&<th className="number-cell">Costo</th>}</tr></thead><tbody>{visibleLines.map(line=><tr key={line.id}><td><strong>{line.product_name}</strong><small>{line.product_code}</small>{line.lots.length>0&&<small>Lotes: {line.lots.map(lot=>`${lot.lot_code} · ${formatDate(lot.expiration_date)} · ${number(lot.quantity)}`).join(" | ")}</small>}</td><td className="number-cell">{number(line.ordered_quantity)}</td><td className="number-cell">{number(line.previously_received)}</td><td className="number-cell">{number(line.current_quantity)}</td><td className="number-cell">{number(line.pending_quantity)}</td>{canCost&&<td className="number-cell">{line.unit_cost==null?"—":money(line.unit_cost)}</td>}</tr>)}</tbody></Table>}</PagedCollection><section className="purchase-order-history"><h3>Movimientos de inventario</h3>{detail.movements.length?<PagedCollection items={detail.movements} resetKey={detail.id} label="movimientos">{visibleMovements=><>{visibleMovements.map(movement=><article key={movement.id}><span><strong>{movement.movement_type==="purchase_receipt"?"Entrada por recepción":"Salida por anulación de recepción"}</strong><small>{new Date(movement.occurred_at).toLocaleString("es-MX")}</small></span><p>{number(movement.quantity_delta)} · saldo {number(movement.balance_after)}</p></article>)}</>}</PagedCollection>:<p>Borrador: todavía no existen movimientos.</p>}</section>{detail.reversal_reason&&<p><strong>Motivo de anulación:</strong> {detail.reversal_reason}</p>}<div className="purchase-order-actions">{canConfirm&&detail.status==="draft"&&<Button variant="primary" loading={busy} onClick={()=>void confirm()}>Confirmar recepción</Button>}{canReverse&&detail.status==="confirmed"&&<Button variant="danger" onClick={()=>setReverseReason("")}><RotateCcw size={15}/> Anular recepción</Button>}</div></div>}</Drawer>
    <Modal open={reverseReason!==null} onOpenChange={open=>!open&&!busy&&setReverseReason(null)} eyebrow="Corrección auditada" title="Anular recepción confirmada" description="Se conservará el registro para auditoría y se retirarán del inventario las cantidades recibidas." footer={<><Button onClick={()=>setReverseReason(null)}>Cancelar</Button><Button variant="danger" loading={busy} disabled={!reverseReason?.trim()} onClick={()=>void reverse()}>Confirmar anulación</Button></>}>{reverseReason!==null&&<Field label="Motivo de anulación"><textarea rows={4} value={reverseReason} onChange={event=>setReverseReason(event.target.value)}/></Field>}</Modal>
  </div>;
}

function ReceiptBadge({status}:{status:ReceiptStatus}){return <Badge tone={status==="confirmed"?"success":status==="reversed"?"danger":"neutral"}>{status==="confirmed"?"Confirmada":status==="reversed"?"Anulada":"Borrador"}</Badge>;}
function fulfillmentLabel(value:string){return value==="fully_received"?"Totalmente recibida":value==="partially_received"?"Parcialmente recibida":"Pendiente";}
function formatDate(value:string){return new Date(`${value}T00:00:00`).toLocaleDateString("es-MX");}
function number(value:number){return Number(value).toLocaleString("es-MX",{maximumFractionDigits:6});}
function money(value:number){return new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(Number(value));}
function formatOrderTotal(value:number,currencyCode:string){return new Intl.NumberFormat("es-MX",{style:"currency",currency:currencyCode}).format(Number(value));}
