"use client";
/* eslint-disable @next/next/no-img-element -- La vista usa imágenes de Storage y actualiza el logotipo antes de guardar. */

import { Building2, FileText, ImagePlus, Palette, Save, X } from "lucide-react";
import { useCallback, useEffect, useRef, useState, type CSSProperties, type ChangeEvent, type FormEvent } from "react";
import { DataState } from "@/app/components/ui/data";
import { Button, Input, useToast } from "@/app/components/ui/primitives";
import { getSupabaseClient } from "@/app/lib/supabase";

type Branding = { display_name:string; legal_name:string|null; tax_id:string|null; fiscal_address:string|null; document_title:string; contact_line:string|null; header_message:string|null; footer_message:string; terms_and_conditions:string|null; website:string|null; accent_color:string; logo_path:string|null };
const colors=[{value:"#176F5E",label:"Verde bosque"},{value:"#245A8D",label:"Azul confianza"},{value:"#6B4EA0",label:"Violeta"},{value:"#9A4B35",label:"Terracota"},{value:"#8A6418",label:"Ocre"},{value:"#34423B",label:"Grafito"}];
function normalize(value:Partial<Branding>):Branding{return{display_name:value.display_name??"",legal_name:value.legal_name??null,tax_id:value.tax_id??null,fiscal_address:value.fiscal_address??null,document_title:value.document_title??"COTIZACIÓN",contact_line:value.contact_line??null,header_message:value.header_message??null,footer_message:value.footer_message??"Gracias por considerar nuestra propuesta.",terms_and_conditions:value.terms_and_conditions??null,website:value.website??null,accent_color:value.accent_color??"#176F5E",logo_path:value.logo_path??null};}
function publicLogoUrl(path:string|null){return path?getSupabaseClient().storage.from("ticket-branding-assets").getPublicUrl(path).data.publicUrl:null;}

function QuotePreview({branding}:{branding:Branding}){const logo=publicLogoUrl(branding.logo_path);return <aside className="quote-format-preview" aria-label="Vista previa del formato de cotización"><header><span>Vista previa</span><strong>A4</strong></header><article style={{"--quote-accent":branding.accent_color} as CSSProperties}><div className="quote-format-preview__head">{logo?<img src={logo} alt=""/>:<FileText size={26} aria-hidden="true"/>}<span><strong>{branding.display_name||"Nombre comercial"}</strong><small>{branding.legal_name||"Razón social"}</small><small>{branding.tax_id?`RFC ${branding.tax_id}`:"RFC por configurar"}</small></span><b>{branding.document_title}<small>COT-260822-AB12CD</small></b></div><div className="quote-format-preview__hero"><strong>Propuesta comercial</strong><span>Vigente hasta: 6 sep 2026 · MXN</span></div>{branding.header_message&&<p>{branding.header_message}</p>}<div className="quote-format-preview__client"><small>CLIENTE</small><strong>Cliente de ejemplo</strong><span>CLI-001 · Sucursal principal</span></div><div className="quote-format-preview__table"><b>Producto de ejemplo</b><span>2 × $125.00</span><strong>$250.00</strong><b>Insumo de muestra</b><span>1 × $80.00</span><strong>$80.00</strong></div><div className="quote-format-preview__total"><span>Total</span><strong>$330.00</strong></div>{branding.terms_and_conditions&&<p><b>Condiciones comerciales</b>{branding.terms_and_conditions}</p>}<footer>{branding.footer_message}{branding.website&&<small>{branding.website}</small>}</footer></article><p>La vista previa cambia mientras editas. Guarda para aplicarla a documentos nuevos.</p></aside>;}

export function QuoteBrandingSettings({companyId}:{companyId:string}){
  const {toast}=useToast();const fileInput=useRef<HTMLInputElement>(null);const [branding,setBranding]=useState<Branding|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [uploading,setUploading]=useState(false);const [error,setError]=useState<string|null>(null);
  const update=(patch:Partial<Branding>)=>setBranding(current=>current?{...current,...patch}:current);
  const load=useCallback(async()=>{setLoading(true);const {data,error:loadError}=await getSupabaseClient().rpc("get_quote_branding",{p_company_id:companyId});if(loadError){setError(loadError.message);setBranding(null);}else{setBranding(normalize((data??{}) as Partial<Branding>));setError(null);}setLoading(false);},[companyId]);
  useEffect(()=>{void Promise.resolve().then(load);},[load]);
  async function uploadLogo(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;if(!["image/png","image/jpeg"].includes(file.type)||file.size>2_097_152){toast({title:"Selecciona otro archivo",description:"Usa PNG o JPG de hasta 2 MB.",tone:"error"});return;}setUploading(true);const extension=file.type==="image/png"?"png":"jpg";const path=`${companyId}/quote-${crypto.randomUUID()}.${extension}`;const {error:uploadError}=await getSupabaseClient().storage.from("ticket-branding-assets").upload(path,file,{contentType:file.type,upsert:false});setUploading(false);if(uploadError)toast({title:"No se pudo cargar el logotipo",description:uploadError.message,tone:"error"});else{update({logo_path:path});toast({title:"Logotipo cargado",description:"Guarda el formato para aplicarlo.",tone:"success"});}}
  async function save(event:FormEvent){event.preventDefault();if(!branding)return;setSaving(true);const {data,error:saveError}=await getSupabaseClient().rpc("update_quote_branding",{p_company_id:companyId,p_display_name:branding.display_name,p_document_title:branding.document_title,p_contact_line:branding.contact_line,p_header_message:branding.header_message,p_footer_message:branding.footer_message,p_terms_and_conditions:branding.terms_and_conditions,p_website:branding.website,p_legal_name:branding.legal_name,p_tax_id:branding.tax_id,p_fiscal_address:branding.fiscal_address,p_accent_color:branding.accent_color,p_logo_path:branding.logo_path});setSaving(false);if(saveError)toast({title:"No se pudo guardar",description:saveError.message,tone:"error"});else{setBranding(normalize((data??{}) as Partial<Branding>));toast({title:"Formato actualizado",description:"Se aplicará a las cotizaciones nuevas.",tone:"success"});}}
  return <section className="ticket-branding-settings quote-branding-settings"><header><div><h2>Formato de cotización</h2><p>Define la identidad del documento que recibe el cliente. Las cotizaciones aprobadas conservan su formato.</p></div></header><DataState loading={loading} error={error} hasData={branding?1:0} empty="No se pudo cargar el formato." errorAction={<Button size="sm" onClick={()=>void load()}>Reintentar</Button>}>{branding&&<div className="ticket-branding-workspace"><form className="sales-form ticket-branding-form quote-branding-form" onSubmit={save}>
    <fieldset><legend><Building2 size={13} aria-hidden="true"/> Identidad</legend><label>Nombre comercial<Input required maxLength={120} value={branding.display_name} onChange={event=>update({display_name:event.target.value})}/></label><label>Razón social<Input maxLength={180} value={branding.legal_name??""} onChange={event=>update({legal_name:event.target.value||null})}/></label><div className="quote-branding-form__pair"><label>RFC<Input maxLength={13} value={branding.tax_id??""} onChange={event=>update({tax_id:event.target.value.toUpperCase()})} placeholder="XAXX010101000"/></label><label>Título del documento<Input required maxLength={60} value={branding.document_title} onChange={event=>update({document_title:event.target.value})}/></label></div><label>Domicilio fiscal<textarea maxLength={260} value={branding.fiscal_address??""} onChange={event=>update({fiscal_address:event.target.value||null})} placeholder="Calle, número, colonia, municipio, estado y C.P."/></label></fieldset>
    <fieldset><legend>Contacto y mensajes</legend><label>Contacto comercial<Input maxLength={180} value={branding.contact_line??""} onChange={event=>update({contact_line:event.target.value||null})} placeholder="Tel. 222 000 0000 · ventas@empresa.mx"/></label><label>Mensaje de presentación<textarea maxLength={300} value={branding.header_message??""} onChange={event=>update({header_message:event.target.value||null})} placeholder="Ponemos a su consideración la siguiente propuesta."/></label><label>Condiciones comerciales<textarea maxLength={600} value={branding.terms_and_conditions??""} onChange={event=>update({terms_and_conditions:event.target.value||null})} placeholder="Vigencia, pago, entrega y disponibilidad."/></label><label>Mensaje final<Input required maxLength={180} value={branding.footer_message} onChange={event=>update({footer_message:event.target.value})}/></label><label>Sitio web<Input maxLength={120} value={branding.website??""} onChange={event=>update({website:event.target.value||null})} placeholder="www.empresa.mx"/></label></fieldset>
    <fieldset className="quote-branding-presentation"><legend><Palette size={13} aria-hidden="true"/> Presentación</legend><div className="quote-branding-presentation__colors"><span className="quote-branding-form__label">Color principal</span><div className="quote-color-options" role="radiogroup" aria-label="Color principal de la cotización">{colors.map(color=><label key={color.value} title={color.label}><input type="radio" name="quote-color" value={color.value} checked={branding.accent_color===color.value} onChange={()=>update({accent_color:color.value})}/><span className="quote-color-options__swatch" style={{backgroundColor:color.value}} aria-hidden="true"/><b>{color.label}</b></label>)}</div></div><div className="quote-branding-presentation__logo"><div className="ticket-branding-logo"><div>{publicLogoUrl(branding.logo_path)?<img src={publicLogoUrl(branding.logo_path)??undefined} alt="Logotipo de la cotización"/>:<ImagePlus size={20} aria-hidden="true"/>}<span>{branding.logo_path?"Logotipo listo":"Sin logotipo"}</span></div><Button type="button" variant="secondary" loading={uploading} onClick={()=>fileInput.current?.click()}><ImagePlus size={15} aria-hidden="true"/>{branding.logo_path?"Reemplazar logotipo":"Cargar logotipo"}</Button>{branding.logo_path&&<Button type="button" variant="ghost" onClick={()=>update({logo_path:null})}><X size={15} aria-hidden="true"/>Quitar</Button>}<input ref={fileInput} type="file" accept="image/png,image/jpeg" onChange={event=>void uploadLogo(event)} hidden/></div><small>PNG o JPG de hasta 2 MB. Usa una imagen horizontal con fondo transparente.</small></div></fieldset>
    <footer className="quote-branding-form__actions"><Button type="submit" variant="primary" loading={saving} disabled={uploading}><Save size={16} aria-hidden="true"/>Guardar formato</Button></footer>
  </form><QuotePreview branding={branding}/></div>}</DataState></section>;
}
