"use client";

import { ChefHat, Plus, Search, Trash2 } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Badge, Button, Field, Input, Modal, Select, useToast } from "@/app/components/ui/primitives";
import { OperationIdempotencyKeys } from "@/app/lib/operation-idempotency";
import { getSupabaseClient } from "@/app/lib/supabase";

type ProductRef={id:string;name:string};
type Candidate={id:string;internal_sku:string;name:string;unit:string|null;is_inventory_tracked:boolean;recipe_kind:"dish"|"preparation"|null;usage_count:number};
type Line={productId:string;productName:string;productCode:string;quantity:string;unitCode:string;baseUnitCode:string;recipeKind:string|null};
type Version={id:string;version_number:number;status:string;yield_quantity:number;yield_unit_code:string;portion_count:number;waste_percent:number;components?:Array<{product_id:string;product_name:string;product_code:string;entered_quantity:number;entered_unit_code:string;base_unit_code:string;recipe_kind:string|null}>;cost?:{allowed:boolean;total_cost:number|null;cost_per_portion:number|null;currency_code:string;blockers:Array<{message:string}>}};
type Context={product:ProductRef&{code:string};recipe_id:string|null;draft:Version|null;active:Version|null;sale_price:number|null;currency_code:string};
const units=[{value:"mg",label:"mg"},{value:"g",label:"g"},{value:"kg",label:"kg"},{value:"ml",label:"ml"},{value:"l",label:"l"},{value:"piece",label:"pieza"}];
const unitCode=(value:string|null)=>{const normalized=(value??"").trim().toLowerCase();return normalized==="pza"||normalized==="pieza"?"piece":units.some(unit=>unit.value===normalized)?normalized:"piece";};
const money=(value:number|null|undefined,currency:string)=>value==null?"Pendiente":new Intl.NumberFormat("es-MX",{style:"currency",currency,maximumFractionDigits:2}).format(value);
const message=(error:{message?:string}|null,fallback:string)=>error?.message?.includes("schema cache")?"La función de recetas aún no está instalada en Supabase. Ejecuta las migraciones pendientes y vuelve a intentarlo.":error?.message?.replace(/^.*?error:\s*/i,"").trim()||fallback;

export function RecipeEditorModal({companyId,product,recipeKind="dish",open,onOpenChange,onCreateIngredient}:{companyId:string;product:ProductRef|null;recipeKind?:"dish"|"preparation";open:boolean;onOpenChange:(open:boolean)=>void;onCreateIngredient?:()=>void}){
 const {toast}=useToast();const keys=useRef(new OperationIdempotencyKeys()).current;
 const [context,setContext]=useState<Context|null>(null);const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const [activating,setActivating]=useState(false);
 const [yieldQuantity,setYieldQuantity]=useState("1");const [yieldUnit,setYieldUnit]=useState("piece");const [portions,setPortions]=useState("1");const [waste,setWaste]=useState("0");const [lines,setLines]=useState<Line[]>([]);
 const [query,setQuery]=useState("");const [candidates,setCandidates]=useState<Candidate[]>([]);const [searching,setSearching]=useState(false);const [formError,setFormError]=useState<string|null>(null);
 const hydrate=useCallback((next:Context)=>{const version=next.draft??next.active;setContext(next);setYieldQuantity(String(version?.yield_quantity??1));setYieldUnit(version?.yield_unit_code??"piece");setPortions(String(version?.portion_count??1));setWaste(String(version?.waste_percent??0));setLines((version?.components??[]).map(item=>({productId:item.product_id,productName:item.product_name,productCode:item.product_code,quantity:String(item.entered_quantity),unitCode:item.entered_unit_code,baseUnitCode:item.base_unit_code,recipeKind:item.recipe_kind})));},[]);
 const load=useCallback(async()=>{if(!product)return;setLoading(true);setFormError(null);const{data,error}=await getSupabaseClient().rpc("get_culinary_recipe_context",{p_company_id:companyId,p_product_id:product.id});setLoading(false);if(error){setFormError(message(error,"Actualiza e intenta abrir la receta nuevamente."));return;}hydrate(data as Context);},[companyId,hydrate,product]);
 useEffect(()=>{if(open&&product)void Promise.resolve().then(load);},[load,open,product]);
 useEffect(()=>{if(!open)return;const timer=window.setTimeout(async()=>{setSearching(true);const{data,error}=await getSupabaseClient().rpc("search_restaurant_recipe_components",{p_company_id:companyId,p_query:query.trim()||null,p_page:1,p_page_size:20});setSearching(false);if(!error)setCandidates(((data as {items?:Candidate[]}|null)?.items??[]).filter(item=>item.id!==product?.id&&!lines.some(line=>line.productId===item.id)));},250);return()=>window.clearTimeout(timer);},[companyId,lines,open,product?.id,query]);
 const numeric=useMemo(()=>({yield:Number(yieldQuantity.replace(",",".")),portions:Number(portions.replace(",",".")),waste:Number(waste.replace(",","."))}),[portions,waste,yieldQuantity]);
 const valid=numeric.yield>0&&numeric.portions>0&&numeric.waste>=0&&numeric.waste<100&&lines.length>0&&lines.every(line=>Number(line.quantity.replace(",","."))>0);
 function add(item:Candidate){const base=unitCode(item.unit);setLines(current=>[...current,{productId:item.id,productName:item.name,productCode:item.internal_sku,quantity:"1",unitCode:base,baseUnitCode:base,recipeKind:item.recipe_kind}]);setQuery("");}
 async function saveDraft(duplicateFromVersionId:string|null=null){if(!product||!valid){setFormError("Completa rendimiento, porciones y al menos un ingrediente con cantidad válida.");return null;}setSaving(true);setFormError(null);const components=lines.map((line,index)=>({product_id:line.productId,quantity:Number(line.quantity.replace(",",".")),unit_code:line.unitCode,base_unit_code:line.baseUnitCode,sort_order:index}));const fingerprint=JSON.stringify({product:product.id,recipeKind,numeric,yieldUnit,components,duplicateFromVersionId});const{data,error}=await getSupabaseClient().rpc("save_culinary_recipe_draft",{p_company_id:companyId,p_product_id:product.id,p_recipe_kind:recipeKind,p_yield_quantity:numeric.yield,p_yield_unit_code:yieldUnit,p_portion_count:numeric.portions,p_waste_percent:numeric.waste,p_components:components,p_client_request_id:keys.get("save-recipe",fingerprint),p_duplicate_from_version_id:duplicateFromVersionId});setSaving(false);if(error){setFormError(message(error,"Revisa la receta e intenta guardarla nuevamente."));return null;}keys.clear("save-recipe");await load();toast({title:duplicateFromVersionId?"Versión duplicada":"Borrador guardado",description:duplicateFromVersionId?"Se creó un borrador nuevo sin modificar la receta activa.":"La receta completa quedó registrada en una sola operación.",tone:"success"});return data as {version_id:string};}
 async function activate(){let versionId=context?.draft?.id;if(!versionId){const saved=await saveDraft();versionId=saved?.version_id;}if(!versionId)return;setActivating(true);const{error}=await getSupabaseClient().rpc("activate_culinary_recipe_version",{p_version_id:versionId,p_expected_status:"draft"});setActivating(false);if(error){setFormError(message(error,"Corrige los bloqueos e intenta activar de nuevo."));return;}await load();toast({title:"Receta activada",description:"Las próximas ventas usarán esta versión. Las ventas anteriores no cambian.",tone:"success"});}
 const cost=context?.draft?.cost??context?.active?.cost;
 return <Modal open={open} onOpenChange={value=>{if(!saving&&!activating)onOpenChange(value);}} eyebrow="Operación culinaria" title={`Receta · ${product?.name??(recipeKind==="preparation"?"Preparación":"Platillo")}`} description={recipeKind==="preparation"?"Define la base intermedia. Al vender, Satrapy expandirá sus insumos dentro de cada platillo que la use.":"Define el rendimiento y los ingredientes. Satrapy normaliza cantidades, calcula el costo y conserva cada versión utilizada."} className="recipe-editor" closeDisabled={saving||activating} footer={<><Button variant="secondary" disabled={saving||activating} onClick={()=>onOpenChange(false)}>Cerrar</Button>{context?.active&&!context?.draft&&<Button variant="secondary" loading={saving} disabled={!valid||activating} onClick={()=>void saveDraft(context.active!.id)}>Duplicar versión activa</Button>}<Button variant="secondary" loading={saving} disabled={!valid||activating} onClick={()=>void saveDraft()}>Guardar borrador</Button><Button variant="primary" loading={activating} disabled={!valid||saving} onClick={()=>void activate()}>Activar receta</Button></>}>
  {loading?<p role="status">Cargando receta…</p>:<div className="recipe-editor__body">
   {formError&&<p className="recipe-editor__error" role="alert">{formError}</p>}
   <section className="recipe-editor__setup" aria-labelledby="recipe-yield-title"><div><h3 id="recipe-yield-title">Rendimiento</h3><p>Indica cuánto produce esta preparación y cuántas porciones sirve.</p></div><div className="recipe-editor__setup-fields"><Field label="Cantidad producida"><Input inputMode="decimal" value={yieldQuantity} onChange={event=>setYieldQuantity(event.target.value)} aria-invalid={numeric.yield<=0||undefined}/></Field><Field label="Unidad del rendimiento"><Select value={yieldUnit} onValueChange={setYieldUnit} ariaLabel="Unidad del rendimiento" options={units}/></Field><Field label="Número de porciones"><Input inputMode="decimal" value={portions} onChange={event=>setPortions(event.target.value)} aria-invalid={numeric.portions<=0||undefined}/></Field><Field label="Merma porcentual" hint="Captúrala sólo cuando esté comprobada."><Input inputMode="decimal" value={waste} onChange={event=>setWaste(event.target.value)} aria-invalid={(numeric.waste<0||numeric.waste>=100)||undefined}/></Field></div></section>
   <section className="recipe-editor__ingredients" aria-labelledby="recipe-ingredients-title"><header><div><h3 id="recipe-ingredients-title">Insumos y preparaciones</h3><p>Busca insumos del catálogo. Las preparaciones activas se expanden automáticamente al vender.</p></div><Badge tone={lines.length?"success":"warning"}>{lines.length} componentes</Badge></header><div className="recipe-editor__search"><Search size={16} aria-hidden="true"/><Input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Ej. tomate, salsa verde o ING-001" aria-label="Buscar insumo o preparación"/></div>{query.trim()&&<div className="recipe-editor__results" aria-label="Resultados de insumos">{searching?<p role="status">Buscando…</p>:candidates.length?candidates.map(item=><button type="button" key={item.id} onClick={()=>add(item)}><span><strong>{item.name}</strong><small>{item.internal_sku} · {item.recipe_kind==="preparation"?"Preparación":item.unit??"Sin unidad"}</small></span><Plus size={16} aria-hidden="true"/></button>):<p>No hay coincidencias. Revisa el nombre o código.</p>}</div>}
   <div className="recipe-editor__lines">{lines.length?lines.map((line,index)=><article key={line.productId}><div className="recipe-editor__line-name"><ChefHat size={17} aria-hidden="true"/><span><strong>{line.productName}</strong><small>{line.productCode}{line.recipeKind==="preparation"?" · Preparación":""}</small></span></div><Field label={`Cantidad de ${line.productName}`}><Input inputMode="decimal" value={line.quantity} onChange={event=>setLines(current=>current.map((item,itemIndex)=>itemIndex===index?{...item,quantity:event.target.value}:item))}/></Field><Field label={`Unidad de ${line.productName}`}><Select value={line.unitCode} onValueChange={value=>setLines(current=>current.map((item,itemIndex)=>itemIndex===index?{...item,unitCode:value,baseUnitCode:line.recipeKind==="preparation"?value:item.baseUnitCode}:item))} ariaLabel={`Unidad de ${line.productName}`} options={units}/></Field><Button size="icon" variant="ghost" aria-label={`Quitar ${line.productName}`} onClick={()=>setLines(current=>current.filter(item=>item.productId!==line.productId))}><Trash2 size={16} aria-hidden="true"/></Button></article>):<div className="recipe-editor__empty"><ChefHat size={22} aria-hidden="true"/><strong>Aún no hay insumos</strong><p>Busca un insumo por nombre o código para comenzar la receta.</p>{onCreateIngredient&&<Button type="button" size="sm" variant="secondary" onClick={onCreateIngredient}><Plus size={15} aria-hidden="true"/> Crear primer insumo</Button>}</div>}</div></section>
   <section className="recipe-editor__summary" aria-live="polite"><div><small>Costo total</small><strong>{money(cost?.total_cost,context?.currency_code??"MXN")}</strong></div><div><small>Costo por porción</small><strong>{money(cost?.cost_per_portion,context?.currency_code??"MXN")}</strong></div><div><small>Precio de venta</small><strong>{money(context?.sale_price,context?.currency_code??"MXN")}</strong></div><div><small>Margen estimado</small><strong>{context?.sale_price!=null&&cost?.cost_per_portion!=null?money(context.sale_price-cost.cost_per_portion,context.currency_code):"Pendiente"}</strong></div>{cost&&!cost.allowed&&<p>{cost.blockers?.[0]?.message??"Completa la información pendiente para calcular el costo."}</p>}</section>
  </div>}
 </Modal>;
}
