"use client";

import { AlertTriangle, RefreshCw, SlidersHorizontal } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { DataPagination, DataState, DataToolbar, Table } from "@/app/components/ui/data";
import { Badge, Button, Field, Input, Modal, useToast } from "@/app/components/ui/primitives";
import { OperationIdempotencyKeys } from "@/app/lib/operation-idempotency";
import { getSupabaseClient } from "@/app/lib/supabase";

type Ingredient={product_id:string;internal_sku:string;name:string;base_unit:string;current_cost:number|null;previous_cost:number|null;change_amount:number|null;change_percent:number|null;receipt_count:number;last_receipt_date:string|null};
type Dish={product_id:string;internal_sku:string;name:string;sale_price:number|null;projected_cost:number|null;projected_margin_percent:number|null;realized_margin_percent:number|null;minimum_margin_percent:number|null;threshold_active:boolean;below_threshold:boolean;quantity_sold:number};
type Analysis={period:{from:string;to:string};currency_code:string;summary:{ingredients_with_cost:number;ingredients_changed:number;dishes_below_threshold:number;realized_sales:number;realized_margin:number|null};ingredients:Ingredient[];dishes:Dish[];ingredient_pagination:{page:number;page_size:number;total:number};dish_pagination:{page:number;page_size:number;total:number}};
type ThresholdDraft={dish:Dish;percent:string;active:boolean;reason:string};
const startOfWeek=()=>{const value=new Date();const day=(value.getDay()+6)%7;value.setDate(value.getDate()-day);return value.toISOString().slice(0,10);};

export function RestaurantCostAnalysis({companyId}:{companyId:string}){
  const {toast}=useToast();const keys=useRef(new OperationIdempotencyKeys());
  const [week,setWeek]=useState(startOfWeek());const [query,setQuery]=useState("");const [ingredientPage,setIngredientPage]=useState(1);const [dishPage,setDishPage]=useState(1);const [data,setData]=useState<Analysis|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [threshold,setThreshold]=useState<ThresholdDraft|null>(null);const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError(null);const {data:result,error:rpcError}=await getSupabaseClient().rpc("get_restaurant_weekly_cost_analysis",{p_company_id:companyId,p_week_start:week,p_query:query.trim()||null,p_ingredient_page:ingredientPage,p_dish_page:dishPage,p_page_size:20});if(rpcError)setError(rpcError.message.includes("schema cache")?"Falta aplicar la migración de compras y márgenes en Supabase.":"No se pudo calcular el análisis semanal.");else setData(result as Analysis);setLoading(false);},[companyId,dishPage,ingredientPage,query,week]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),180);return()=>clearTimeout(timer);},[load]);
  const currency=data?.currency_code??"MXN";const money=(value:number|null)=>value==null?"Pendiente":new Intl.NumberFormat("es-MX",{style:"currency",currency}).format(value);const percent=(value:number|null)=>value==null?"Pendiente":`${value.toLocaleString("es-MX",{maximumFractionDigits:2})}%`;
  async function saveThreshold(){if(!threshold||Number(threshold.percent)<0||Number(threshold.percent)>=100||threshold.reason.trim().length<5)return;setBusy(true);const fingerprint=JSON.stringify({product:threshold.dish.product_id,percent:threshold.percent,active:threshold.active,reason:threshold.reason});const {error:rpcError}=await getSupabaseClient().rpc("set_restaurant_margin_threshold",{p_company_id:companyId,p_product_id:threshold.dish.product_id,p_minimum_margin_percent:Number(threshold.percent),p_active:threshold.active,p_reason:threshold.reason.trim(),p_client_request_id:keys.current.get("restaurant-margin",fingerprint)});setBusy(false);if(rpcError){toast({title:"No se guardó la alerta",description:rpcError.message,tone:"error"});return;}keys.current.clear("restaurant-margin");setThreshold(null);toast({title:"Límite actualizado",description:"El margen del platillo se evaluó con el nuevo límite.",tone:"success"});await load();}
  return <div className="content-frame restaurant-cost-analysis">
    <div className="page-heading"><div><span className="eyebrow">Rentabilidad del menú</span><h1>Costos y márgenes</h1><p>Compara precios de insumos y vigila el margen proyectado y real de cada platillo por semana.</p></div><Button onClick={()=>void load()}><RefreshCw size={16}/> Actualizar</Button></div>
    <div className="restaurant-cost-controls"><Field label="Semana que inicia"><Input type="date" max={startOfWeek()} value={week} onChange={event=>{setWeek(event.target.value);setIngredientPage(1);setDishPage(1);}}/></Field><DataToolbar search={query} onSearchChange={value=>{setQuery(value);setIngredientPage(1);setDishPage(1);}} placeholder="Buscar insumo o platillo"/></div>
    <DataState loading={loading&&!data} error={error} hasData={data?1:0} empty="No hay información de costos para esta semana.">
      {data&&<><section className="restaurant-cost-kpis" aria-label="Resumen semanal"><article><span>Insumos con costo</span><strong>{data.summary.ingredients_with_cost}</strong><small>{data.summary.ingredients_changed} cambiaron esta semana</small></article><article><span>Ventas realizadas</span><strong>{money(data.summary.realized_sales)}</strong><small>Tickets no cancelados</small></article><article><span>Margen real</span><strong>{money(data.summary.realized_margin)}</strong><small>Con costo congelado al vender</small></article><article className={data.summary.dishes_below_threshold?"is-warning":""}><span>Alertas de margen</span><strong>{data.summary.dishes_below_threshold}</strong><small>Platillos debajo de su límite</small></article></section>
      <section className="restaurant-analysis-section"><header><div><h2>Variación de precios de insumos</h2><p>Costo vigente al cierre de la semana frente al costo anterior.</p></div><Badge tone="neutral">{data.ingredient_pagination.total} insumos</Badge></header><Table ariaLabel="Variación de precios de insumos"><thead><tr><th>Insumo</th><th className="number-cell">Costo anterior</th><th className="number-cell">Costo actual</th><th className="number-cell">Variación</th><th className="number-cell">Entradas</th></tr></thead><tbody>{data.ingredients.map(item=><tr key={item.product_id}><td><strong>{item.name}</strong><small>{item.internal_sku} · {item.base_unit}</small></td><td className="number-cell">{money(item.previous_cost)}</td><td className="number-cell">{money(item.current_cost)}</td><td className="number-cell"><Badge tone={item.change_percent!=null&&item.change_percent>0?"warning":item.change_percent!=null&&item.change_percent<0?"success":"neutral"}>{percent(item.change_percent)}</Badge></td><td className="number-cell">{item.receipt_count}</td></tr>)}</tbody></Table><DataPagination page={ingredientPage} total={data.ingredient_pagination.total} pageSize={20} onChange={setIngredientPage}/></section>
      <section className="restaurant-analysis-section"><header><div><h2>Rentabilidad por platillo</h2><p>El proyectado usa la receta y costo vigente; el real usa ventas y costo reconocido.</p></div><Badge tone={data.summary.dishes_below_threshold?"warning":"success"}>{data.summary.dishes_below_threshold} requieren atención</Badge></header><Table ariaLabel="Rentabilidad por platillo"><thead><tr><th>Platillo</th><th className="number-cell">Precio</th><th className="number-cell">Costo actual</th><th className="number-cell">Margen proyectado</th><th className="number-cell">Margen real</th><th>Límite</th></tr></thead><tbody>{data.dishes.map(item=><tr key={item.product_id} className={item.below_threshold?"restaurant-margin-warning":""}><td><strong>{item.name}</strong><small>{item.internal_sku} · {item.quantity_sold} vendidos</small></td><td className="number-cell">{money(item.sale_price)}</td><td className="number-cell">{money(item.projected_cost)}</td><td className="number-cell"><Badge tone={item.below_threshold?"danger":"neutral"}>{percent(item.projected_margin_percent)}</Badge></td><td className="number-cell">{percent(item.realized_margin_percent)}</td><td><Button size="sm" variant="ghost" onClick={()=>setThreshold({dish:item,percent:String(item.minimum_margin_percent??30),active:item.minimum_margin_percent==null?true:item.threshold_active,reason:"Ajuste del límite operativo"})}><SlidersHorizontal size={15}/>{item.minimum_margin_percent==null?"Configurar":`${percent(item.minimum_margin_percent)}${item.threshold_active?"":" · pausado"}`}</Button></td></tr>)}</tbody></Table><DataPagination page={dishPage} total={data.dish_pagination.total} pageSize={20} onChange={setDishPage}/></section></>}
    </DataState>
    <Modal open={Boolean(threshold)} onOpenChange={open=>!open&&!busy&&setThreshold(null)} eyebrow="Alerta por platillo" title={threshold?.dish.name??"Límite de margen"} description="Satrapy avisará cuando el margen proyectado baje de este porcentaje." closeDisabled={busy} footer={<><Button disabled={busy} onClick={()=>setThreshold(null)}>Cancelar</Button><Button variant="primary" loading={busy} onClick={()=>void saveThreshold()}>Guardar límite</Button></>}>
      {threshold&&<div className="restaurant-threshold-form"><Field label="Margen mínimo" hint="Porcentaje sobre el precio de venta"><div className="restaurant-number-unit"><Input type="number" min="0" max="99.99" step="0.01" value={threshold.percent} onChange={event=>setThreshold({...threshold,percent:event.target.value})}/><span>%</span></div></Field><label className="checkbox-field"><input type="checkbox" checked={threshold.active} onChange={event=>setThreshold({...threshold,active:event.target.checked})}/> Evaluar y mostrar alertas</label><Field label="Motivo"><Input minLength={5} value={threshold.reason} onChange={event=>setThreshold({...threshold,reason:event.target.value})}/></Field>{threshold.dish.below_threshold&&<p className="restaurant-threshold-warning"><AlertTriangle size={17}/> Actualmente este platillo está debajo del límite.</p>}</div>}
    </Modal>
  </div>;
}
