"use client";

import { AlertTriangle, Plus } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { DataState, DataToolbar } from "@/app/components/ui/data";
import { Badge, Button, Drawer, Field, Input, Modal, Select, useToast } from "@/app/components/ui/primitives";
import { getSupabaseClient } from "@/app/lib/supabase";

type Supplier = { id:string;code:string;display_name:string;legal_name:string|null;legal_entity_type:"physical"|"moral"|null;tax_id:string|null;tax_regime:string|null;fiscal_postal_code:string|null;country_code:string;contact_name:string|null;email:string|null;supplier_category:string|null;address_line:string|null;neighborhood:string|null;municipality:string|null;state_name:string|null;postal_code:string|null;phone:string|null;phone_extension:string|null;phone_status:"canonical"|"missing_area_code"|"invalid"|null;is_active:boolean;updated_at:string };
type Candidate = { id:string;code:string;display_name:string;tax_id:string|null };
type SupplierException = { id:string;batch_id:string;external_code:string;display_name:string;tax_id:string|null;source_row_number:number;conflict_kinds:string[];candidates:Candidate[] };
type Draft = { id?:string;display_name:string;legal_name:string;legal_entity_type:""|"physical"|"moral";tax_id:string;tax_regime:string;fiscal_postal_code:string;country_code:string;contact_name:string;email:string;supplier_category:string;address_line:string;neighborhood:string;municipality:string;state_name:string;postal_code:string;phone:string;phone_extension:string;is_active:boolean;updated_at?:string };
type DraftErrors = Partial<Record<"display_name"|"legal_entity_type"|"legal_name"|"tax_id"|"fiscal_postal_code"|"country_code"|"email"|"phone",string>>;
const emptyDraft:Draft={display_name:"",legal_name:"",legal_entity_type:"",tax_id:"",tax_regime:"",fiscal_postal_code:"",country_code:"MX",contact_name:"",email:"",supplier_category:"",address_line:"",neighborhood:"",municipality:"",state_name:"",postal_code:"",phone:"",phone_extension:"",is_active:true};
const pageSize=50;

export function SuppliersView({companyId,permissions}:{companyId:string;permissions:string[]}) {
  const {toast}=useToast();
  const [rows,setRows]=useState<Supplier[]>([]); const [total,setTotal]=useState(0); const [page,setPage]=useState(1); const [query,setQuery]=useState(""); const [debounced,setDebounced]=useState(""); const [active,setActive]=useState("all"); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  const [draft,setDraft]=useState<Draft|null>(null); const [draftErrors,setDraftErrors]=useState<DraftErrors>({}); const [saving,setSaving]=useState(false); const [exceptions,setExceptions]=useState<SupplierException[]>([]); const [exceptionPage,setExceptionPage]=useState(1); const [exceptionTotal,setExceptionTotal]=useState(0); const [resolution,setResolution]=useState<{item:SupplierException;target:string;reason:string}|null>(null);
  const request=useRef(0); const canManage=permissions.includes("manage_suppliers"); const canPromote=permissions.includes("promote_suppliers");
  useEffect(()=>{const timer=window.setTimeout(()=>{setDebounced(query.trim());setPage(1);},250);return()=>window.clearTimeout(timer);},[query]);
  const load=useCallback(async()=>{const current=++request.current;setLoading(true);setError(null);const {data,error:rpcError}=await getSupabaseClient().rpc("search_suppliers",{p_company_id:companyId,p_query:debounced||null,p_page:page,p_page_size:pageSize,p_is_active:active==="all"?null:active==="active",p_origin:null});if(current!==request.current)return;const result=data as {items?:Supplier[];pagination?:{total:number}}|null;setRows(result?.items??[]);setTotal(result?.pagination?.total??0);setError(rpcError?.message??null);setLoading(false);},[active,companyId,debounced,page]);
  const loadMigration=useCallback(async()=>{if(!canPromote)return;const {data:inbox}=await getSupabaseClient().rpc("list_supplier_import_exceptions",{p_company_id:companyId,p_page:exceptionPage,p_page_size:50});const result=inbox as {items?:SupplierException[];pagination?:{total:number}}|null;const items=result?.items??[];const nextTotal=result?.pagination?.total??0;setExceptionTotal(nextTotal);if(items.length===0&&nextTotal>0&&exceptionPage>1){setExceptionPage(value=>value-1);return;}setExceptions(items);},[canPromote,companyId,exceptionPage]);
  useEffect(()=>{void Promise.resolve().then(load);},[load]); useEffect(()=>{void Promise.resolve().then(loadMigration);},[loadMigration]);
  function updateDraft<K extends keyof Draft>(key:K,value:Draft[K]){setDraft(current=>current?{...current,[key]:value}:current);setDraftErrors(current=>({...current,[key]:undefined}));}
  function validateDraft(value:Draft){const errors:DraftErrors={};const mexico=value.country_code.trim().toUpperCase()==="MX";if(!value.display_name.trim())errors.display_name="Captura el nombre comercial.";if(!value.legal_entity_type)errors.legal_entity_type="Selecciona si es persona física o moral.";if(!value.is_active)return errors;if(!value.country_code.trim())errors.country_code="Indica el país.";if(value.legal_entity_type==="moral"&&!value.legal_name.trim())errors.legal_name="La razón social es obligatoria para una persona moral.";if(mexico&&!/^[A-Z&Ñ]{3,4}\d{6}[A-Z\d]{3}$/.test(value.tax_id.trim().toUpperCase()))errors.tax_id="Captura un RFC válido.";if(mexico&&!/^\d{5}$/.test(value.fiscal_postal_code))errors.fiscal_postal_code="El código postal fiscal debe tener 5 dígitos.";if(value.email.trim()&&!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(value.email.trim()))errors.email="Captura un correo válido.";const phoneDigits=value.phone.replace(/\D/g,"");if(value.phone.trim()&&((mexico&&phoneDigits.length!==10)||(!mexico&&(phoneDigits.length<8||phoneDigits.length>15))))errors.phone="Captura un teléfono completo con lada.";if(!value.email.trim()&&!value.phone.trim()){errors.email="Captura correo o teléfono.";errors.phone="Captura teléfono o correo.";}return errors;}
  async function save(asActive:boolean){if(!draft)return;const next={...draft,is_active:asActive};const errors=validateDraft(next);setDraftErrors(errors);if(Object.keys(errors).length)return;setSaving(true);const {error:saveError}=await getSupabaseClient().rpc("save_supplier",{p_company_id:companyId,p_supplier_id:next.id??null,p_display_name:next.display_name,p_legal_name:next.legal_name||null,p_legal_entity_type:next.legal_entity_type||null,p_tax_id:next.tax_id||null,p_tax_regime:next.tax_regime||null,p_fiscal_postal_code:next.fiscal_postal_code||null,p_country_code:next.country_code,p_contact_name:next.contact_name||null,p_email:next.email||null,p_phone:next.phone||null,p_phone_extension:next.phone_extension||null,p_supplier_category:next.supplier_category||null,p_address_line:next.address_line||null,p_neighborhood:next.neighborhood||null,p_municipality:next.municipality||null,p_state_name:next.state_name||null,p_postal_code:next.postal_code||null,p_is_active:next.is_active,p_expected_updated_at:next.updated_at??null});if(saveError)toast({title:"No se guardó el proveedor",description:saveError.message,tone:"error"});else{toast({title:asActive?"Proveedor guardado":"Borrador guardado",description:"El cambio quedó auditado automáticamente.",tone:"success"});setDraft(null);setDraftErrors({});await load();}setSaving(false);}
  async function resolve(decision:"link_existing"|"create_separate"){if(!resolution)return;setSaving(true);const {error:resolveError}=await getSupabaseClient().rpc("resolve_supplier_import_exception",{p_exception_id:resolution.item.id,p_decision:decision,p_target_supplier_id:decision==="link_existing"?resolution.target:null,p_reason:resolution.reason});if(resolveError)toast({title:"No se resolvió la excepción",description:resolveError.message,tone:"error"});else{toast({title:"Excepción resuelta",description:"La decisión y su evidencia quedaron auditadas.",tone:"success"});setResolution(null);await Promise.all([load(),loadMigration()]);}setSaving(false);}
  return <div className="content-frame"><header className="page-heading"><div><span className="eyebrow">Compras</span><h1>Proveedores</h1><p>Maestro canónico de Satrapy. El código de origen se conserva únicamente como referencia de importación.</p></div>{canManage&&<Button variant="primary" onClick={()=>{setDraftErrors({});setDraft({...emptyDraft});}}><Plus size={16}/> Nuevo proveedor</Button>}</header>
    {canPromote&&exceptionTotal>0&&<section className="supplier-exceptions"><header><div><AlertTriangle size={18}/><span><strong>Bandeja de excepciones</strong><small>Sólo identidades con RFC, código o nombre conflictivo requieren decisión.</small></span></div><Badge tone="warning">{exceptionTotal} pendientes</Badge></header>{exceptions.map(item=><article key={item.id}><span><strong>{item.display_name}</strong><small>Origen {item.external_code} · RFC {item.tax_id??"sin RFC"} · {item.conflict_kinds.map(conflictLabel).join(", ")}</small></span><Button size="sm" onClick={()=>setResolution({item,target:item.candidates[0]?.id??"",reason:""})}>Revisar</Button></article>)}{exceptionTotal>50&&<div className="data-pagination"><span>Página {exceptionPage} de {Math.ceil(exceptionTotal/50)} · {exceptionTotal} excepciones</span><div><Button size="sm" disabled={exceptionPage<=1} onClick={()=>setExceptionPage(value=>value-1)}>Anterior</Button><Button size="sm" disabled={exceptionPage*50>=exceptionTotal} onClick={()=>setExceptionPage(value=>value+1)}>Siguiente</Button></div></div>}</section>}
    <DataToolbar search={query} onSearchChange={setQuery} placeholder="Buscar nombre, código, RFC o teléfono" filters={<Select ariaLabel="Filtrar estado" value={active} onValueChange={value=>{setActive(value);setPage(1);}} options={[{value:"all",label:"Todos los estados"},{value:"active",label:"Activos"},{value:"inactive",label:"Inactivos"}]}/>} activeFilters={(query.trim()?1:0)+(active!=="all"?1:0)} onClear={()=>{setQuery("");setDebounced("");setActive("all");setPage(1);}} results={total}/>
    <DataState loading={loading&&rows.length===0} error={error} errorAction={<Button size="sm" onClick={()=>void load()}>Reintentar</Button>} hasData={rows.length} empty="Aún no hay proveedores canónicos."><div className="table-wrap surface-table"><table><thead><tr><th>Código</th><th>Proveedor</th><th>RFC</th><th>Contacto</th><th>Estado</th><th></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td className="mono">{row.code}</td><td><strong>{row.display_name}</strong><small>{[row.municipality,row.state_name].filter(Boolean).join(", ")||"Sin ubicación"}</small></td><td className="mono">{row.tax_id??"—"}</td><td>{row.contact_name&&<strong>{row.contact_name}</strong>}<span>{formatPhone(row.phone,row.phone_extension)}</span>{row.phone_status==="missing_area_code"&&<small>Sin lada</small>}{row.email&&<small>{row.email}</small>}</td><td><Badge tone={row.is_active?"success":"neutral"}>{row.is_active?"Activo":"Inactivo"}</Badge></td><td>{canManage&&<Button variant="ghost" size="sm" onClick={()=>{setDraftErrors({});setDraft({id:row.id,display_name:row.display_name,legal_name:row.legal_name??"",legal_entity_type:row.legal_entity_type??"",tax_id:row.tax_id??"",tax_regime:row.tax_regime??"",fiscal_postal_code:row.fiscal_postal_code??"",country_code:row.country_code??"MX",contact_name:row.contact_name??"",email:row.email??"",supplier_category:row.supplier_category??"",address_line:row.address_line??"",neighborhood:row.neighborhood??"",municipality:row.municipality??"",state_name:row.state_name??"",postal_code:row.postal_code??"",phone:phoneDigits(row.phone),phone_extension:row.phone_extension??"",is_active:row.is_active,updated_at:row.updated_at});}}>Editar</Button>}</td></tr>)}</tbody></table></div></DataState>
    {total>pageSize&&<div className="data-pagination"><span>Página {page} de {Math.ceil(total/pageSize)} · {total} proveedores</span><div><Button size="sm" disabled={page===1} onClick={()=>setPage(page-1)}>Anterior</Button><Button size="sm" disabled={page>=Math.ceil(total/pageSize)} onClick={()=>setPage(page+1)}>Siguiente</Button></div></div>}
    <Drawer open={Boolean(draft)} onOpenChange={open=>!open&&!saving&&setDraft(null)} title={draft?.id?"Editar proveedor":"Nuevo proveedor"} className="supplier-drawer">{draft&&<form id="supplier-form" className="supplier-master-form supplier-drawer-form" noValidate onSubmit={event=>{event.preventDefault();void save(true);}}>
      <p className="supplier-drawer__intro">El código se genera automáticamente. Guarda un borrador con nombre y tipo de persona; activa sólo cuando esté completo.</p>
      <section><h3>Identidad</h3><Field label="Nombre comercial *" error={draftErrors.display_name}><Input autoFocus value={draft.display_name} onChange={event=>updateDraft("display_name",event.target.value)}/></Field><Field label="Tipo de persona *" error={draftErrors.legal_entity_type}><Select ariaLabel="Tipo de persona" value={draft.legal_entity_type||"none"} onValueChange={value=>updateDraft("legal_entity_type",value==="none"?"":value as "physical"|"moral")} options={[{value:"none",label:"Selecciona una opción",disabled:true},{value:"physical",label:"Persona física"},{value:"moral",label:"Persona moral"}]}/></Field>{draft.legal_entity_type==="moral"&&<Field label="Razón social (para guardar proveedor)" error={draftErrors.legal_name}><Input value={draft.legal_name} onChange={event=>updateDraft("legal_name",event.target.value)}/></Field>}<Field label="RFC (para guardar proveedor)" error={draftErrors.tax_id}><Input value={draft.tax_id} onChange={event=>updateDraft("tax_id",event.target.value.toUpperCase())}/></Field><Field label="Régimen fiscal"><Input value={draft.tax_regime} onChange={event=>updateDraft("tax_regime",event.target.value)} placeholder="Opcional"/></Field><Field label="Código postal fiscal (para guardar proveedor)" error={draftErrors.fiscal_postal_code}><Input inputMode="numeric" maxLength={5} value={draft.fiscal_postal_code} onChange={event=>updateDraft("fiscal_postal_code",event.target.value.replace(/\D/g,""))}/></Field><Field label="País (ISO)" error={draftErrors.country_code}><Input maxLength={2} value={draft.country_code} onChange={event=>updateDraft("country_code",event.target.value.toUpperCase().replace(/[^A-Z]/g,""))} placeholder="MX"/></Field></section>
      <section><h3>Contacto principal</h3><Field label="Nombre del contacto"><Input value={draft.contact_name} onChange={event=>updateDraft("contact_name",event.target.value)}/></Field><Field label="Correo electrónico" error={draftErrors.email}><Input type="email" value={draft.email} onChange={event=>updateDraft("email",event.target.value)}/></Field><Field label="Teléfono con lada" error={draftErrors.phone}><Input inputMode="tel" value={draft.phone} onChange={event=>updateDraft("phone",event.target.value.replace(/[^0-9+]/g,""))} placeholder="7222787751"/></Field><Field label="Extensión"><Input inputMode="numeric" value={draft.phone_extension} onChange={event=>updateDraft("phone_extension",event.target.value.replace(/\D/g,""))}/></Field></section>
      <section><h3>Domicilio</h3><Field label="Calle y número"><Input value={draft.address_line} onChange={event=>updateDraft("address_line",event.target.value)}/></Field><Field label="Colonia"><Input value={draft.neighborhood} onChange={event=>updateDraft("neighborhood",event.target.value)}/></Field><Field label="Municipio o alcaldía"><Input value={draft.municipality} onChange={event=>updateDraft("municipality",event.target.value)}/></Field><Field label="Estado"><Input value={draft.state_name} onChange={event=>updateDraft("state_name",event.target.value)}/></Field></section>
      <div className="supplier-drawer__actions"><Button disabled={saving} onClick={()=>setDraft(null)}>Cancelar</Button><Button type="button" disabled={saving} onClick={()=>void save(false)}>Guardar borrador</Button><Button type="submit" variant="primary" loading={saving}>Guardar proveedor</Button></div>
    </form>}</Drawer>
    <Modal open={Boolean(resolution)} onOpenChange={open=>!open&&!saving&&setResolution(null)} eyebrow="Excepción de identidad" title={resolution?.item.display_name??"Revisar proveedor"} description="Vincula una identidad comprobada o documenta por qué debe crearse por separado." footer={<><Button disabled={saving} onClick={()=>setResolution(null)}>Cancelar</Button><Button disabled={!resolution?.reason.trim()} loading={saving} onClick={()=>void resolve("create_separate")}>Crear separado</Button><Button variant="primary" disabled={!resolution?.target||!resolution.reason.trim()} loading={saving} onClick={()=>void resolve("link_existing")}>Vincular candidato</Button></>}>{resolution&&<div className="supplier-resolution"><Select ariaLabel="Proveedor candidato" value={resolution.target||"none"} onValueChange={target=>setResolution({...resolution,target:target==="none"?"":target})} options={[{value:"none",label:"Selecciona un candidato",disabled:true},...resolution.item.candidates.map(candidate=>({value:candidate.id,label:`${candidate.display_name} · ${candidate.code} · ${candidate.tax_id??"sin RFC"}`}))]}/><label className="operation-reason">Motivo<textarea rows={3} value={resolution.reason} onChange={event=>setResolution({...resolution,reason:event.target.value})} placeholder="Describe la evidencia que sustenta la decisión"/></label></div>}</Modal>
  </div>;
}

function conflictLabel(value:string){return value==="tax_id"?"RFC coincidente":value==="code"?"código coincidente":"identidad coincidente";}
function phoneDigits(value:string|null){return value?.replace(/^\+52/,"").replace(/\D/g,"")??"";}
function formatPhone(value:string|null,extension:string|null){if(!value)return "—";const digits=value.replace(/\D/g,"");const local=digits.startsWith("52")&&digits.length===12?digits.slice(2):digits;if(local.length===10)return `+52 ${local.slice(0,3)} ${local.slice(3,6)} ${local.slice(6)}${extension?` ext. ${extension}`:""}`;return `${value}${extension?` ext. ${extension}`:""}`;}
