-- M4B · reversas operativas faltantes. Los documentos originales permanecen
-- inmutables; cada reversa es un documento separado, idempotente y auditado.

insert into public.permissions(code,description) values
 ('cancel_sales','Cancelar ventas confirmadas con restitución transaccional.'),
 ('reverse_receivable_payments','Revertir cobros y restaurar sus aplicaciones.'),
 ('reverse_cash_movements','Revertir entradas o salidas de caja mediante contramovimiento.'),
 ('reverse_supplier_credit_notes','Revertir notas de crédito y restaurar CxP.')
on conflict(code) do update set description=excluded.description;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r cross join public.permissions p where r.code in ('super_admin','direccion_admin') and p.code in ('cancel_sales','reverse_receivable_payments','reverse_cash_movements','reverse_supplier_credit_notes') on conflict do nothing;

create table public.sale_cancellations(
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,sale_id uuid not null unique references public.sales(id) on delete restrict,
 reason text not null check(nullif(trim(reason),'') is not null),client_request_id uuid not null,cancelled_by uuid references auth.users(id) on delete set null default auth.uid(),cancelled_at timestamptz not null default now(),unique(company_id,client_request_id)
);
create table public.sale_cancellation_items(
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,sale_cancellation_id uuid not null references public.sale_cancellations(id) on delete restrict,sale_item_id uuid not null unique references public.sale_items(id) on delete restrict,quantity numeric(18,6) not null check(quantity>0)
);
alter table public.inventory_ledger add column sale_cancellation_item_id uuid references public.sale_cancellation_items(id) on delete restrict;
alter table public.inventory_ledger drop constraint inventory_ledger_movement_type_check,drop constraint inventory_ledger_source_check;
alter table public.inventory_ledger add constraint inventory_ledger_movement_type_check check(movement_type in ('opening_snapshot','sale','sale_reversal','controlled_adjustment','physical_count_adjustment','transfer_out','transfer_in','purchase_receipt','purchase_receipt_reversal')),
 add constraint inventory_ledger_source_check check(
  (movement_type='opening_snapshot' and source_snapshot_item_id is not null and sale_item_id is null and inventory_count_line_id is null and inventory_transfer_line_id is null and purchase_receipt_line_id is null and sale_cancellation_item_id is null)
  or (movement_type='sale' and sale_item_id is not null and source_snapshot_item_id is null and inventory_count_line_id is null and inventory_transfer_line_id is null and purchase_receipt_line_id is null and sale_cancellation_item_id is null)
  or (movement_type='sale_reversal' and sale_cancellation_item_id is not null and source_snapshot_item_id is null and sale_item_id is null and inventory_count_line_id is null and inventory_transfer_line_id is null and purchase_receipt_line_id is null)
  or (movement_type='controlled_adjustment' and source_snapshot_item_id is null and sale_item_id is null and inventory_count_line_id is null and inventory_transfer_line_id is null and purchase_receipt_line_id is null and sale_cancellation_item_id is null)
  or (movement_type='physical_count_adjustment' and inventory_count_line_id is not null and source_snapshot_item_id is null and sale_item_id is null and inventory_transfer_line_id is null and purchase_receipt_line_id is null and sale_cancellation_item_id is null)
  or (movement_type in ('transfer_out','transfer_in') and inventory_transfer_line_id is not null and source_snapshot_item_id is null and sale_item_id is null and inventory_count_line_id is null and purchase_receipt_line_id is null and sale_cancellation_item_id is null)
  or (movement_type in ('purchase_receipt','purchase_receipt_reversal') and purchase_receipt_line_id is not null and purchase_receipt_id is not null and purchase_order_id is not null and supplier_id is not null and source_snapshot_item_id is null and sale_item_id is null and inventory_count_line_id is null and inventory_transfer_line_id is null and sale_cancellation_item_id is null)
 );
create unique index inventory_ledger_sale_cancellation_once_idx on public.inventory_ledger(sale_cancellation_item_id) where sale_cancellation_item_id is not null;

create table public.receivable_payment_reversals(
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,receivable_payment_id uuid not null unique references public.receivable_payments(id) on delete restrict,
 reason text not null check(nullif(trim(reason),'') is not null),client_request_id uuid not null,reversed_by uuid references auth.users(id) on delete set null default auth.uid(),reversed_at timestamptz not null default now(),unique(company_id,client_request_id)
);
create table public.cash_movement_reversals(
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,cash_movement_id uuid not null unique references public.cash_movements(id) on delete restrict,reversal_movement_id uuid not null unique references public.cash_movements(id) on delete restrict,
 reason text not null check(nullif(trim(reason),'') is not null),client_request_id uuid not null,reversed_by uuid references auth.users(id) on delete set null default auth.uid(),reversed_at timestamptz not null default now(),unique(company_id,client_request_id)
);
create table public.supplier_credit_note_reversals(
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,credit_note_id uuid not null unique references public.supplier_invoices(id) on delete restrict,
 reason text not null check(nullif(trim(reason),'') is not null),client_request_id uuid not null,reversed_by uuid references auth.users(id) on delete set null default auth.uid(),reversed_at timestamptz not null default now(),unique(company_id,client_request_id)
);

create or replace function public.capture_operational_reversal_event()
returns trigger language plpgsql security definer set search_path=public as $$
begin
 if not public.accounting_operational_matrix_active(new.company_id) then return new;end if;
 if tg_table_name='sale_cancellations' then perform public.capture_exact_accounting_reversal(new.company_id,'sale_confirmed','sale_cancelled','sale',new.sale_id,new.cancelled_at::date,new.cancelled_at,'Cancelación de venta');
 elsif tg_table_name='receivable_payment_reversals' then perform public.capture_exact_accounting_reversal(new.company_id,'receivable_payment_confirmed','receivable_payment_reversed','receivable_payment',new.receivable_payment_id,new.reversed_at::date,new.reversed_at,'Reversa de cobro');
 elsif tg_table_name='supplier_credit_note_reversals' then perform public.capture_exact_accounting_reversal(new.company_id,'supplier_credit_note_confirmed','supplier_credit_note_reversed','supplier_invoice',new.credit_note_id,new.reversed_at::date,new.reversed_at,'Reversa de nota de crédito');end if;return new;
end$$;
create constraint trigger sale_cancellations_accounting_event after insert on public.sale_cancellations deferrable initially deferred for each row execute function public.capture_operational_reversal_event();
create constraint trigger receivable_payment_reversals_accounting_event after insert on public.receivable_payment_reversals deferrable initially deferred for each row execute function public.capture_operational_reversal_event();
create constraint trigger supplier_credit_note_reversals_accounting_event after insert on public.supplier_credit_note_reversals deferrable initially deferred for each row execute function public.capture_operational_reversal_event();

create or replace function public.cancel_sale(p_company_id uuid,p_sale_id uuid,p_reason text,p_client_request_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_sale public.sales%rowtype;v_existing public.sale_cancellations%rowtype;v_receivable public.customer_receivables%rowtype;v_payment public.sale_payments%rowtype;v_item record;v_balance numeric;v_cancellation uuid;v_cancel_item uuid;
begin
 if auth.uid() is null or not public.has_company_permission(p_company_id,'cancel_sales') then raise exception 'No autorizado para cancelar ventas.';end if;if nullif(trim(coalesce(p_reason,'')),'') is null or p_client_request_id is null then raise exception 'Motivo y llave son obligatorios.';end if;select * into v_existing from public.sale_cancellations where company_id=p_company_id and client_request_id=p_client_request_id;if found then return to_jsonb(v_existing)||jsonb_build_object('idempotent',true);end if;
 select * into v_sale from public.sales where id=p_sale_id and company_id=p_company_id for update;if not found or exists(select 1 from public.sale_cancellations where sale_id=p_sale_id) then raise exception 'Venta no disponible para cancelación.';end if;
 if v_sale.sale_type='credit' then select * into v_receivable from public.customer_receivables where sale_id=v_sale.id for update;if not found or v_receivable.outstanding_amount<>v_receivable.original_amount then raise exception 'La venta tiene cobros aplicados; reviértalos primero.';end if;update public.customer_receivables set outstanding_amount=0 where id=v_receivable.id;else select * into v_payment from public.sale_payments where sale_id=v_sale.id;if v_payment.settlement_kind='cash_drawer' and not exists(select 1 from public.cash_sessions where id=v_sale.cash_session_id and status='open' for share) then raise exception 'La devolución en efectivo requiere la misma caja abierta.';end if;end if;
 insert into public.sale_cancellations(company_id,sale_id,reason,client_request_id) values(p_company_id,v_sale.id,trim(p_reason),p_client_request_id) returning id into v_cancellation;
 for v_item in select si.*,il.location_id from public.sale_items si join public.inventory_ledger il on il.sale_item_id=si.id and il.movement_type='sale' where si.sale_id=v_sale.id order by il.location_id,si.product_id for update of il loop insert into public.sale_cancellation_items(company_id,sale_cancellation_id,sale_item_id,quantity) values(p_company_id,v_cancellation,v_item.id,v_item.quantity) returning id into v_cancel_item;select quantity_on_hand into v_balance from public.inventory_balances where location_id=v_item.location_id and product_id=v_item.product_id for update;update public.inventory_balances set quantity_on_hand=quantity_on_hand+v_item.quantity,updated_at=now() where location_id=v_item.location_id and product_id=v_item.product_id returning quantity_on_hand into v_balance;insert into public.inventory_ledger(company_id,location_id,product_id,quantity_delta,balance_after,movement_type,sale_cancellation_item_id,actor_id) values(p_company_id,v_item.location_id,v_item.product_id,v_item.quantity,v_balance,'sale_reversal',v_cancel_item,auth.uid());end loop;
 if v_sale.sale_type='cash' and v_payment.settlement_kind='cash_drawer' then insert into public.cash_movements(company_id,cash_session_id,movement_type,amount,actor_id,reason,source_entity_type,source_entity_id) values(p_company_id,v_sale.cash_session_id,'paid_out',-v_sale.total_amount,auth.uid(),trim(p_reason),'sale_cancellation',v_cancellation);end if;
 insert into public.audit_log(company_id,actor_id,action,entity_type,entity_id,metadata) values(p_company_id,auth.uid(),'sale.cancelled','sale_cancellation',v_cancellation,jsonb_build_object('sale_id',v_sale.id,'reason',p_reason,'client_request_id',p_client_request_id));return jsonb_build_object('id',v_cancellation,'sale_id',v_sale.id,'idempotent',false);
end$$;

create or replace function public.reverse_receivable_payment(p_company_id uuid,p_payment_id uuid,p_reason text,p_client_request_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_payment public.receivable_payments%rowtype;v_existing public.receivable_payment_reversals%rowtype;v_app record;v_id uuid;
begin
 if auth.uid() is null or not public.has_company_permission(p_company_id,'reverse_receivable_payments') then raise exception 'No autorizado para revertir cobros.';end if;if nullif(trim(coalesce(p_reason,'')),'') is null or p_client_request_id is null then raise exception 'Motivo y llave son obligatorios.';end if;select * into v_existing from public.receivable_payment_reversals where company_id=p_company_id and client_request_id=p_client_request_id;if found then return to_jsonb(v_existing)||jsonb_build_object('idempotent',true);end if;
 select * into v_payment from public.receivable_payments where id=p_payment_id and company_id=p_company_id for share;if not found or exists(select 1 from public.receivable_payment_reversals where receivable_payment_id=p_payment_id) then raise exception 'Cobro no disponible para reversa.';end if;if v_payment.settlement_kind='cash_drawer' and not exists(select 1 from public.cash_sessions where id=v_payment.cash_session_id and status='open' for share) then raise exception 'La reversa en efectivo requiere la caja original abierta.';end if;
 for v_app in select a.receivable_id,a.amount,r.original_amount,r.outstanding_amount from public.receivable_payment_applications a join public.customer_receivables r on r.id=a.receivable_id where a.receivable_payment_id=p_payment_id order by r.id for update of r loop if v_app.outstanding_amount+v_app.amount>v_app.original_amount then raise exception 'La reversa excedería el saldo original.';end if;update public.customer_receivables set outstanding_amount=outstanding_amount+v_app.amount where id=v_app.receivable_id;end loop;
 insert into public.receivable_payment_reversals(company_id,receivable_payment_id,reason,client_request_id) values(p_company_id,p_payment_id,trim(p_reason),p_client_request_id) returning id into v_id;if v_payment.settlement_kind='cash_drawer' then insert into public.cash_movements(company_id,cash_session_id,movement_type,amount,actor_id,reason,source_entity_type,source_entity_id) values(p_company_id,v_payment.cash_session_id,'paid_out',-v_payment.amount,auth.uid(),trim(p_reason),'receivable_payment_reversal',v_id);end if;insert into public.audit_log(company_id,actor_id,action,entity_type,entity_id,metadata) values(p_company_id,auth.uid(),'receivable_payment.reversed','receivable_payment_reversal',v_id,jsonb_build_object('payment_id',p_payment_id,'reason',p_reason,'client_request_id',p_client_request_id));return jsonb_build_object('id',v_id,'payment_id',p_payment_id,'idempotent',false);
end$$;

create or replace function public.reverse_cash_drawer_movement(p_company_id uuid,p_movement_id uuid,p_reason text,p_client_request_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_movement public.cash_movements%rowtype;v_existing public.cash_movement_reversals%rowtype;v_reversal_movement uuid;v_id uuid;
begin
 if auth.uid() is null or not public.has_company_permission(p_company_id,'reverse_cash_movements') then raise exception 'No autorizado para revertir caja.';end if;if nullif(trim(coalesce(p_reason,'')),'') is null or p_client_request_id is null then raise exception 'Motivo y llave son obligatorios.';end if;select * into v_existing from public.cash_movement_reversals where company_id=p_company_id and client_request_id=p_client_request_id;if found then return to_jsonb(v_existing)||jsonb_build_object('idempotent',true);end if;
 select * into v_movement from public.cash_movements where id=p_movement_id and company_id=p_company_id for share;if not found or v_movement.movement_type not in ('paid_in','paid_out') or exists(select 1 from public.cash_movement_reversals where cash_movement_id=p_movement_id) then raise exception 'Movimiento no disponible para reversa.';end if;if not exists(select 1 from public.cash_sessions where id=v_movement.cash_session_id and status='open' for share) then raise exception 'La caja debe continuar abierta.';end if;
 insert into public.cash_movements(company_id,cash_session_id,movement_type,amount,actor_id,reason,source_entity_type,source_entity_id) values(p_company_id,v_movement.cash_session_id,case when v_movement.movement_type='paid_in' then 'paid_out' else 'paid_in' end,-v_movement.amount,auth.uid(),trim(p_reason),'cash_movement_reversal',v_movement.id) returning id into v_reversal_movement;insert into public.cash_movement_reversals(company_id,cash_movement_id,reversal_movement_id,reason,client_request_id) values(p_company_id,v_movement.id,v_reversal_movement,trim(p_reason),p_client_request_id) returning id into v_id;insert into public.audit_log(company_id,actor_id,action,entity_type,entity_id,metadata) values(p_company_id,auth.uid(),'cash_movement.reversed','cash_movement_reversal',v_id,jsonb_build_object('movement_id',p_movement_id,'reversal_movement_id',v_reversal_movement,'reason',p_reason));return jsonb_build_object('id',v_id,'reversal_movement_id',v_reversal_movement,'idempotent',false);
end$$;

create or replace function public.reverse_supplier_credit_note(p_company_id uuid,p_credit_note_id uuid,p_reason text,p_client_request_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_note public.supplier_invoices%rowtype;v_payable public.accounts_payable%rowtype;v_existing public.supplier_credit_note_reversals%rowtype;v_id uuid;
begin
 if auth.uid() is null or not public.has_company_permission(p_company_id,'reverse_supplier_credit_notes') then raise exception 'No autorizado para revertir notas de crédito.';end if;if nullif(trim(coalesce(p_reason,'')),'') is null or p_client_request_id is null then raise exception 'Motivo y llave son obligatorios.';end if;select * into v_existing from public.supplier_credit_note_reversals where company_id=p_company_id and client_request_id=p_client_request_id;if found then return to_jsonb(v_existing)||jsonb_build_object('idempotent',true);end if;
 select * into v_note from public.supplier_invoices where id=p_credit_note_id and company_id=p_company_id for share;if not found or v_note.document_type<>'credit_note' or v_note.status<>'confirmed' or exists(select 1 from public.supplier_credit_note_reversals where credit_note_id=p_credit_note_id) then raise exception 'Nota de crédito no disponible para reversa.';end if;select * into v_payable from public.accounts_payable where supplier_invoice_id=v_note.original_invoice_id for update;if not found or v_payable.reversed_at is not null or v_payable.outstanding_amount+v_note.total>v_payable.original_amount then raise exception 'La CxP no puede restaurar esta nota.';end if;update public.accounts_payable set outstanding_amount=outstanding_amount+v_note.total where id=v_payable.id;insert into public.supplier_credit_note_reversals(company_id,credit_note_id,reason,client_request_id) values(p_company_id,v_note.id,trim(p_reason),p_client_request_id) returning id into v_id;insert into public.audit_log(company_id,actor_id,action,entity_type,entity_id,metadata) values(p_company_id,auth.uid(),'supplier_credit_note.reversed','supplier_credit_note_reversal',v_id,jsonb_build_object('credit_note_id',v_note.id,'payable_id',v_payable.id,'reason',p_reason));return jsonb_build_object('id',v_id,'credit_note_id',v_note.id,'idempotent',false);
end$$;

alter table public.sale_cancellations enable row level security;alter table public.sale_cancellation_items enable row level security;alter table public.receivable_payment_reversals enable row level security;alter table public.cash_movement_reversals enable row level security;alter table public.supplier_credit_note_reversals enable row level security;
create policy sale_cancellations_read on public.sale_cancellations for select to authenticated using(public.has_company_permission(company_id,'view_sales'));create policy sale_cancellation_items_read on public.sale_cancellation_items for select to authenticated using(public.has_company_permission(company_id,'view_sales'));create policy receivable_payment_reversals_read on public.receivable_payment_reversals for select to authenticated using(public.has_company_permission(company_id,'view_customer_credit'));create policy cash_movement_reversals_read on public.cash_movement_reversals for select to authenticated using(public.has_company_permission(company_id,'view_cash_reports'));create policy supplier_credit_note_reversals_read on public.supplier_credit_note_reversals for select to authenticated using(public.has_company_permission(company_id,'view_supplier_invoices'));
grant select on public.sale_cancellations,public.sale_cancellation_items,public.receivable_payment_reversals,public.cash_movement_reversals,public.supplier_credit_note_reversals to authenticated;
revoke all on function public.cancel_sale(uuid,uuid,text,uuid),public.reverse_receivable_payment(uuid,uuid,text,uuid),public.reverse_cash_drawer_movement(uuid,uuid,text,uuid),public.reverse_supplier_credit_note(uuid,uuid,text,uuid) from public,anon;grant execute on function public.cancel_sale(uuid,uuid,text,uuid),public.reverse_receivable_payment(uuid,uuid,text,uuid),public.reverse_cash_drawer_movement(uuid,uuid,text,uuid),public.reverse_supplier_credit_note(uuid,uuid,text,uuid) to authenticated;
